/* Generated by flowc - do not edit */
/* Source: tests/programs/app_healthcheck.flow */
#include "flow_runtime.h"

/* From: stdlib/char.flow */

fl_bool fl_char_is_digit(fl_char c);

fl_bool fl_char_is_alpha(fl_char c);

fl_bool fl_char_is_alphanumeric(fl_char c);

fl_bool fl_char_is_whitespace(fl_char c);

fl_int fl_char_to_code(fl_char c);

fl_char fl_char_from_code(fl_int n);

FL_String* fl_char_to_string(fl_char c);

/* Flow: char.is_digit */
fl_bool fl_char_is_digit(fl_char c) {
    return ((c >= 48) && (c <= 57));
}

/* Flow: char.is_alpha */
fl_bool fl_char_is_alpha(fl_char c) {
    return ((((c >= 97) && (c <= 122)) || ((c >= 65) && (c <= 90))) || (c == 95));
}

/* Flow: char.is_alphanumeric */
fl_bool fl_char_is_alphanumeric(fl_char c) {
    return (fl_char_is_alpha(c) || fl_char_is_digit(c));
}

/* Flow: char.is_whitespace */
fl_bool fl_char_is_whitespace(fl_char c) {
    return ((((c == 32) || (c == 9)) || (c == 10)) || (c == 13));
}

/* Flow: char.to_code */
fl_int fl_char_to_code(fl_char c) {
    return ((fl_int)c);
}

/* Flow: char.from_code */
fl_char fl_char_from_code(fl_int n) {
    return ((fl_char)n);
}

/* Flow: char.to_string */
FL_String* fl_char_to_string(fl_char c) {
    fl_int code = fl_char_to_code(c);
    if (code < 128) {
        void* buf = fl_mem_alloc(((fl_int64)1));
        fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)code));
        return fl_mem_to_string(buf, ((fl_int64)1));
    } else {
        if (code < 2048) {
            void* buf = fl_mem_alloc(((fl_int64)2));
            fl_int _fl_e_2;
            FL_CHECKED_DIV(code, 64, &_fl_e_2);
            fl_int _fl_e_1;
            FL_CHECKED_ADD(192, _fl_e_2, &_fl_e_1);
            fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)_fl_e_1));
            fl_int _fl_e_4;
            FL_CHECKED_MOD(code, 64, &_fl_e_4);
            fl_int _fl_e_3;
            FL_CHECKED_ADD(128, _fl_e_4, &_fl_e_3);
            fl_mem_write_byte(buf, ((fl_int64)1), ((fl_byte)_fl_e_3));
            return fl_mem_to_string(buf, ((fl_int64)2));
        } else {
            if (code < 65536) {
                void* buf = fl_mem_alloc(((fl_int64)3));
                fl_int _fl_e_6;
                FL_CHECKED_DIV(code, 4096, &_fl_e_6);
                fl_int _fl_e_5;
                FL_CHECKED_ADD(224, _fl_e_6, &_fl_e_5);
                fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)_fl_e_5));
                fl_int _fl_e_9;
                FL_CHECKED_DIV(code, 64, &_fl_e_9);
                fl_int _fl_e_8;
                FL_CHECKED_MOD(_fl_e_9, 64, &_fl_e_8);
                fl_int _fl_e_7;
                FL_CHECKED_ADD(128, _fl_e_8, &_fl_e_7);
                fl_mem_write_byte(buf, ((fl_int64)1), ((fl_byte)_fl_e_7));
                fl_int _fl_e_11;
                FL_CHECKED_MOD(code, 64, &_fl_e_11);
                fl_int _fl_e_10;
                FL_CHECKED_ADD(128, _fl_e_11, &_fl_e_10);
                fl_mem_write_byte(buf, ((fl_int64)2), ((fl_byte)_fl_e_10));
                return fl_mem_to_string(buf, ((fl_int64)3));
            } else {
                void* buf = fl_mem_alloc(((fl_int64)4));
                fl_int _fl_e_13;
                FL_CHECKED_DIV(code, 262144, &_fl_e_13);
                fl_int _fl_e_12;
                FL_CHECKED_ADD(240, _fl_e_13, &_fl_e_12);
                fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)_fl_e_12));
                fl_int _fl_e_16;
                FL_CHECKED_DIV(code, 4096, &_fl_e_16);
                fl_int _fl_e_15;
                FL_CHECKED_MOD(_fl_e_16, 64, &_fl_e_15);
                fl_int _fl_e_14;
                FL_CHECKED_ADD(128, _fl_e_15, &_fl_e_14);
                fl_mem_write_byte(buf, ((fl_int64)1), ((fl_byte)_fl_e_14));
                fl_int _fl_e_19;
                FL_CHECKED_DIV(code, 64, &_fl_e_19);
                fl_int _fl_e_18;
                FL_CHECKED_MOD(_fl_e_19, 64, &_fl_e_18);
                fl_int _fl_e_17;
                FL_CHECKED_ADD(128, _fl_e_18, &_fl_e_17);
                fl_mem_write_byte(buf, ((fl_int64)2), ((fl_byte)_fl_e_17));
                fl_int _fl_e_21;
                FL_CHECKED_MOD(code, 64, &_fl_e_21);
                fl_int _fl_e_20;
                FL_CHECKED_ADD(128, _fl_e_21, &_fl_e_20);
                fl_mem_write_byte(buf, ((fl_int64)3), ((fl_byte)_fl_e_20));
                return fl_mem_to_string(buf, ((fl_int64)4));
            }
        }
    }
}

/* From: stdlib/conv.flow */

FL_String* fl_conv_char_to_string(fl_char c);

FL_Option_int fl_conv_string_to_int(FL_String* s);

FL_Option_int64 fl_conv_string_to_int64(FL_String* s);

FL_Option_float fl_conv_string_to_float(FL_String* s);

FL_Option_float fl_conv_parse_float_rest(FL_String* s, fl_int len, fl_int pos, fl_float int_part, fl_bool negative, fl_bool has_digits_before);

FL_Option_float fl_conv_parse_float_exp(FL_String* s, fl_int len, fl_int pos, fl_float mantissa, fl_bool negative, fl_bool has_digits);

/* Flow: conv.char_to_string */
FL_String* fl_conv_char_to_string(fl_char c) {
    return fl_char_to_string(c);
}

/* Flow: conv.string_to_int */
FL_Option_int fl_conv_string_to_int(FL_String* s) {
    fl_int len = fl_string_len(s);
    if (len == 0) {
        return (FL_Option_int){.tag = 0};
    }
    fl_int start = 0;
    fl_bool negative = fl_false;
    FL_Option_char _fl_tmp_0 = fl_string_char_at(s, 0);
    if (_fl_tmp_0.tag == 1) {
        fl_char c = _fl_tmp_0.value;
        if (c == 45) {
            negative = fl_true;
            start = 1;
        } else {
            if (c == 43) {
                start = 1;
            }
        }
    } else {
        return (FL_Option_int){.tag = 0};
    }
    if (start >= len) {
        return (FL_Option_int){.tag = 0};
    }
    fl_int result = 0;
    fl_int i = start;
    while (i < len) {
        FL_Option_char _fl_tmp_1 = fl_string_char_at(s, i);
        if (_fl_tmp_1.tag == 1) {
            fl_char c = _fl_tmp_1.value;
            if (!fl_char_is_digit(c)) {
                return (FL_Option_int){.tag = 0};
            }
            fl_int _fl_e_1;
            FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_1);
            fl_int digit = _fl_e_1;
            fl_int _fl_e_3;
            FL_CHECKED_MUL(result, 10, &_fl_e_3);
            fl_int _fl_e_2;
            FL_CHECKED_ADD(_fl_e_3, digit, &_fl_e_2);
            result = _fl_e_2;
        } else {
            return (FL_Option_int){.tag = 0};
        }
        fl_int _fl_e_4;
        FL_CHECKED_ADD(i, 1, &_fl_e_4);
        i = _fl_e_4;
    }
    if (negative) {
        fl_int _fl_e_5;
        FL_CHECKED_SUB(0, result, &_fl_e_5);
        result = _fl_e_5;
    }
    return (FL_Option_int){.tag = 1, .value = result};
}

/* Flow: conv.string_to_int64 */
FL_Option_int64 fl_conv_string_to_int64(FL_String* s) {
    fl_int len = fl_string_len(s);
    if (len == 0) {
        return (FL_Option_int64){.tag = 0};
    }
    fl_int start = 0;
    fl_bool negative = fl_false;
    FL_Option_char _fl_tmp_2 = fl_string_char_at(s, 0);
    if (_fl_tmp_2.tag == 1) {
        fl_char c = _fl_tmp_2.value;
        if (c == 45) {
            negative = fl_true;
            start = 1;
        } else {
            if (c == 43) {
                start = 1;
            }
        }
    } else {
        return (FL_Option_int64){.tag = 0};
    }
    if (start >= len) {
        return (FL_Option_int64){.tag = 0};
    }
    fl_int64 result = ((fl_int64)0);
    fl_int i = start;
    while (i < len) {
        FL_Option_char _fl_tmp_3 = fl_string_char_at(s, i);
        if (_fl_tmp_3.tag == 1) {
            fl_char c = _fl_tmp_3.value;
            if (!fl_char_is_digit(c)) {
                return (FL_Option_int64){.tag = 0};
            }
            fl_int _fl_e_1;
            FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_1);
            fl_int64 digit = ((fl_int64)_fl_e_1);
            fl_int64 _fl_e_3;
            FL_CHECKED_MUL(result, ((fl_int64)10), &_fl_e_3);
            fl_int64 _fl_e_2;
            FL_CHECKED_ADD(_fl_e_3, digit, &_fl_e_2);
            result = _fl_e_2;
        } else {
            return (FL_Option_int64){.tag = 0};
        }
        fl_int _fl_e_4;
        FL_CHECKED_ADD(i, 1, &_fl_e_4);
        i = _fl_e_4;
    }
    if (negative) {
        fl_int64 _fl_e_5;
        FL_CHECKED_SUB(((fl_int64)0), result, &_fl_e_5);
        result = _fl_e_5;
    }
    return (FL_Option_int64){.tag = 1, .value = result};
}

/* Flow: conv.string_to_float */
FL_Option_float fl_conv_string_to_float(FL_String* s) {
    fl_int len = fl_string_len(s);
    if (len == 0) {
        return (FL_Option_float){.tag = 0};
    }
    fl_int start = 0;
    fl_bool negative = fl_false;
    FL_Option_char _fl_tmp_4 = fl_string_char_at(s, 0);
    if (_fl_tmp_4.tag == 1) {
        fl_char c = _fl_tmp_4.value;
        if (c == 45) {
            negative = fl_true;
            start = 1;
        } else {
            if (c == 43) {
                start = 1;
            }
        }
    } else {
        return (FL_Option_float){.tag = 0};
    }
    if (start >= len) {
        return (FL_Option_float){.tag = 0};
    }
    fl_float result = 0.0;
    fl_int i = start;
    fl_bool has_digits = fl_false;
    while (i < len) {
        FL_Option_char _fl_tmp_5 = fl_string_char_at(s, i);
        if (_fl_tmp_5.tag == 1) {
            fl_char c = _fl_tmp_5.value;
            if (fl_char_is_digit(c)) {
                fl_int _fl_e_1;
                FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_1);
                fl_float digit = ((fl_float)_fl_e_1);
                result = ((result * 10.0) + digit);
                has_digits = fl_true;
                fl_int _fl_e_2;
                FL_CHECKED_ADD(i, 1, &_fl_e_2);
                i = _fl_e_2;
            } else {
                i = i;
                return fl_conv_parse_float_rest(s, len, i, result, negative, has_digits);
            }
        } else {
            return (FL_Option_float){.tag = 0};
        }
    }
    if (!has_digits) {
        return (FL_Option_float){.tag = 0};
    }
    if (negative) {
        result = (0.0 - result);
    }
    return (FL_Option_float){.tag = 1, .value = result};
}

/* Flow: conv.parse_float_rest */
FL_Option_float fl_conv_parse_float_rest(FL_String* s, fl_int len, fl_int pos, fl_float int_part, fl_bool negative, fl_bool has_digits_before) {
    fl_float result = int_part;
    fl_int i = pos;
    fl_bool has_digits = has_digits_before;
    fl_bool at_dot = fl_false;
    if (i < len) {
        FL_Option_char _fl_tmp_6 = fl_string_char_at(s, i);
        if (_fl_tmp_6.tag == 1) {
            fl_char c = _fl_tmp_6.value;
            if (c == 46) {
                at_dot = fl_true;
                fl_int _fl_e_1;
                FL_CHECKED_ADD(i, 1, &_fl_e_1);
                i = _fl_e_1;
            }
        }
    }
    if (at_dot) {
        fl_float frac = 0.0;
        fl_float frac_div = 1.0;
        while (i < len) {
            FL_Option_char _fl_tmp_7 = fl_string_char_at(s, i);
            if (_fl_tmp_7.tag == 1) {
                fl_char c = _fl_tmp_7.value;
                if (fl_char_is_digit(c)) {
                    fl_int _fl_e_2;
                    FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_2);
                    fl_float digit = ((fl_float)_fl_e_2);
                    frac = ((frac * 10.0) + digit);
                    frac_div = (frac_div * 10.0);
                    has_digits = fl_true;
                    fl_int _fl_e_3;
                    FL_CHECKED_ADD(i, 1, &_fl_e_3);
                    i = _fl_e_3;
                } else {
                    return fl_conv_parse_float_exp(s, len, i, (result + (frac / frac_div)), negative, has_digits);
                }
            } else {
                return (FL_Option_float){.tag = 0};
            }
        }
        result = (result + (frac / frac_div));
    }
    if (!has_digits) {
        return (FL_Option_float){.tag = 0};
    }
    if (i < len) {
        return fl_conv_parse_float_exp(s, len, i, result, negative, has_digits);
    }
    if (negative) {
        result = (0.0 - result);
    }
    return (FL_Option_float){.tag = 1, .value = result};
}

/* Flow: conv.parse_float_exp */
FL_Option_float fl_conv_parse_float_exp(FL_String* s, fl_int len, fl_int pos, fl_float mantissa, fl_bool negative, fl_bool has_digits) {
    fl_int i = pos;
    if (!has_digits) {
        return (FL_Option_float){.tag = 0};
    }
    fl_bool at_exp = fl_false;
    if (i < len) {
        FL_Option_char _fl_tmp_8 = fl_string_char_at(s, i);
        if (_fl_tmp_8.tag == 1) {
            fl_char c = _fl_tmp_8.value;
            if ((c == 101) || (c == 69)) {
                at_exp = fl_true;
                fl_int _fl_e_1;
                FL_CHECKED_ADD(i, 1, &_fl_e_1);
                i = _fl_e_1;
            }
        }
    }
    fl_float result = mantissa;
    if (at_exp) {
        fl_bool exp_neg = fl_false;
        if (i < len) {
            FL_Option_char _fl_tmp_9 = fl_string_char_at(s, i);
            if (_fl_tmp_9.tag == 1) {
                fl_char c = _fl_tmp_9.value;
                if (c == 45) {
                    exp_neg = fl_true;
                    fl_int _fl_e_2;
                    FL_CHECKED_ADD(i, 1, &_fl_e_2);
                    i = _fl_e_2;
                } else {
                    if (c == 43) {
                        fl_int _fl_e_3;
                        FL_CHECKED_ADD(i, 1, &_fl_e_3);
                        i = _fl_e_3;
                    }
                }
            }
        }
        fl_int exp_val = 0;
        fl_bool exp_digits = fl_false;
        while (i < len) {
            FL_Option_char _fl_tmp_10 = fl_string_char_at(s, i);
            if (_fl_tmp_10.tag == 1) {
                fl_char c = _fl_tmp_10.value;
                if (fl_char_is_digit(c)) {
                    fl_int _fl_e_5;
                    FL_CHECKED_MUL(exp_val, 10, &_fl_e_5);
                    fl_int _fl_e_6;
                    FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_6);
                    fl_int _fl_e_4;
                    FL_CHECKED_ADD(_fl_e_5, _fl_e_6, &_fl_e_4);
                    exp_val = _fl_e_4;
                    exp_digits = fl_true;
                } else {
                    return (FL_Option_float){.tag = 0};
                }
            } else {
                return (FL_Option_float){.tag = 0};
            }
            fl_int _fl_e_7;
            FL_CHECKED_ADD(i, 1, &_fl_e_7);
            i = _fl_e_7;
        }
        if (!exp_digits) {
            return (FL_Option_float){.tag = 0};
        }
        fl_float multiplier = 1.0;
        fl_int e = 0;
        while (e < exp_val) {
            multiplier = (multiplier * 10.0);
            fl_int _fl_e_8;
            FL_CHECKED_ADD(e, 1, &_fl_e_8);
            e = _fl_e_8;
        }
        if (exp_neg) {
            result = (result / multiplier);
        } else {
            result = (result * multiplier);
        }
    }
    if (i != len) {
        return (FL_Option_float){.tag = 0};
    }
    if (negative) {
        result = (0.0 - result);
    }
    return (FL_Option_float){.tag = 1, .value = result};
}

typedef struct fl_tests_app_healthcheck_CheckStatus_Pass fl_tests_app_healthcheck_CheckStatus_Pass;

typedef struct fl_tests_app_healthcheck_CheckStatus_Fail fl_tests_app_healthcheck_CheckStatus_Fail;

typedef struct fl_tests_app_healthcheck_CheckStatus_Warn fl_tests_app_healthcheck_CheckStatus_Warn;

typedef struct fl_tests_app_healthcheck_CheckStatus fl_tests_app_healthcheck_CheckStatus;

typedef struct _fl_frame_tests_app_healthcheck_mock_server _fl_frame_tests_app_healthcheck_mock_server;

typedef struct _fl_frame_tests_app_healthcheck_result_aggregator _fl_frame_tests_app_healthcheck_result_aggregator;

FL_String* fl_conv_to_string__int(fl_int val);

FL_Option_ptr _fl_next_tests_app_healthcheck_mock_server(FL_Stream* self);

void _fl_free_tests_app_healthcheck_mock_server(FL_Stream* self);

FL_Stream* fl_tests_app_healthcheck_mock_server(FL_Stream* inbox, fl_int port);

fl_int fl_tests_app_healthcheck_parse_http_status(FL_String* response);

fl_tests_app_healthcheck_CheckStatus fl_tests_app_healthcheck_check_url(FL_String* host, fl_int port, FL_String* url_path, fl_int expected, fl_int timeout);

FL_Option_ptr _fl_next_tests_app_healthcheck_result_aggregator(FL_Stream* self);

void _fl_free_tests_app_healthcheck_result_aggregator(FL_Stream* self);

FL_Stream* fl_tests_app_healthcheck_result_aggregator(FL_Stream* inbox);

void fl_tests_app_healthcheck_main(void);

struct fl_tests_app_healthcheck_CheckStatus_Pass {
    fl_int code;
};

struct fl_tests_app_healthcheck_CheckStatus_Fail {
    FL_String* msg;
};

struct fl_tests_app_healthcheck_CheckStatus_Warn {
    fl_int code;
    FL_String* reason;
};

struct fl_tests_app_healthcheck_CheckStatus {
    fl_byte tag;
    fl_tests_app_healthcheck_CheckStatus_Pass Pass;
    fl_tests_app_healthcheck_CheckStatus_Fail Fail;
    fl_tests_app_healthcheck_CheckStatus_Warn Warn;
};

struct _fl_frame_tests_app_healthcheck_mock_server {
    fl_int _state;
    FL_Stream* inbox;
    fl_int port;
    void* listener;
    fl_bool running;
    FL_String* cmd;
    void* client;
    FL_Array* data;
    FL_String* request;
    FL_String* response;
};

struct _fl_frame_tests_app_healthcheck_result_aggregator {
    fl_int _state;
    FL_Stream* inbox;
    fl_int p;
    fl_int f;
    fl_int w;
    fl_bool finished;
    FL_String* s;
    fl_int total;
};

/* Flow: conv.to_string[mono] */
FL_String* fl_conv_to_string__int(fl_int val) {
    return fl_int_to_string(val);
}

/* Flow: tests.app_healthcheck.mock_server::next */
FL_Option_ptr _fl_next_tests_app_healthcheck_mock_server(FL_Stream* self) {
    _fl_frame_tests_app_healthcheck_mock_server* frame = ((_fl_frame_tests_app_healthcheck_mock_server*)self->state);
    switch (frame->_state) {
        case 0: {
            goto _fl_state_0;
            break;
        }
        case 1: {
            goto _fl_state_1;
            break;
        }
        case 2: {
            goto _fl_state_2;
            break;
        }
        default: {
            goto _fl_stream_done;
            break;
        }
    }
_fl_state_0:;
    FL_Option_ptr _fl_tmp_0 = fl_net_listen(fl_string_from_cstr("127.0.0.1"), frame->port);
    if (_fl_tmp_0.tag == 1) {
        frame->listener = _fl_tmp_0.value;
        frame->_state = 1;
        return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)fl_string_from_cstr("ready")))};
_fl_state_1:;
        fl_net_set_timeout(frame->listener, 200);
        frame->running = fl_true;
        while (frame->running) {
            while (1) {
                FL_Option_ptr _fl_tmp_1 = fl_stream_next(frame->inbox);
                if (_fl_tmp_1.tag == 0) {
                    break;
                }
                frame->cmd = ((FL_String*)_fl_tmp_1.value);
                if (fl_string_eq(frame->cmd, fl_string_from_cstr("stop"))) {
                    frame->running = fl_false;
                }
            }
            if (!frame->running) {
                break;
            }
            FL_Option_ptr _fl_tmp_2 = fl_net_accept(frame->listener);
            if (_fl_tmp_2.tag == 1) {
                frame->client = _fl_tmp_2.value;
                FL_Option_ptr _fl_tmp_3 = fl_net_read(frame->client, 4096);
                if (_fl_tmp_3.tag == 1) {
                    frame->data = _fl_tmp_3.value;
                    frame->request = fl_string_from_bytes(frame->data);
                    frame->response = fl_string_from_cstr("HTTP/1.0 404 Not Found\r\n\r\nnot found");
                    if (fl_string_contains(frame->request, fl_string_from_cstr("GET /api/health"))) {
                        frame->response = fl_string_from_cstr("HTTP/1.0 200 OK\r\n\r\nok");
                    } else {
                        if (fl_string_contains(frame->request, fl_string_from_cstr("GET /api/users"))) {
                            frame->response = fl_string_from_cstr("HTTP/1.0 200 OK\r\n\r\n[users]");
                        }
                    }
                    fl_net_write_string(frame->client, frame->response);
                }
                fl_net_close(frame->client);
            }
        }
        fl_net_close(frame->listener);
    } else {
        frame->_state = 2;
        return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)fl_string_from_cstr("failed")))};
_fl_state_2:;
    }
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.app_healthcheck.mock_server::free */
void _fl_free_tests_app_healthcheck_mock_server(FL_Stream* self) {
    _fl_frame_tests_app_healthcheck_mock_server* frame = ((_fl_frame_tests_app_healthcheck_mock_server*)self->state);
    free(frame);
}

/* Flow: tests.app_healthcheck.mock_server */
FL_Stream* fl_tests_app_healthcheck_mock_server(FL_Stream* inbox, fl_int port) {
    _fl_frame_tests_app_healthcheck_mock_server* frame = ((_fl_frame_tests_app_healthcheck_mock_server*)malloc(sizeof(_fl_frame_tests_app_healthcheck_mock_server)));
    frame->_state = 0;
    frame->inbox = inbox;
    frame->port = port;
    return fl_stream_new(_fl_next_tests_app_healthcheck_mock_server, _fl_free_tests_app_healthcheck_mock_server, ((void*)frame));
}

/* Flow: tests.app_healthcheck.parse_http_status */
fl_int fl_tests_app_healthcheck_parse_http_status(FL_String* response) {
    FL_Option_int _fl_tmp_4 = fl_string_index_of(response, fl_string_from_cstr(" "));
    if (_fl_tmp_4.tag == 1) {
        fl_int sp1 = _fl_tmp_4.value;
        fl_int _fl_e_1;
        FL_CHECKED_ADD(sp1, 1, &_fl_e_1);
        FL_String* after = fl_string_substring(response, _fl_e_1, fl_string_len(response));
        FL_Option_int _fl_tmp_5 = fl_string_index_of(after, fl_string_from_cstr(" "));
        if (_fl_tmp_5.tag == 1) {
            fl_int sp2 = _fl_tmp_5.value;
            FL_Option_int _fl_tmp_6 = fl_conv_string_to_int(fl_string_substring(after, 0, sp2));
            return ((_fl_tmp_6.tag == 1) ? _fl_tmp_6.value : 0);
        }
        FL_Option_int _fl_tmp_7 = fl_conv_string_to_int(after);
        return ((_fl_tmp_7.tag == 1) ? _fl_tmp_7.value : 0);
    }
    return 0;
}

/* Flow: tests.app_healthcheck.check_url */
fl_tests_app_healthcheck_CheckStatus fl_tests_app_healthcheck_check_url(FL_String* host, fl_int port, FL_String* url_path, fl_int expected, fl_int timeout) {
    FL_Option_ptr conn = fl_net_connect(host, port);
    FL_Option_ptr _fl_tmp_8 = conn;
    if (_fl_tmp_8.tag == 1) {
        void* sock = _fl_tmp_8.value;
        fl_net_set_timeout(sock, timeout);
        FL_String* req = fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("GET "), url_path), fl_string_from_cstr(" HTTP/1.0\r\nHost: ")), host), fl_string_from_cstr("\r\n\r\n"));
        fl_bool wrote = fl_net_write_string(sock, req);
        if (!wrote) {
            fl_net_close(sock);
            _fl_throw(((void*)fl_string_from_cstr("write failed")), 0);
        }
        FL_Option_ptr response = fl_net_read(sock, 4096);
        FL_Option_ptr _fl_tmp_9 = response;
        if (_fl_tmp_9.tag == 1) {
            FL_Array* data = _fl_tmp_9.value;
            fl_net_close(sock);
            FL_String* resp = fl_string_from_bytes(data);
            fl_int status_code = fl_tests_app_healthcheck_parse_http_status(resp);
            if (status_code == expected) {
                return (fl_tests_app_healthcheck_CheckStatus){.tag = 0, .Pass = (fl_tests_app_healthcheck_CheckStatus_Pass){.code = status_code}};
            }
            return (fl_tests_app_healthcheck_CheckStatus){.tag = 2, .Warn = (fl_tests_app_healthcheck_CheckStatus_Warn){.code = status_code, .reason = fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("expected "), fl_conv_to_string__int(expected)), fl_string_from_cstr(" got ")), fl_conv_to_string__int(status_code))}};
        }
        fl_net_close(sock);
        _fl_throw(((void*)fl_string_from_cstr("timeout")), 0);
    }
    _fl_throw(((void*)fl_string_from_cstr("connection failed")), 0);
}

/* Flow: tests.app_healthcheck.result_aggregator::next */
FL_Option_ptr _fl_next_tests_app_healthcheck_result_aggregator(FL_Stream* self) {
    _fl_frame_tests_app_healthcheck_result_aggregator* frame = ((_fl_frame_tests_app_healthcheck_result_aggregator*)self->state);
    switch (frame->_state) {
        case 0: {
            goto _fl_state_0;
            break;
        }
        case 1: {
            goto _fl_state_1;
            break;
        }
        default: {
            goto _fl_stream_done;
            break;
        }
    }
_fl_state_0:;
    frame->p = 0;
    frame->f = 0;
    frame->w = 0;
    frame->finished = fl_false;
    while (!frame->finished) {
        while (1) {
            FL_Option_ptr _fl_tmp_10 = fl_stream_next(frame->inbox);
            if (_fl_tmp_10.tag == 0) {
                break;
            }
            frame->s = ((FL_String*)_fl_tmp_10.value);
            if (fl_string_eq(frame->s, fl_string_from_cstr("done"))) {
                frame->finished = fl_true;
            } else {
                if (fl_string_eq(frame->s, fl_string_from_cstr("pass"))) {
                    fl_int _fl_e_1;
                    FL_CHECKED_ADD(frame->p, 1, &_fl_e_1);
                    frame->p = _fl_e_1;
                } else {
                    if (fl_string_eq(frame->s, fl_string_from_cstr("fail"))) {
                        fl_int _fl_e_2;
                        FL_CHECKED_ADD(frame->f, 1, &_fl_e_2);
                        frame->f = _fl_e_2;
                    } else {
                        if (fl_string_eq(frame->s, fl_string_from_cstr("warn"))) {
                            fl_int _fl_e_3;
                            FL_CHECKED_ADD(frame->w, 1, &_fl_e_3);
                            frame->w = _fl_e_3;
                        }
                    }
                }
            }
        }
        if (!frame->finished) {
            fl_time_sleep_ms(5);
        }
    }
    fl_int _fl_e_5;
    FL_CHECKED_ADD(frame->p, frame->f, &_fl_e_5);
    fl_int _fl_e_4;
    FL_CHECKED_ADD(_fl_e_5, frame->w, &_fl_e_4);
    frame->total = _fl_e_4;
    frame->_state = 1;
    return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_conv_to_string__int(frame->p), fl_string_from_cstr(":")), fl_conv_to_string__int(frame->f)), fl_string_from_cstr(":")), fl_conv_to_string__int(frame->w)), fl_string_from_cstr(":")), fl_conv_to_string__int(frame->total))))};
_fl_state_1:;
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.app_healthcheck.result_aggregator::free */
void _fl_free_tests_app_healthcheck_result_aggregator(FL_Stream* self) {
    _fl_frame_tests_app_healthcheck_result_aggregator* frame = ((_fl_frame_tests_app_healthcheck_result_aggregator*)self->state);
    free(frame);
}

/* Flow: tests.app_healthcheck.result_aggregator */
FL_Stream* fl_tests_app_healthcheck_result_aggregator(FL_Stream* inbox) {
    _fl_frame_tests_app_healthcheck_result_aggregator* frame = ((_fl_frame_tests_app_healthcheck_result_aggregator*)malloc(sizeof(_fl_frame_tests_app_healthcheck_result_aggregator)));
    frame->_state = 0;
    frame->inbox = inbox;
    return fl_stream_new(_fl_next_tests_app_healthcheck_result_aggregator, _fl_free_tests_app_healthcheck_result_aggregator, ((void*)frame));
}

/* Flow: tests.app_healthcheck.main */
void fl_tests_app_healthcheck_main(void) {
    fl_int port = 39876;
    FL_Channel* _fl_tmp_11 = fl_channel_new(64);
    FL_Stream* _fl_tmp_12 = fl_stream_from_channel_nonblocking(_fl_tmp_11);
    FL_Stream* _fl_tmp_13 = fl_tests_app_healthcheck_mock_server(_fl_tmp_12, port);
    FL_Coroutine* _fl_tmp_14 = fl_coroutine_new_threaded(_fl_tmp_13, 64);
    fl_coroutine_set_input(_fl_tmp_14, _fl_tmp_11);
    FL_Coroutine* server = _fl_tmp_14;
    FL_Option_ptr _fl_tmp_15 = fl_coroutine_next(server);
    if (_fl_tmp_15.tag == 1) {
        FL_String* status = _fl_tmp_15.value;
        if (!fl_string_eq(status, fl_string_from_cstr("ready"))) {
            fl_println(fl_string_from_cstr("[HC] Server failed to start"));
            return;
        }
    } else {
        fl_println(fl_string_from_cstr("[HC] Server failed to start"));
        return;
    }
    fl_time_sleep_ms(50);
    fl_println(fl_string_from_cstr("[HC] Starting health check for 5 targets..."));
    FL_Channel* _fl_tmp_16 = fl_channel_new(64);
    FL_Stream* _fl_tmp_17 = fl_stream_from_channel_nonblocking(_fl_tmp_16);
    FL_Stream* _fl_tmp_18 = fl_tests_app_healthcheck_result_aggregator(_fl_tmp_17);
    FL_Coroutine* _fl_tmp_19 = fl_coroutine_new_threaded(_fl_tmp_18, 64);
    fl_coroutine_set_input(_fl_tmp_19, _fl_tmp_16);
    FL_Coroutine* agg = _fl_tmp_19;
    FL_Array* urls = fl_array_new(0, 0, NULL);
    urls = fl_array_push_ptr(urls, fl_string_concat(fl_string_concat(fl_string_from_cstr("127.0.0.1|"), fl_conv_to_string__int(port)), fl_string_from_cstr("|/api/health|200")));
    urls = fl_array_push_ptr(urls, fl_string_concat(fl_string_concat(fl_string_from_cstr("127.0.0.1|"), fl_conv_to_string__int(port)), fl_string_from_cstr("|/api/users|200")));
    urls = fl_array_push_ptr(urls, fl_string_concat(fl_string_concat(fl_string_from_cstr("127.0.0.1|"), fl_conv_to_string__int(port)), fl_string_from_cstr("|/api/nothing|200")));
    urls = fl_array_push_ptr(urls, fl_string_concat(fl_string_concat(fl_string_from_cstr("127.0.0.1|"), fl_conv_to_string__int(port)), fl_string_from_cstr("|/api/nothing|404")));
    fl_int _fl_e_1;
    FL_CHECKED_ADD(port, 1, &_fl_e_1);
    urls = fl_array_push_ptr(urls, fl_string_concat(fl_string_concat(fl_string_from_cstr("127.0.0.1|"), fl_conv_to_string__int(_fl_e_1)), fl_string_from_cstr("|/fail|200")));
    fl_int idx = 0;
    while (idx < 5) {
        FL_Option_ptr _fl_tmp_20 = fl_array_get_safe(urls, idx);
        FL_String* target_str = ((_fl_tmp_20.tag == 1) ? _fl_tmp_20.value : fl_string_from_cstr(""));
        FL_Array* parts = fl_string_split(target_str, fl_string_from_cstr("|"));
        FL_Option_ptr _fl_tmp_21 = fl_array_get_safe(parts, 0);
        FL_String* host = ((_fl_tmp_21.tag == 1) ? _fl_tmp_21.value : fl_string_from_cstr("127.0.0.1"));
        FL_Option_ptr _fl_tmp_22 = fl_array_get_safe(parts, 1);
        FL_Option_int _fl_tmp_23 = fl_conv_string_to_int(((_fl_tmp_22.tag == 1) ? _fl_tmp_22.value : fl_string_from_cstr("0")));
        fl_int tport = ((_fl_tmp_23.tag == 1) ? _fl_tmp_23.value : 0);
        FL_Option_ptr _fl_tmp_24 = fl_array_get_safe(parts, 2);
        FL_String* url_path = ((_fl_tmp_24.tag == 1) ? _fl_tmp_24.value : fl_string_from_cstr("/"));
        FL_Option_ptr _fl_tmp_25 = fl_array_get_safe(parts, 3);
        FL_Option_int _fl_tmp_26 = fl_conv_string_to_int(((_fl_tmp_25.tag == 1) ? _fl_tmp_25.value : fl_string_from_cstr("200")));
        fl_int expected = ((_fl_tmp_26.tag == 1) ? _fl_tmp_26.value : 200);
        fl_println(fl_string_concat(fl_string_from_cstr("[HC] Checking: "), url_path));
        FL_ExceptionFrame _fl_ef_0;
        _fl_exception_push((&_fl_ef_0));
        if (setjmp(_fl_ef_0.jmp) == 0) {
            fl_tests_app_healthcheck_CheckStatus status = fl_tests_app_healthcheck_check_url(host, tport, url_path, expected, 2000);
            fl_tests_app_healthcheck_CheckStatus _fl_tmp_27 = status;
            switch (_fl_tmp_27.tag) {
                case 0: {
                    fl_int code = _fl_tmp_27.Pass.code;
                    fl_println(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("[HC] OK: "), url_path), fl_string_from_cstr(" (")), fl_conv_to_string__int(code)), fl_string_from_cstr(")")));
                    fl_coroutine_send(agg, ((void*)fl_string_from_cstr("pass")));
                    break;
                }
                case 2: {
                    fl_int code = _fl_tmp_27.Warn.code;
                    FL_String* reason = _fl_tmp_27.Warn.reason;
                    fl_println(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("[HC] WARN: "), url_path), fl_string_from_cstr(" (")), fl_conv_to_string__int(code)), fl_string_from_cstr(" - ")), reason), fl_string_from_cstr(")")));
                    fl_coroutine_send(agg, ((void*)fl_string_from_cstr("warn")));
                    break;
                }
                case 1: {
                    FL_String* msg = _fl_tmp_27.Fail.msg;
                    fl_println(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("[HC] FAIL: "), url_path), fl_string_from_cstr(" (")), msg), fl_string_from_cstr(")")));
                    fl_coroutine_send(agg, ((void*)fl_string_from_cstr("fail")));
                    break;
                }
            }
            _fl_exception_pop();
        } else {
            _fl_exception_pop();
            if (_fl_ef_0.exception_tag == 0) {
                fl_int _fl_tmp_28 = 0;
                FL_String* ex = ((FL_String*)_fl_ef_0.exception);
                while (_fl_tmp_28 < 2) {
                    _fl_tmp_28 = (_fl_tmp_28 + 1);
                    fl_println(fl_string_concat(fl_string_concat(fl_string_from_cstr("[HC] RETRY: "), ex), fl_string_from_cstr(", retrying...")));
                    _fl_exception_push((&_fl_ef_0));
                    if (setjmp(_fl_ef_0.jmp) == 0) {
                        fl_tests_app_healthcheck_CheckStatus status = fl_tests_app_healthcheck_check_url(host, tport, url_path, expected, 2000);
                        fl_tests_app_healthcheck_CheckStatus _fl_tmp_30 = status;
                        switch (_fl_tmp_30.tag) {
                            case 0: {
                                fl_int code = _fl_tmp_30.Pass.code;
                                fl_println(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("[HC] OK: "), url_path), fl_string_from_cstr(" (")), fl_conv_to_string__int(code)), fl_string_from_cstr(")")));
                                fl_coroutine_send(agg, ((void*)fl_string_from_cstr("pass")));
                                break;
                            }
                            case 2: {
                                fl_int code = _fl_tmp_30.Warn.code;
                                FL_String* reason = _fl_tmp_30.Warn.reason;
                                fl_println(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("[HC] WARN: "), url_path), fl_string_from_cstr(" (")), fl_conv_to_string__int(code)), fl_string_from_cstr(" - ")), reason), fl_string_from_cstr(")")));
                                fl_coroutine_send(agg, ((void*)fl_string_from_cstr("warn")));
                                break;
                            }
                            case 1: {
                                FL_String* msg = _fl_tmp_30.Fail.msg;
                                fl_println(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("[HC] FAIL: "), url_path), fl_string_from_cstr(" (")), msg), fl_string_from_cstr(")")));
                                fl_coroutine_send(agg, ((void*)fl_string_from_cstr("fail")));
                                break;
                            }
                        }
                        _fl_exception_pop();
                        goto _fl_tmp_29;
                    } else {
                        _fl_exception_pop();
                        ex = ((FL_String*)_fl_ef_0.exception);
                    }
                }
                fl_println(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("[HC] FAIL: "), url_path), fl_string_from_cstr(" (")), ex), fl_string_from_cstr(" after retries)")));
                fl_coroutine_send(agg, ((void*)fl_string_from_cstr("fail")));
_fl_tmp_29:;
            } else {
                _fl_throw(_fl_ef_0.exception, _fl_ef_0.exception_tag);
            }
        }
        fl_int _fl_e_2;
        FL_CHECKED_ADD(idx, 1, &_fl_e_2);
        idx = _fl_e_2;
    }
    fl_coroutine_send(agg, ((void*)fl_string_from_cstr("done")));
    FL_Option_ptr _fl_tmp_31 = fl_coroutine_next(agg);
    if (_fl_tmp_31.tag == 1) {
        FL_String* report_str = _fl_tmp_31.value;
        FL_Array* rparts = fl_string_split(report_str, fl_string_from_cstr(":"));
        fl_println(fl_string_from_cstr("[HC] --- Report ---"));
        FL_Option_ptr _fl_tmp_32 = fl_array_get_safe(rparts, 0);
        fl_println(fl_string_concat(fl_string_from_cstr("[HC] Passed: "), ((_fl_tmp_32.tag == 1) ? _fl_tmp_32.value : fl_string_from_cstr("0"))));
        FL_Option_ptr _fl_tmp_33 = fl_array_get_safe(rparts, 1);
        fl_println(fl_string_concat(fl_string_from_cstr("[HC] Failed: "), ((_fl_tmp_33.tag == 1) ? _fl_tmp_33.value : fl_string_from_cstr("0"))));
        FL_Option_ptr _fl_tmp_34 = fl_array_get_safe(rparts, 2);
        fl_println(fl_string_concat(fl_string_from_cstr("[HC] Warnings: "), ((_fl_tmp_34.tag == 1) ? _fl_tmp_34.value : fl_string_from_cstr("0"))));
        FL_Option_ptr _fl_tmp_35 = fl_array_get_safe(rparts, 3);
        fl_println(fl_string_concat(fl_string_from_cstr("[HC] Total: "), ((_fl_tmp_35.tag == 1) ? _fl_tmp_35.value : fl_string_from_cstr("0"))));
    } else {
        fl_println(fl_string_from_cstr("[HC] No report available"));
    }
    fl_coroutine_send(server, ((void*)fl_string_from_cstr("stop")));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_app_healthcheck_main();
    return 0;
}
