/* Generated by flowc - do not edit */
/* Source: tests/programs/app_csv_to_json.flow */
#include "flow_runtime.h"

/* From: stdlib/char.flow */

fl_bool fl_char_is_digit(fl_char c);

fl_bool fl_char_is_alpha(fl_char c);

fl_bool fl_char_is_alphanumeric(fl_char c);

fl_bool fl_char_is_whitespace(fl_char c);

fl_int fl_char_to_code(fl_char c);

fl_char fl_char_from_code(fl_int n);

FL_String* fl_char_to_string(fl_char c);

/* Flow: char.is_digit */
fl_bool fl_char_is_digit(fl_char c) {
    return ((c >= 48) && (c <= 57));
}

/* Flow: char.is_alpha */
fl_bool fl_char_is_alpha(fl_char c) {
    return ((((c >= 97) && (c <= 122)) || ((c >= 65) && (c <= 90))) || (c == 95));
}

/* Flow: char.is_alphanumeric */
fl_bool fl_char_is_alphanumeric(fl_char c) {
    return (fl_char_is_alpha(c) || fl_char_is_digit(c));
}

/* Flow: char.is_whitespace */
fl_bool fl_char_is_whitespace(fl_char c) {
    return ((((c == 32) || (c == 9)) || (c == 10)) || (c == 13));
}

/* Flow: char.to_code */
fl_int fl_char_to_code(fl_char c) {
    return ((fl_int)c);
}

/* Flow: char.from_code */
fl_char fl_char_from_code(fl_int n) {
    return ((fl_char)n);
}

/* Flow: char.to_string */
FL_String* fl_char_to_string(fl_char c) {
    fl_int code = fl_char_to_code(c);
    if (code < 128) {
        void* buf = fl_mem_alloc(((fl_int64)1));
        fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)code));
        return fl_mem_to_string(buf, ((fl_int64)1));
    } else {
        if (code < 2048) {
            void* buf = fl_mem_alloc(((fl_int64)2));
            fl_int _fl_e_2;
            FL_CHECKED_DIV(code, 64, &_fl_e_2);
            fl_int _fl_e_1;
            FL_CHECKED_ADD(192, _fl_e_2, &_fl_e_1);
            fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)_fl_e_1));
            fl_int _fl_e_4;
            FL_CHECKED_MOD(code, 64, &_fl_e_4);
            fl_int _fl_e_3;
            FL_CHECKED_ADD(128, _fl_e_4, &_fl_e_3);
            fl_mem_write_byte(buf, ((fl_int64)1), ((fl_byte)_fl_e_3));
            return fl_mem_to_string(buf, ((fl_int64)2));
        } else {
            if (code < 65536) {
                void* buf = fl_mem_alloc(((fl_int64)3));
                fl_int _fl_e_6;
                FL_CHECKED_DIV(code, 4096, &_fl_e_6);
                fl_int _fl_e_5;
                FL_CHECKED_ADD(224, _fl_e_6, &_fl_e_5);
                fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)_fl_e_5));
                fl_int _fl_e_9;
                FL_CHECKED_DIV(code, 64, &_fl_e_9);
                fl_int _fl_e_8;
                FL_CHECKED_MOD(_fl_e_9, 64, &_fl_e_8);
                fl_int _fl_e_7;
                FL_CHECKED_ADD(128, _fl_e_8, &_fl_e_7);
                fl_mem_write_byte(buf, ((fl_int64)1), ((fl_byte)_fl_e_7));
                fl_int _fl_e_11;
                FL_CHECKED_MOD(code, 64, &_fl_e_11);
                fl_int _fl_e_10;
                FL_CHECKED_ADD(128, _fl_e_11, &_fl_e_10);
                fl_mem_write_byte(buf, ((fl_int64)2), ((fl_byte)_fl_e_10));
                return fl_mem_to_string(buf, ((fl_int64)3));
            } else {
                void* buf = fl_mem_alloc(((fl_int64)4));
                fl_int _fl_e_13;
                FL_CHECKED_DIV(code, 262144, &_fl_e_13);
                fl_int _fl_e_12;
                FL_CHECKED_ADD(240, _fl_e_13, &_fl_e_12);
                fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)_fl_e_12));
                fl_int _fl_e_16;
                FL_CHECKED_DIV(code, 4096, &_fl_e_16);
                fl_int _fl_e_15;
                FL_CHECKED_MOD(_fl_e_16, 64, &_fl_e_15);
                fl_int _fl_e_14;
                FL_CHECKED_ADD(128, _fl_e_15, &_fl_e_14);
                fl_mem_write_byte(buf, ((fl_int64)1), ((fl_byte)_fl_e_14));
                fl_int _fl_e_19;
                FL_CHECKED_DIV(code, 64, &_fl_e_19);
                fl_int _fl_e_18;
                FL_CHECKED_MOD(_fl_e_19, 64, &_fl_e_18);
                fl_int _fl_e_17;
                FL_CHECKED_ADD(128, _fl_e_18, &_fl_e_17);
                fl_mem_write_byte(buf, ((fl_int64)2), ((fl_byte)_fl_e_17));
                fl_int _fl_e_21;
                FL_CHECKED_MOD(code, 64, &_fl_e_21);
                fl_int _fl_e_20;
                FL_CHECKED_ADD(128, _fl_e_21, &_fl_e_20);
                fl_mem_write_byte(buf, ((fl_int64)3), ((fl_byte)_fl_e_20));
                return fl_mem_to_string(buf, ((fl_int64)4));
            }
        }
    }
}

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/conv.flow */

FL_String* fl_conv_char_to_string(fl_char c);

FL_Option_int fl_conv_string_to_int(FL_String* s);

FL_Option_int64 fl_conv_string_to_int64(FL_String* s);

FL_Option_float fl_conv_string_to_float(FL_String* s);

FL_Option_float fl_conv_parse_float_rest(FL_String* s, fl_int len, fl_int pos, fl_float int_part, fl_bool negative, fl_bool has_digits_before);

FL_Option_float fl_conv_parse_float_exp(FL_String* s, fl_int len, fl_int pos, fl_float mantissa, fl_bool negative, fl_bool has_digits);

/* Flow: conv.char_to_string */
FL_String* fl_conv_char_to_string(fl_char c) {
    return fl_char_to_string(c);
}

/* Flow: conv.string_to_int */
FL_Option_int fl_conv_string_to_int(FL_String* s) {
    fl_int len = fl_string_len(s);
    if (len == 0) {
        return (FL_Option_int){.tag = 0};
    }
    fl_int start = 0;
    fl_bool negative = fl_false;
    FL_Option_char _fl_tmp_0 = fl_string_char_at(s, 0);
    if (_fl_tmp_0.tag == 1) {
        fl_char c = _fl_tmp_0.value;
        if (c == 45) {
            negative = fl_true;
            start = 1;
        } else {
            if (c == 43) {
                start = 1;
            }
        }
    } else {
        return (FL_Option_int){.tag = 0};
    }
    if (start >= len) {
        return (FL_Option_int){.tag = 0};
    }
    fl_int result = 0;
    fl_int i = start;
    while (i < len) {
        FL_Option_char _fl_tmp_1 = fl_string_char_at(s, i);
        if (_fl_tmp_1.tag == 1) {
            fl_char c = _fl_tmp_1.value;
            if (!fl_char_is_digit(c)) {
                return (FL_Option_int){.tag = 0};
            }
            fl_int _fl_e_1;
            FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_1);
            fl_int digit = _fl_e_1;
            fl_int _fl_e_3;
            FL_CHECKED_MUL(result, 10, &_fl_e_3);
            fl_int _fl_e_2;
            FL_CHECKED_ADD(_fl_e_3, digit, &_fl_e_2);
            result = _fl_e_2;
        } else {
            return (FL_Option_int){.tag = 0};
        }
        fl_int _fl_e_4;
        FL_CHECKED_ADD(i, 1, &_fl_e_4);
        i = _fl_e_4;
    }
    if (negative) {
        fl_int _fl_e_5;
        FL_CHECKED_SUB(0, result, &_fl_e_5);
        result = _fl_e_5;
    }
    return (FL_Option_int){.tag = 1, .value = result};
}

/* Flow: conv.string_to_int64 */
FL_Option_int64 fl_conv_string_to_int64(FL_String* s) {
    fl_int len = fl_string_len(s);
    if (len == 0) {
        return (FL_Option_int64){.tag = 0};
    }
    fl_int start = 0;
    fl_bool negative = fl_false;
    FL_Option_char _fl_tmp_2 = fl_string_char_at(s, 0);
    if (_fl_tmp_2.tag == 1) {
        fl_char c = _fl_tmp_2.value;
        if (c == 45) {
            negative = fl_true;
            start = 1;
        } else {
            if (c == 43) {
                start = 1;
            }
        }
    } else {
        return (FL_Option_int64){.tag = 0};
    }
    if (start >= len) {
        return (FL_Option_int64){.tag = 0};
    }
    fl_int64 result = ((fl_int64)0);
    fl_int i = start;
    while (i < len) {
        FL_Option_char _fl_tmp_3 = fl_string_char_at(s, i);
        if (_fl_tmp_3.tag == 1) {
            fl_char c = _fl_tmp_3.value;
            if (!fl_char_is_digit(c)) {
                return (FL_Option_int64){.tag = 0};
            }
            fl_int _fl_e_1;
            FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_1);
            fl_int64 digit = ((fl_int64)_fl_e_1);
            fl_int64 _fl_e_3;
            FL_CHECKED_MUL(result, ((fl_int64)10), &_fl_e_3);
            fl_int64 _fl_e_2;
            FL_CHECKED_ADD(_fl_e_3, digit, &_fl_e_2);
            result = _fl_e_2;
        } else {
            return (FL_Option_int64){.tag = 0};
        }
        fl_int _fl_e_4;
        FL_CHECKED_ADD(i, 1, &_fl_e_4);
        i = _fl_e_4;
    }
    if (negative) {
        fl_int64 _fl_e_5;
        FL_CHECKED_SUB(((fl_int64)0), result, &_fl_e_5);
        result = _fl_e_5;
    }
    return (FL_Option_int64){.tag = 1, .value = result};
}

/* Flow: conv.string_to_float */
FL_Option_float fl_conv_string_to_float(FL_String* s) {
    fl_int len = fl_string_len(s);
    if (len == 0) {
        return (FL_Option_float){.tag = 0};
    }
    fl_int start = 0;
    fl_bool negative = fl_false;
    FL_Option_char _fl_tmp_4 = fl_string_char_at(s, 0);
    if (_fl_tmp_4.tag == 1) {
        fl_char c = _fl_tmp_4.value;
        if (c == 45) {
            negative = fl_true;
            start = 1;
        } else {
            if (c == 43) {
                start = 1;
            }
        }
    } else {
        return (FL_Option_float){.tag = 0};
    }
    if (start >= len) {
        return (FL_Option_float){.tag = 0};
    }
    fl_float result = 0.0;
    fl_int i = start;
    fl_bool has_digits = fl_false;
    while (i < len) {
        FL_Option_char _fl_tmp_5 = fl_string_char_at(s, i);
        if (_fl_tmp_5.tag == 1) {
            fl_char c = _fl_tmp_5.value;
            if (fl_char_is_digit(c)) {
                fl_int _fl_e_1;
                FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_1);
                fl_float digit = ((fl_float)_fl_e_1);
                result = ((result * 10.0) + digit);
                has_digits = fl_true;
                fl_int _fl_e_2;
                FL_CHECKED_ADD(i, 1, &_fl_e_2);
                i = _fl_e_2;
            } else {
                i = i;
                return fl_conv_parse_float_rest(s, len, i, result, negative, has_digits);
            }
        } else {
            return (FL_Option_float){.tag = 0};
        }
    }
    if (!has_digits) {
        return (FL_Option_float){.tag = 0};
    }
    if (negative) {
        result = (0.0 - result);
    }
    return (FL_Option_float){.tag = 1, .value = result};
}

/* Flow: conv.parse_float_rest */
FL_Option_float fl_conv_parse_float_rest(FL_String* s, fl_int len, fl_int pos, fl_float int_part, fl_bool negative, fl_bool has_digits_before) {
    fl_float result = int_part;
    fl_int i = pos;
    fl_bool has_digits = has_digits_before;
    fl_bool at_dot = fl_false;
    if (i < len) {
        FL_Option_char _fl_tmp_6 = fl_string_char_at(s, i);
        if (_fl_tmp_6.tag == 1) {
            fl_char c = _fl_tmp_6.value;
            if (c == 46) {
                at_dot = fl_true;
                fl_int _fl_e_1;
                FL_CHECKED_ADD(i, 1, &_fl_e_1);
                i = _fl_e_1;
            }
        }
    }
    if (at_dot) {
        fl_float frac = 0.0;
        fl_float frac_div = 1.0;
        while (i < len) {
            FL_Option_char _fl_tmp_7 = fl_string_char_at(s, i);
            if (_fl_tmp_7.tag == 1) {
                fl_char c = _fl_tmp_7.value;
                if (fl_char_is_digit(c)) {
                    fl_int _fl_e_2;
                    FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_2);
                    fl_float digit = ((fl_float)_fl_e_2);
                    frac = ((frac * 10.0) + digit);
                    frac_div = (frac_div * 10.0);
                    has_digits = fl_true;
                    fl_int _fl_e_3;
                    FL_CHECKED_ADD(i, 1, &_fl_e_3);
                    i = _fl_e_3;
                } else {
                    return fl_conv_parse_float_exp(s, len, i, (result + (frac / frac_div)), negative, has_digits);
                }
            } else {
                return (FL_Option_float){.tag = 0};
            }
        }
        result = (result + (frac / frac_div));
    }
    if (!has_digits) {
        return (FL_Option_float){.tag = 0};
    }
    if (i < len) {
        return fl_conv_parse_float_exp(s, len, i, result, negative, has_digits);
    }
    if (negative) {
        result = (0.0 - result);
    }
    return (FL_Option_float){.tag = 1, .value = result};
}

/* Flow: conv.parse_float_exp */
FL_Option_float fl_conv_parse_float_exp(FL_String* s, fl_int len, fl_int pos, fl_float mantissa, fl_bool negative, fl_bool has_digits) {
    fl_int i = pos;
    if (!has_digits) {
        return (FL_Option_float){.tag = 0};
    }
    fl_bool at_exp = fl_false;
    if (i < len) {
        FL_Option_char _fl_tmp_8 = fl_string_char_at(s, i);
        if (_fl_tmp_8.tag == 1) {
            fl_char c = _fl_tmp_8.value;
            if ((c == 101) || (c == 69)) {
                at_exp = fl_true;
                fl_int _fl_e_1;
                FL_CHECKED_ADD(i, 1, &_fl_e_1);
                i = _fl_e_1;
            }
        }
    }
    fl_float result = mantissa;
    if (at_exp) {
        fl_bool exp_neg = fl_false;
        if (i < len) {
            FL_Option_char _fl_tmp_9 = fl_string_char_at(s, i);
            if (_fl_tmp_9.tag == 1) {
                fl_char c = _fl_tmp_9.value;
                if (c == 45) {
                    exp_neg = fl_true;
                    fl_int _fl_e_2;
                    FL_CHECKED_ADD(i, 1, &_fl_e_2);
                    i = _fl_e_2;
                } else {
                    if (c == 43) {
                        fl_int _fl_e_3;
                        FL_CHECKED_ADD(i, 1, &_fl_e_3);
                        i = _fl_e_3;
                    }
                }
            }
        }
        fl_int exp_val = 0;
        fl_bool exp_digits = fl_false;
        while (i < len) {
            FL_Option_char _fl_tmp_10 = fl_string_char_at(s, i);
            if (_fl_tmp_10.tag == 1) {
                fl_char c = _fl_tmp_10.value;
                if (fl_char_is_digit(c)) {
                    fl_int _fl_e_5;
                    FL_CHECKED_MUL(exp_val, 10, &_fl_e_5);
                    fl_int _fl_e_6;
                    FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_6);
                    fl_int _fl_e_4;
                    FL_CHECKED_ADD(_fl_e_5, _fl_e_6, &_fl_e_4);
                    exp_val = _fl_e_4;
                    exp_digits = fl_true;
                } else {
                    return (FL_Option_float){.tag = 0};
                }
            } else {
                return (FL_Option_float){.tag = 0};
            }
            fl_int _fl_e_7;
            FL_CHECKED_ADD(i, 1, &_fl_e_7);
            i = _fl_e_7;
        }
        if (!exp_digits) {
            return (FL_Option_float){.tag = 0};
        }
        fl_float multiplier = 1.0;
        fl_int e = 0;
        while (e < exp_val) {
            multiplier = (multiplier * 10.0);
            fl_int _fl_e_8;
            FL_CHECKED_ADD(e, 1, &_fl_e_8);
            e = _fl_e_8;
        }
        if (exp_neg) {
            result = (result / multiplier);
        } else {
            result = (result * multiplier);
        }
    }
    if (i != len) {
        return (FL_Option_float){.tag = 0};
    }
    if (negative) {
        result = (0.0 - result);
    }
    return (FL_Option_float){.tag = 1, .value = result};
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

/* From: stdlib/string_builder.flow */

typedef struct fl_string_builder_StringBuilder fl_string_builder_StringBuilder;

FL_String* fl_conv_to_string__int(fl_int val);

fl_int64 fl_string_builder_get_len(fl_string_builder_StringBuilder sb);

void fl_string_builder_set_len(fl_string_builder_StringBuilder sb, fl_int64 len);

fl_int64 fl_string_builder_get_cap(fl_string_builder_StringBuilder sb);

void fl_string_builder_set_cap(fl_string_builder_StringBuilder sb, fl_int64 cap);

void* fl_string_builder_get_data(fl_string_builder_StringBuilder sb);

void fl_string_builder_set_data(fl_string_builder_StringBuilder sb, void* data);

void fl_string_builder_grow(fl_string_builder_StringBuilder sb, fl_int64 needed);

fl_string_builder_StringBuilder fl_string_builder_new(void);

fl_string_builder_StringBuilder fl_string_builder_with_capacity(fl_int64 cap);

void fl_string_builder_append(fl_string_builder_StringBuilder sb, FL_String* s);

void fl_string_builder_append_char(fl_string_builder_StringBuilder sb, fl_char c);

void fl_string_builder_append_int(fl_string_builder_StringBuilder sb, fl_int v);

void fl_string_builder_append_int64(fl_string_builder_StringBuilder sb, fl_int64 v);

void fl_string_builder_append_float(fl_string_builder_StringBuilder sb, fl_float v);

FL_String* fl_string_builder_build(fl_string_builder_StringBuilder sb);

fl_int64 fl_string_builder_len(fl_string_builder_StringBuilder sb);

void fl_string_builder_clear(fl_string_builder_StringBuilder sb);

struct fl_string_builder_StringBuilder {
    void* handle;
};

/* Flow: conv.to_string[mono] */
FL_String* fl_conv_to_string__int(fl_int val) {
    return fl_int_to_string(val);
}

/* Flow: string_builder.get_len */
fl_int64 fl_string_builder_get_len(fl_string_builder_StringBuilder sb) {
    return fl_mem_read_int64(sb.handle, ((fl_int64)0));
}

/* Flow: string_builder.set_len */
void fl_string_builder_set_len(fl_string_builder_StringBuilder sb, fl_int64 len) {
    fl_mem_write_int64(sb.handle, ((fl_int64)0), len);
}

/* Flow: string_builder.get_cap */
fl_int64 fl_string_builder_get_cap(fl_string_builder_StringBuilder sb) {
    return fl_mem_read_int64(sb.handle, ((fl_int64)8));
}

/* Flow: string_builder.set_cap */
void fl_string_builder_set_cap(fl_string_builder_StringBuilder sb, fl_int64 cap) {
    fl_mem_write_int64(sb.handle, ((fl_int64)8), cap);
}

/* Flow: string_builder.get_data */
void* fl_string_builder_get_data(fl_string_builder_StringBuilder sb) {
    return fl_mem_read_ptr(sb.handle, ((fl_int64)16));
}

/* Flow: string_builder.set_data */
void fl_string_builder_set_data(fl_string_builder_StringBuilder sb, void* data) {
    fl_mem_write_ptr(sb.handle, ((fl_int64)16), data);
}

/* Flow: string_builder.grow */
void fl_string_builder_grow(fl_string_builder_StringBuilder sb, fl_int64 needed) {
    fl_int64 cur_len = fl_string_builder_get_len(sb);
    fl_int64 cur_cap = fl_string_builder_get_cap(sb);
    fl_int64 _fl_e_1;
    FL_CHECKED_ADD(cur_len, needed, &_fl_e_1);
    fl_int64 required = _fl_e_1;
    if (required <= cur_cap) {
        return;
    }
    fl_int64 new_cap = cur_cap;
    while (new_cap < required) {
        if (new_cap < 64) {
            new_cap = 64;
        } else {
            fl_int64 _fl_e_2;
            FL_CHECKED_MUL(new_cap, ((fl_int64)2), &_fl_e_2);
            new_cap = _fl_e_2;
        }
    }
    void* old_data = fl_string_builder_get_data(sb);
    if (fl_ptr_is_null(old_data)) {
        void* new_data = fl_mem_alloc(new_cap);
        fl_string_builder_set_data(sb, new_data);
    } else {
        void* new_data = fl_mem_realloc(old_data, new_cap);
        fl_string_builder_set_data(sb, new_data);
    }
    fl_string_builder_set_cap(sb, new_cap);
}

/* Flow: string_builder.new */
fl_string_builder_StringBuilder fl_string_builder_new(void) {
    void* handle = fl_mem_alloc(((fl_int64)24));
    fl_mem_write_int64(handle, ((fl_int64)0), ((fl_int64)0));
    fl_mem_write_int64(handle, ((fl_int64)8), ((fl_int64)0));
    fl_mem_write_ptr(handle, ((fl_int64)16), fl_ptr_null());
    return (fl_string_builder_StringBuilder){.handle = handle};
}

/* Flow: string_builder.with_capacity */
fl_string_builder_StringBuilder fl_string_builder_with_capacity(fl_int64 cap) {
    fl_string_builder_StringBuilder sb = fl_string_builder_new();
    if (cap > 0) {
        void* data = fl_mem_alloc(cap);
        fl_string_builder_set_data(sb, data);
        fl_string_builder_set_cap(sb, cap);
    }
    return sb;
}

/* Flow: string_builder.append */
void fl_string_builder_append(fl_string_builder_StringBuilder sb, FL_String* s) {
    fl_int64 slen = ((fl_int64)fl_string_len(s));
    if (slen == 0) {
        return;
    }
    fl_string_builder_grow(sb, slen);
    void* data = fl_string_builder_get_data(sb);
    fl_int64 cur_len = fl_string_builder_get_len(sb);
    fl_mem_copy_str(data, cur_len, s);
    fl_int64 _fl_e_1;
    FL_CHECKED_ADD(cur_len, slen, &_fl_e_1);
    fl_string_builder_set_len(sb, _fl_e_1);
}

/* Flow: string_builder.append_char */
void fl_string_builder_append_char(fl_string_builder_StringBuilder sb, fl_char c) {
    fl_int code = fl_char_to_code(c);
    if (code < 128) {
        fl_string_builder_grow(sb, ((fl_int64)1));
        void* data = fl_string_builder_get_data(sb);
        fl_int64 cur_len = fl_string_builder_get_len(sb);
        fl_mem_write_byte(data, cur_len, ((fl_byte)code));
        fl_int64 _fl_e_1;
        FL_CHECKED_ADD(cur_len, ((fl_int64)1), &_fl_e_1);
        fl_string_builder_set_len(sb, _fl_e_1);
    } else {
        if (code < 2048) {
            fl_string_builder_grow(sb, ((fl_int64)2));
            void* data = fl_string_builder_get_data(sb);
            fl_int64 cur_len = fl_string_builder_get_len(sb);
            fl_int _fl_e_3;
            FL_CHECKED_DIV(code, 64, &_fl_e_3);
            fl_int _fl_e_2;
            FL_CHECKED_ADD(192, _fl_e_3, &_fl_e_2);
            fl_mem_write_byte(data, cur_len, ((fl_byte)_fl_e_2));
            fl_int64 _fl_e_4;
            FL_CHECKED_ADD(cur_len, ((fl_int64)1), &_fl_e_4);
            fl_int _fl_e_6;
            FL_CHECKED_MOD(code, 64, &_fl_e_6);
            fl_int _fl_e_5;
            FL_CHECKED_ADD(128, _fl_e_6, &_fl_e_5);
            fl_mem_write_byte(data, _fl_e_4, ((fl_byte)_fl_e_5));
            fl_int64 _fl_e_7;
            FL_CHECKED_ADD(cur_len, ((fl_int64)2), &_fl_e_7);
            fl_string_builder_set_len(sb, _fl_e_7);
        } else {
            if (code < 65536) {
                fl_string_builder_grow(sb, ((fl_int64)3));
                void* data = fl_string_builder_get_data(sb);
                fl_int64 cur_len = fl_string_builder_get_len(sb);
                fl_int _fl_e_9;
                FL_CHECKED_DIV(code, 4096, &_fl_e_9);
                fl_int _fl_e_8;
                FL_CHECKED_ADD(224, _fl_e_9, &_fl_e_8);
                fl_mem_write_byte(data, cur_len, ((fl_byte)_fl_e_8));
                fl_int64 _fl_e_10;
                FL_CHECKED_ADD(cur_len, ((fl_int64)1), &_fl_e_10);
                fl_int _fl_e_13;
                FL_CHECKED_DIV(code, 64, &_fl_e_13);
                fl_int _fl_e_12;
                FL_CHECKED_MOD(_fl_e_13, 64, &_fl_e_12);
                fl_int _fl_e_11;
                FL_CHECKED_ADD(128, _fl_e_12, &_fl_e_11);
                fl_mem_write_byte(data, _fl_e_10, ((fl_byte)_fl_e_11));
                fl_int64 _fl_e_14;
                FL_CHECKED_ADD(cur_len, ((fl_int64)2), &_fl_e_14);
                fl_int _fl_e_16;
                FL_CHECKED_MOD(code, 64, &_fl_e_16);
                fl_int _fl_e_15;
                FL_CHECKED_ADD(128, _fl_e_16, &_fl_e_15);
                fl_mem_write_byte(data, _fl_e_14, ((fl_byte)_fl_e_15));
                fl_int64 _fl_e_17;
                FL_CHECKED_ADD(cur_len, ((fl_int64)3), &_fl_e_17);
                fl_string_builder_set_len(sb, _fl_e_17);
            } else {
                fl_string_builder_grow(sb, ((fl_int64)4));
                void* data = fl_string_builder_get_data(sb);
                fl_int64 cur_len = fl_string_builder_get_len(sb);
                fl_int _fl_e_19;
                FL_CHECKED_DIV(code, 262144, &_fl_e_19);
                fl_int _fl_e_18;
                FL_CHECKED_ADD(240, _fl_e_19, &_fl_e_18);
                fl_mem_write_byte(data, cur_len, ((fl_byte)_fl_e_18));
                fl_int64 _fl_e_20;
                FL_CHECKED_ADD(cur_len, ((fl_int64)1), &_fl_e_20);
                fl_int _fl_e_23;
                FL_CHECKED_DIV(code, 4096, &_fl_e_23);
                fl_int _fl_e_22;
                FL_CHECKED_MOD(_fl_e_23, 64, &_fl_e_22);
                fl_int _fl_e_21;
                FL_CHECKED_ADD(128, _fl_e_22, &_fl_e_21);
                fl_mem_write_byte(data, _fl_e_20, ((fl_byte)_fl_e_21));
                fl_int64 _fl_e_24;
                FL_CHECKED_ADD(cur_len, ((fl_int64)2), &_fl_e_24);
                fl_int _fl_e_27;
                FL_CHECKED_DIV(code, 64, &_fl_e_27);
                fl_int _fl_e_26;
                FL_CHECKED_MOD(_fl_e_27, 64, &_fl_e_26);
                fl_int _fl_e_25;
                FL_CHECKED_ADD(128, _fl_e_26, &_fl_e_25);
                fl_mem_write_byte(data, _fl_e_24, ((fl_byte)_fl_e_25));
                fl_int64 _fl_e_28;
                FL_CHECKED_ADD(cur_len, ((fl_int64)3), &_fl_e_28);
                fl_int _fl_e_30;
                FL_CHECKED_MOD(code, 64, &_fl_e_30);
                fl_int _fl_e_29;
                FL_CHECKED_ADD(128, _fl_e_30, &_fl_e_29);
                fl_mem_write_byte(data, _fl_e_28, ((fl_byte)_fl_e_29));
                fl_int64 _fl_e_31;
                FL_CHECKED_ADD(cur_len, ((fl_int64)4), &_fl_e_31);
                fl_string_builder_set_len(sb, _fl_e_31);
            }
        }
    }
}

/* Flow: string_builder.append_int */
void fl_string_builder_append_int(fl_string_builder_StringBuilder sb, fl_int v) {
    fl_string_builder_append(sb, fl_conv_to_string__int(v));
}

/* Flow: string_builder.append_int64 */
void fl_string_builder_append_int64(fl_string_builder_StringBuilder sb, fl_int64 v) {
    fl_string_builder_append(sb, fl_int64_to_string(v));
}

/* Flow: string_builder.append_float */
void fl_string_builder_append_float(fl_string_builder_StringBuilder sb, fl_float v) {
    fl_string_builder_append(sb, fl_float_to_string(v));
}

/* Flow: string_builder.build */
FL_String* fl_string_builder_build(fl_string_builder_StringBuilder sb) {
    fl_int64 cur_len = fl_string_builder_get_len(sb);
    if (cur_len == 0) {
        return fl_string_from_cstr("");
    }
    void* data = fl_string_builder_get_data(sb);
    return fl_mem_to_string(data, cur_len);
}

/* Flow: string_builder.len */
fl_int64 fl_string_builder_len(fl_string_builder_StringBuilder sb) {
    return fl_string_builder_get_len(sb);
}

/* Flow: string_builder.clear */
void fl_string_builder_clear(fl_string_builder_StringBuilder sb) {
    fl_string_builder_set_len(sb, ((fl_int64)0));
}

typedef struct fl_tests_app_csv_to_json_Schema fl_tests_app_csv_to_json_Schema;

typedef struct fl_tests_app_csv_to_json_CsvRow fl_tests_app_csv_to_json_CsvRow;

fl_tests_app_csv_to_json_CsvRow fl_tests_app_csv_to_json_parse_row(fl_int idx, FL_String* line);

fl_bool fl_tests_app_csv_to_json_is_required(FL_String* name, FL_Array* required);

fl_tests_app_csv_to_json_CsvRow fl_tests_app_csv_to_json_validate(fl_tests_app_csv_to_json_CsvRow row, fl_tests_app_csv_to_json_Schema schema);

FL_String* fl_tests_app_csv_to_json_escape_json(FL_String* s);

FL_String* fl_tests_app_csv_to_json_to_json(fl_tests_app_csv_to_json_CsvRow row, fl_tests_app_csv_to_json_Schema schema);

FL_String* fl_tests_app_csv_to_json_sanitize(FL_String* line);

void fl_tests_app_csv_to_json_main(void);

struct fl_tests_app_csv_to_json_Schema {
    FL_Array* columns;
    FL_Array* required;
};

struct fl_tests_app_csv_to_json_CsvRow {
    fl_int index;
    FL_Array* fields;
};

/* Flow: tests.app_csv_to_json.parse_row */
fl_tests_app_csv_to_json_CsvRow fl_tests_app_csv_to_json_parse_row(fl_int idx, FL_String* line) {
    FL_Array* fields = fl_string_split(line, fl_string_from_cstr(","));
    return (fl_tests_app_csv_to_json_CsvRow){.index = idx, .fields = fields};
}

/* Flow: tests.app_csv_to_json.is_required */
fl_bool fl_tests_app_csv_to_json_is_required(FL_String* name, FL_Array* required) {
    fl_int64 _fl_tmp_0 = 0;
    while (_fl_tmp_0 < fl_array_len(required)) {
        FL_String* r = (*((FL_String**)fl_array_get_ptr(required, _fl_tmp_0)));
        if (fl_string_eq(r, name)) {
            return fl_true;
        }
        _fl_tmp_0 = (_fl_tmp_0 + 1);
    }
    return fl_false;
}

/* Flow: tests.app_csv_to_json.validate */
fl_tests_app_csv_to_json_CsvRow fl_tests_app_csv_to_json_validate(fl_tests_app_csv_to_json_CsvRow row, fl_tests_app_csv_to_json_Schema schema) {
    FL_Array* cols = schema.columns;
    fl_int i = 0;
    while (i < fl_array_len_int(cols)) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(cols, i);
        FL_String* col_name = ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr(""));
        if (fl_tests_app_csv_to_json_is_required(col_name, schema.required)) {
            FL_Option_ptr _fl_tmp_2 = fl_array_get_safe(row.fields, i);
            FL_String* field_val = ((_fl_tmp_2.tag == 1) ? _fl_tmp_2.value : fl_string_from_cstr(""));
            if (fl_string_len(field_val) == 0) {
                _fl_throw(((void*)fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("missing required field '"), col_name), fl_string_from_cstr("' at row ")), fl_conv_to_string__int(row.index))), 0);
            }
        }
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return row;
}

/* Flow: tests.app_csv_to_json.escape_json */
FL_String* fl_tests_app_csv_to_json_escape_json(FL_String* s) {
    FL_String* r1 = fl_string_replace(s, fl_string_from_cstr("\\"), fl_string_from_cstr("\\\\"));
    FL_String* r2 = fl_string_replace(r1, fl_string_from_cstr("\""), fl_string_from_cstr("\\\""));
    return r2;
}

/* Flow: tests.app_csv_to_json.to_json */
FL_String* fl_tests_app_csv_to_json_to_json(fl_tests_app_csv_to_json_CsvRow row, fl_tests_app_csv_to_json_Schema schema) {
    FL_Array* cols = schema.columns;
    fl_string_builder_StringBuilder b = fl_string_builder_new();
    fl_string_builder_append(b, fl_string_from_cstr("{"));
    fl_int i = 0;
    while (i < fl_array_len_int(cols)) {
        if (i > 0) {
            fl_string_builder_append(b, fl_string_from_cstr(","));
        }
        FL_Option_ptr _fl_tmp_3 = fl_array_get_safe(cols, i);
        FL_String* col_name = ((_fl_tmp_3.tag == 1) ? _fl_tmp_3.value : fl_string_from_cstr(""));
        FL_Option_ptr _fl_tmp_4 = fl_array_get_safe(row.fields, i);
        FL_String* field_val = ((_fl_tmp_4.tag == 1) ? _fl_tmp_4.value : fl_string_from_cstr(""));
        fl_string_builder_append(b, fl_string_from_cstr("\""));
        fl_string_builder_append(b, fl_tests_app_csv_to_json_escape_json(col_name));
        fl_string_builder_append(b, fl_string_from_cstr("\":"));
        if (fl_string_len(field_val) > 0) {
            fl_string_builder_append(b, fl_string_from_cstr("\""));
            fl_string_builder_append(b, fl_tests_app_csv_to_json_escape_json(field_val));
            fl_string_builder_append(b, fl_string_from_cstr("\""));
        } else {
            fl_string_builder_append(b, fl_string_from_cstr("null"));
        }
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    fl_string_builder_append(b, fl_string_from_cstr("}"));
    return fl_string_builder_build(b);
}

/* Flow: tests.app_csv_to_json.sanitize */
FL_String* fl_tests_app_csv_to_json_sanitize(FL_String* line) {
    FL_String* cleaned = fl_string_replace(line, fl_string_from_cstr("\""), fl_string_from_cstr(""));
    return fl_string_trim(cleaned);
}

/* Flow: tests.app_csv_to_json.main */
void fl_tests_app_csv_to_json_main(void) {
    FL_Array* lines = fl_array_new(5, sizeof(FL_String*), (FL_String*[]){fl_string_from_cstr("name,age,city"), fl_string_from_cstr("Alice,30,NYC"), fl_string_from_cstr("Bob,,London"), fl_string_from_cstr(",bad,data"), fl_string_from_cstr("Charlie,25,Paris")});
    fl_tests_app_csv_to_json_Schema schema = (fl_tests_app_csv_to_json_Schema){.columns = fl_array_new(3, sizeof(FL_String*), (FL_String*[]){fl_string_from_cstr("name"), fl_string_from_cstr("age"), fl_string_from_cstr("city")}), .required = fl_array_new(1, sizeof(FL_String*), (FL_String*[]){fl_string_from_cstr("name")})};
    fl_int i = 1;
    while (i < fl_array_len_int(lines)) {
        FL_Option_ptr _fl_tmp_5 = fl_array_get_safe(lines, i);
        FL_String* line = ((_fl_tmp_5.tag == 1) ? _fl_tmp_5.value : fl_string_from_cstr(""));
        FL_ExceptionFrame _fl_ef_0;
        _fl_exception_push((&_fl_ef_0));
        if (setjmp(_fl_ef_0.jmp) == 0) {
            fl_tests_app_csv_to_json_CsvRow row = fl_tests_app_csv_to_json_parse_row(i, line);
            fl_tests_app_csv_to_json_CsvRow validated = fl_tests_app_csv_to_json_validate(row, schema);
            FL_String* json_str = fl_tests_app_csv_to_json_to_json(validated, schema);
            fl_println(json_str);
            _fl_exception_pop();
        } else {
            _fl_exception_pop();
            if (_fl_ef_0.exception_tag == 0) {
                FL_String* e = ((FL_String*)_fl_ef_0.exception);
                FL_ExceptionFrame _fl_ef_1;
                _fl_exception_push((&_fl_ef_1));
                if (setjmp(_fl_ef_1.jmp) == 0) {
                    FL_String* fixed = fl_tests_app_csv_to_json_sanitize(line);
                    fl_tests_app_csv_to_json_CsvRow row = fl_tests_app_csv_to_json_parse_row(i, fixed);
                    fl_tests_app_csv_to_json_CsvRow validated = fl_tests_app_csv_to_json_validate(row, schema);
                    FL_String* json_str = fl_tests_app_csv_to_json_to_json(validated, schema);
                    fl_println(json_str);
                    _fl_exception_pop();
                } else {
                    _fl_exception_pop();
                    if (_fl_ef_1.exception_tag == 0) {
                        FL_String* e2 = ((FL_String*)_fl_ef_1.exception);
                        fl_println(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("SKIP row "), fl_conv_to_string__int(i)), fl_string_from_cstr(": ")), e2));
                    } else {
                        _fl_throw(_fl_ef_1.exception, _fl_ef_1.exception_tag);
                    }
                }
            } else {
                _fl_throw(_fl_ef_0.exception, _fl_ef_0.exception_tag);
            }
        }
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_app_csv_to_json_main();
    return 0;
}
