/* Generated by reflowc - do not edit */
/* Source: tests/programs/app_chat_parse.reflow */
#include "reflow_runtime.h"

typedef struct RF_Tuple_RF_String_ptr_RF_String_ptr RF_Tuple_RF_String_ptr_RF_String_ptr;

RF_Tuple_RF_String_ptr_RF_String_ptr rf_tests_app_chat_parse_parse_message(RF_String* raw);

RF_Option_ptr rf_tests_app_chat_parse_validate_nick(RF_String* name);

void rf_tests_app_chat_parse_test_parse(RF_String* input, RF_String* expected_cmd, RF_String* expected_arg);

void rf_tests_app_chat_parse_test_nick(RF_String* input, rf_bool expect_ok);

void rf_tests_app_chat_parse_main(void);

struct RF_Tuple_RF_String_ptr_RF_String_ptr {
    RF_String* _0;
    RF_String* _1;
};

/* ReFlow: tests.app_chat_parse.parse_message */
RF_Tuple_RF_String_ptr_RF_String_ptr rf_tests_app_chat_parse_parse_message(RF_String* raw) {
    RF_String* trimmed = rf_string_trim(raw);
    if (rf_string_len(trimmed) == 0) {
        return (RF_Tuple_RF_String_ptr_RF_String_ptr){._0 = rf_string_from_cstr("/empty"), ._1 = rf_string_from_cstr("")};
    }
    if (rf_string_starts_with(trimmed, rf_string_from_cstr("/"))) {
        RF_Option_int _rf_tmp_0 = rf_string_index_of(trimmed, rf_string_from_cstr(" "));
        if (_rf_tmp_0.tag == 1) {
            rf_int idx = _rf_tmp_0.value;
            RF_String* cmd = rf_string_substring(trimmed, 0, idx);
            rf_int _rf_e_1;
            RF_CHECKED_ADD(idx, 1, &_rf_e_1);
            RF_String* arg = rf_string_trim(rf_string_substring(trimmed, _rf_e_1, rf_string_len(trimmed)));
            return (RF_Tuple_RF_String_ptr_RF_String_ptr){._0 = cmd, ._1 = arg};
        } else {
            return (RF_Tuple_RF_String_ptr_RF_String_ptr){._0 = trimmed, ._1 = rf_string_from_cstr("")};
        }
    }
    return (RF_Tuple_RF_String_ptr_RF_String_ptr){._0 = rf_string_from_cstr("/say"), ._1 = trimmed};
}

/* ReFlow: tests.app_chat_parse.validate_nick */
RF_Option_ptr rf_tests_app_chat_parse_validate_nick(RF_String* name) {
    if (rf_string_len(name) == 0) {
        return (RF_Option_ptr){.tag = 1, .value = rf_string_from_cstr("Nickname cannot be empty.")};
    }
    if (rf_string_len(name) > 20) {
        return (RF_Option_ptr){.tag = 1, .value = rf_string_from_cstr("Nickname too long (max 20 chars).")};
    }
    if (rf_string_contains(name, rf_string_from_cstr(" "))) {
        return (RF_Option_ptr){.tag = 1, .value = rf_string_from_cstr("Nickname cannot contain spaces.")};
    }
    return (RF_Option_ptr){.tag = 0};
}

/* ReFlow: tests.app_chat_parse.test_parse */
void rf_tests_app_chat_parse_test_parse(RF_String* input, RF_String* expected_cmd, RF_String* expected_arg) {
    RF_Tuple_RF_String_ptr_RF_String_ptr result = rf_tests_app_chat_parse_parse_message(input);
    if (rf_string_eq(result._0, expected_cmd) && rf_string_eq(result._1, expected_arg)) {
        rf_println(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_from_cstr("PASS: \""), input), rf_string_from_cstr("\" -> (")), result._0), rf_string_from_cstr(", ")), result._1), rf_string_from_cstr(")")));
    } else {
        rf_println(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_from_cstr("FAIL: \""), input), rf_string_from_cstr("\" expected (")), expected_cmd), rf_string_from_cstr(", ")), expected_arg), rf_string_from_cstr(") got (")), result._0), rf_string_from_cstr(", ")), result._1), rf_string_from_cstr(")")));
    }
}

/* ReFlow: tests.app_chat_parse.test_nick */
void rf_tests_app_chat_parse_test_nick(RF_String* input, rf_bool expect_ok) {
    RF_Option_ptr _rf_tmp_1 = rf_tests_app_chat_parse_validate_nick(input);
    if (_rf_tmp_1.tag == 1) {
        RF_String* reason = _rf_tmp_1.value;
        if (!expect_ok) {
            rf_println(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_from_cstr("PASS: validate_nick(\""), input), rf_string_from_cstr("\") -> error: ")), reason));
        } else {
            rf_println(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_from_cstr("FAIL: validate_nick(\""), input), rf_string_from_cstr("\") expected ok, got: ")), reason));
        }
    } else {
        if (expect_ok) {
            rf_println(rf_string_concat(rf_string_concat(rf_string_from_cstr("PASS: validate_nick(\""), input), rf_string_from_cstr("\") -> ok")));
        } else {
            rf_println(rf_string_concat(rf_string_concat(rf_string_from_cstr("FAIL: validate_nick(\""), input), rf_string_from_cstr("\") expected error, got ok")));
        }
    }
}

/* ReFlow: tests.app_chat_parse.main */
void rf_tests_app_chat_parse_main(void) {
    rf_println(rf_string_from_cstr("=== parse_message tests ==="));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("hello"), rf_string_from_cstr("/say"), rf_string_from_cstr("hello"));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("hello world"), rf_string_from_cstr("/say"), rf_string_from_cstr("hello world"));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("/help"), rf_string_from_cstr("/help"), rf_string_from_cstr(""));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("/quit"), rf_string_from_cstr("/quit"), rf_string_from_cstr(""));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("/nick bob"), rf_string_from_cstr("/nick"), rf_string_from_cstr("bob"));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("/nick  alice "), rf_string_from_cstr("/nick"), rf_string_from_cstr("alice"));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("/say hi there"), rf_string_from_cstr("/say"), rf_string_from_cstr("hi there"));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr(""), rf_string_from_cstr("/empty"), rf_string_from_cstr(""));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("  "), rf_string_from_cstr("/empty"), rf_string_from_cstr(""));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("/"), rf_string_from_cstr("/"), rf_string_from_cstr(""));
    rf_tests_app_chat_parse_test_parse(rf_string_from_cstr("/ "), rf_string_from_cstr("/"), rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== validate_nick tests ==="));
    rf_tests_app_chat_parse_test_nick(rf_string_from_cstr("alice"), rf_true);
    rf_tests_app_chat_parse_test_nick(rf_string_from_cstr("bob123"), rf_true);
    rf_tests_app_chat_parse_test_nick(rf_string_from_cstr("a"), rf_true);
    rf_tests_app_chat_parse_test_nick(rf_string_from_cstr("twelve_chars_ok!"), rf_true);
    rf_tests_app_chat_parse_test_nick(rf_string_from_cstr(""), rf_false);
    rf_tests_app_chat_parse_test_nick(rf_string_from_cstr("has space"), rf_false);
    rf_tests_app_chat_parse_test_nick(rf_string_from_cstr("this_name_is_way_too_long_for_a_nickname"), rf_false);
    rf_println(rf_string_from_cstr("done"));
}

/* Entry point */
int main(int argc, char** argv) {
    _rf_runtime_init(argc, argv);
    rf_tests_app_chat_parse_main();
    return 0;
}
