/* Generated by reflowc - do not edit */
/* Source: tests/programs/app_log_pipeline.reflow */
#include "reflow_runtime.h"

typedef struct rf_tests_app_log_pipeline_Severity rf_tests_app_log_pipeline_Severity;

typedef struct rf_tests_app_log_pipeline_LogEntry rf_tests_app_log_pipeline_LogEntry;

rf_tests_app_log_pipeline_Severity rf_tests_app_log_pipeline_make_severity(RF_String* name);

rf_tests_app_log_pipeline_LogEntry rf_tests_app_log_pipeline_parse_kv_log(RF_String* line);

rf_tests_app_log_pipeline_LogEntry rf_tests_app_log_pipeline_parse_csv_log(RF_String* line);

rf_tests_app_log_pipeline_LogEntry rf_tests_app_log_pipeline_parse_simple_log(RF_String* line);

rf_tests_app_log_pipeline_LogEntry rf_tests_app_log_pipeline_detect_and_parse(RF_String* line);

RF_String* rf_tests_app_log_pipeline_write_archive(rf_tests_app_log_pipeline_LogEntry entry);

RF_String* rf_tests_app_log_pipeline_update_stats(rf_tests_app_log_pipeline_LogEntry entry);

RF_String* rf_tests_app_log_pipeline_combine_output(RF_String* archived, RF_String* stats);

void rf_tests_app_log_pipeline_main(void);

struct rf_tests_app_log_pipeline_Severity {
    rf_int level;
    RF_String* name;
};

struct rf_tests_app_log_pipeline_LogEntry {
    RF_String* timestamp;
    rf_tests_app_log_pipeline_Severity severity;
    RF_String* source;
    RF_String* message;
};

/* ReFlow: tests.app_log_pipeline.make_severity */
rf_tests_app_log_pipeline_Severity rf_tests_app_log_pipeline_make_severity(RF_String* name) {
    if (rf_string_eq(name, rf_string_from_cstr("ERROR"))) {
        return (rf_tests_app_log_pipeline_Severity){.level = 0, .name = rf_string_from_cstr("ERROR")};
    }
    if (rf_string_eq(name, rf_string_from_cstr("WARN"))) {
        return (rf_tests_app_log_pipeline_Severity){.level = 1, .name = rf_string_from_cstr("WARN")};
    }
    if (rf_string_eq(name, rf_string_from_cstr("INFO"))) {
        return (rf_tests_app_log_pipeline_Severity){.level = 2, .name = rf_string_from_cstr("INFO")};
    }
    return (rf_tests_app_log_pipeline_Severity){.level = 3, .name = rf_string_from_cstr("DEBUG")};
}

/* ReFlow: tests.app_log_pipeline.parse_kv_log */
rf_tests_app_log_pipeline_LogEntry rf_tests_app_log_pipeline_parse_kv_log(RF_String* line) {
    RF_Array* parts = rf_string_split(line, rf_string_from_cstr(" "));
    RF_Option_ptr _rf_tmp_0 = rf_array_get_safe(parts, 0);
    RF_String* ts = rf_string_replace(((_rf_tmp_0.tag == 1) ? _rf_tmp_0.value : rf_string_from_cstr("")), rf_string_from_cstr("ts="), rf_string_from_cstr(""));
    RF_Option_ptr _rf_tmp_1 = rf_array_get_safe(parts, 1);
    RF_String* level = rf_string_replace(((_rf_tmp_1.tag == 1) ? _rf_tmp_1.value : rf_string_from_cstr("")), rf_string_from_cstr("level="), rf_string_from_cstr(""));
    RF_Option_ptr _rf_tmp_2 = rf_array_get_safe(parts, 2);
    RF_String* src = rf_string_replace(((_rf_tmp_2.tag == 1) ? _rf_tmp_2.value : rf_string_from_cstr("")), rf_string_from_cstr("src="), rf_string_from_cstr(""));
    RF_Option_ptr _rf_tmp_3 = rf_array_get_safe(parts, 3);
    RF_String* msg = rf_string_replace(((_rf_tmp_3.tag == 1) ? _rf_tmp_3.value : rf_string_from_cstr("")), rf_string_from_cstr("msg="), rf_string_from_cstr(""));
    return (rf_tests_app_log_pipeline_LogEntry){.timestamp = ts, .severity = rf_tests_app_log_pipeline_make_severity(level), .source = src, .message = msg};
}

/* ReFlow: tests.app_log_pipeline.parse_csv_log */
rf_tests_app_log_pipeline_LogEntry rf_tests_app_log_pipeline_parse_csv_log(RF_String* line) {
    RF_Array* parts = rf_string_split(line, rf_string_from_cstr(","));
    RF_Option_ptr _rf_tmp_4 = rf_array_get_safe(parts, 0);
    RF_Option_ptr _rf_tmp_5 = rf_array_get_safe(parts, 1);
    RF_Option_ptr _rf_tmp_6 = rf_array_get_safe(parts, 2);
    RF_Option_ptr _rf_tmp_7 = rf_array_get_safe(parts, 3);
    return (rf_tests_app_log_pipeline_LogEntry){.timestamp = ((_rf_tmp_4.tag == 1) ? _rf_tmp_4.value : rf_string_from_cstr("")), .severity = rf_tests_app_log_pipeline_make_severity(((_rf_tmp_5.tag == 1) ? _rf_tmp_5.value : rf_string_from_cstr(""))), .source = ((_rf_tmp_6.tag == 1) ? _rf_tmp_6.value : rf_string_from_cstr("")), .message = ((_rf_tmp_7.tag == 1) ? _rf_tmp_7.value : rf_string_from_cstr(""))};
}

/* ReFlow: tests.app_log_pipeline.parse_simple_log */
rf_tests_app_log_pipeline_LogEntry rf_tests_app_log_pipeline_parse_simple_log(RF_String* line) {
    RF_Array* parts = rf_string_split(line, rf_string_from_cstr(" "));
    RF_Option_ptr _rf_tmp_8 = rf_array_get_safe(parts, 0);
    RF_Option_ptr _rf_tmp_9 = rf_array_get_safe(parts, 2);
    RF_Option_ptr _rf_tmp_10 = rf_array_get_safe(parts, 1);
    RF_Option_ptr _rf_tmp_11 = rf_array_get_safe(parts, 3);
    return (rf_tests_app_log_pipeline_LogEntry){.timestamp = ((_rf_tmp_8.tag == 1) ? _rf_tmp_8.value : rf_string_from_cstr("")), .severity = rf_tests_app_log_pipeline_make_severity(((_rf_tmp_9.tag == 1) ? _rf_tmp_9.value : rf_string_from_cstr(""))), .source = ((_rf_tmp_10.tag == 1) ? _rf_tmp_10.value : rf_string_from_cstr("")), .message = ((_rf_tmp_11.tag == 1) ? _rf_tmp_11.value : rf_string_from_cstr(""))};
}

/* ReFlow: tests.app_log_pipeline.detect_and_parse */
rf_tests_app_log_pipeline_LogEntry rf_tests_app_log_pipeline_detect_and_parse(RF_String* line) {
    if (rf_string_starts_with(line, rf_string_from_cstr("ts="))) {
        return rf_tests_app_log_pipeline_parse_kv_log(line);
    }
    if (rf_string_contains(line, rf_string_from_cstr(","))) {
        return rf_tests_app_log_pipeline_parse_csv_log(line);
    }
    return rf_tests_app_log_pipeline_parse_simple_log(line);
}

/* ReFlow: tests.app_log_pipeline.write_archive */
RF_String* rf_tests_app_log_pipeline_write_archive(rf_tests_app_log_pipeline_LogEntry entry) {
    return rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_from_cstr("ARCHIVE: ["), entry.timestamp), rf_string_from_cstr("] ")), entry.source), rf_string_from_cstr(" ")), entry.message);
}

/* ReFlow: tests.app_log_pipeline.update_stats */
RF_String* rf_tests_app_log_pipeline_update_stats(rf_tests_app_log_pipeline_LogEntry entry) {
    return rf_string_concat(rf_string_concat(rf_string_concat(rf_string_from_cstr("STATS: severity="), entry.severity.name), rf_string_from_cstr(" source=")), entry.source);
}

/* ReFlow: tests.app_log_pipeline.combine_output */
RF_String* rf_tests_app_log_pipeline_combine_output(RF_String* archived, RF_String* stats) {
    return rf_string_concat(rf_string_concat(archived, rf_string_from_cstr("\n")), stats);
}

/* ReFlow: tests.app_log_pipeline.main */
void rf_tests_app_log_pipeline_main(void) {
    RF_Array* lines = rf_array_new(5, sizeof(RF_String*), (RF_String*[]){rf_string_from_cstr("ts=2024-01-01 level=ERROR src=api msg=timeout"), rf_string_from_cstr("2024-01-01,INFO,db,connected"), rf_string_from_cstr("2024-01-01 web WARN slow_query"), rf_string_from_cstr("corrupt???"), rf_string_from_cstr("ts=2024-01-02 level=WARN src=api msg=retry")});
    rf_int64 _rf_tmp_12 = 0;
    while (_rf_tmp_12 < rf_array_len(lines)) {
        RF_String* line = (*((RF_String**)rf_array_get_ptr(lines, _rf_tmp_12)));
        RF_ExceptionFrame _rf_ef_0;
        _rf_exception_push((&_rf_ef_0));
        if (setjmp(_rf_ef_0.jmp) == 0) {
            rf_tests_app_log_pipeline_LogEntry entry = rf_tests_app_log_pipeline_detect_and_parse(line);
            if (rf_string_len(entry.timestamp) == 0) {
                _rf_throw(((void*)rf_string_from_cstr("empty timestamp")), 0);
            }
            if (rf_string_len(entry.source) == 0) {
                _rf_throw(((void*)rf_string_from_cstr("empty source")), 0);
            }
            rf_tests_app_log_pipeline_LogEntry _rf_tmp_13 = entry;
            RF_String* _rf_tmp_14 = rf_tests_app_log_pipeline_write_archive(_rf_tmp_13);
            RF_String* _rf_tmp_15 = rf_tests_app_log_pipeline_update_stats(_rf_tmp_13);
            RF_String* output = rf_tests_app_log_pipeline_combine_output(_rf_tmp_14, _rf_tmp_15);
            rf_println(output);
            if (entry.severity.level <= 1) {
                rf_println(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_from_cstr("ALERT: "), entry.severity.name), rf_string_from_cstr(" from ")), entry.source), rf_string_from_cstr(": ")), entry.message));
            }
            _rf_exception_pop();
        } else {
            _rf_exception_pop();
            if (_rf_ef_0.exception_tag == 0) {
                RF_String* e = ((RF_String*)_rf_ef_0.exception);
                rf_println(rf_string_concat(rf_string_from_cstr("SKIP: "), e));
            } else {
                _rf_throw(_rf_ef_0.exception, _rf_ef_0.exception_tag);
            }
        }
        _rf_tmp_12 = (_rf_tmp_12 + 1);
    }
}

/* Entry point */
int main(int argc, char** argv) {
    _rf_runtime_init(argc, argv);
    rf_tests_app_log_pipeline_main();
    return 0;
}
