/* Generated by flowc - do not edit */
/* Source: tests/programs/app_log_pipeline.flow */
#include "flow_runtime.h"

/* From: stdlib/char.flow */

fl_bool fl_char_is_digit(fl_char c);

fl_bool fl_char_is_alpha(fl_char c);

fl_bool fl_char_is_alphanumeric(fl_char c);

fl_bool fl_char_is_whitespace(fl_char c);

fl_int fl_char_to_code(fl_char c);

fl_char fl_char_from_code(fl_int n);

FL_String* fl_char_to_string(fl_char c);

/* Flow: char.is_digit */
fl_bool fl_char_is_digit(fl_char c) {
    return ((c >= 48) && (c <= 57));
}

/* Flow: char.is_alpha */
fl_bool fl_char_is_alpha(fl_char c) {
    return ((((c >= 97) && (c <= 122)) || ((c >= 65) && (c <= 90))) || (c == 95));
}

/* Flow: char.is_alphanumeric */
fl_bool fl_char_is_alphanumeric(fl_char c) {
    return (fl_char_is_alpha(c) || fl_char_is_digit(c));
}

/* Flow: char.is_whitespace */
fl_bool fl_char_is_whitespace(fl_char c) {
    return ((((c == 32) || (c == 9)) || (c == 10)) || (c == 13));
}

/* Flow: char.to_code */
fl_int fl_char_to_code(fl_char c) {
    return ((fl_int)c);
}

/* Flow: char.from_code */
fl_char fl_char_from_code(fl_int n) {
    return ((fl_char)n);
}

/* Flow: char.to_string */
FL_String* fl_char_to_string(fl_char c) {
    fl_int code = fl_char_to_code(c);
    if (code < 128) {
        void* buf = fl_mem_alloc(((fl_int64)1));
        fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)code));
        return fl_mem_to_string(buf, ((fl_int64)1));
    } else {
        if (code < 2048) {
            void* buf = fl_mem_alloc(((fl_int64)2));
            fl_int _fl_e_2;
            FL_CHECKED_DIV(code, 64, &_fl_e_2);
            fl_int _fl_e_1;
            FL_CHECKED_ADD(192, _fl_e_2, &_fl_e_1);
            fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)_fl_e_1));
            fl_int _fl_e_4;
            FL_CHECKED_MOD(code, 64, &_fl_e_4);
            fl_int _fl_e_3;
            FL_CHECKED_ADD(128, _fl_e_4, &_fl_e_3);
            fl_mem_write_byte(buf, ((fl_int64)1), ((fl_byte)_fl_e_3));
            return fl_mem_to_string(buf, ((fl_int64)2));
        } else {
            if (code < 65536) {
                void* buf = fl_mem_alloc(((fl_int64)3));
                fl_int _fl_e_6;
                FL_CHECKED_DIV(code, 4096, &_fl_e_6);
                fl_int _fl_e_5;
                FL_CHECKED_ADD(224, _fl_e_6, &_fl_e_5);
                fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)_fl_e_5));
                fl_int _fl_e_9;
                FL_CHECKED_DIV(code, 64, &_fl_e_9);
                fl_int _fl_e_8;
                FL_CHECKED_MOD(_fl_e_9, 64, &_fl_e_8);
                fl_int _fl_e_7;
                FL_CHECKED_ADD(128, _fl_e_8, &_fl_e_7);
                fl_mem_write_byte(buf, ((fl_int64)1), ((fl_byte)_fl_e_7));
                fl_int _fl_e_11;
                FL_CHECKED_MOD(code, 64, &_fl_e_11);
                fl_int _fl_e_10;
                FL_CHECKED_ADD(128, _fl_e_11, &_fl_e_10);
                fl_mem_write_byte(buf, ((fl_int64)2), ((fl_byte)_fl_e_10));
                return fl_mem_to_string(buf, ((fl_int64)3));
            } else {
                void* buf = fl_mem_alloc(((fl_int64)4));
                fl_int _fl_e_13;
                FL_CHECKED_DIV(code, 262144, &_fl_e_13);
                fl_int _fl_e_12;
                FL_CHECKED_ADD(240, _fl_e_13, &_fl_e_12);
                fl_mem_write_byte(buf, ((fl_int64)0), ((fl_byte)_fl_e_12));
                fl_int _fl_e_16;
                FL_CHECKED_DIV(code, 4096, &_fl_e_16);
                fl_int _fl_e_15;
                FL_CHECKED_MOD(_fl_e_16, 64, &_fl_e_15);
                fl_int _fl_e_14;
                FL_CHECKED_ADD(128, _fl_e_15, &_fl_e_14);
                fl_mem_write_byte(buf, ((fl_int64)1), ((fl_byte)_fl_e_14));
                fl_int _fl_e_19;
                FL_CHECKED_DIV(code, 64, &_fl_e_19);
                fl_int _fl_e_18;
                FL_CHECKED_MOD(_fl_e_19, 64, &_fl_e_18);
                fl_int _fl_e_17;
                FL_CHECKED_ADD(128, _fl_e_18, &_fl_e_17);
                fl_mem_write_byte(buf, ((fl_int64)2), ((fl_byte)_fl_e_17));
                fl_int _fl_e_21;
                FL_CHECKED_MOD(code, 64, &_fl_e_21);
                fl_int _fl_e_20;
                FL_CHECKED_ADD(128, _fl_e_21, &_fl_e_20);
                fl_mem_write_byte(buf, ((fl_int64)3), ((fl_byte)_fl_e_20));
                return fl_mem_to_string(buf, ((fl_int64)4));
            }
        }
    }
}

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_string_release(_fl_tmp_2);
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/conv.flow */

FL_String* fl_conv_char_to_string(fl_char c);

FL_Option_int fl_conv_string_to_int(FL_String* s);

FL_Option_int64 fl_conv_string_to_int64(FL_String* s);

FL_Option_float fl_conv_string_to_float(FL_String* s);

FL_Option_float fl_conv_parse_float_rest(FL_String* s, fl_int len, fl_int pos, fl_float int_part, fl_bool negative, fl_bool has_digits_before);

FL_Option_float fl_conv_parse_float_exp(FL_String* s, fl_int len, fl_int pos, fl_float mantissa, fl_bool negative, fl_bool has_digits);

/* Flow: conv.char_to_string */
FL_String* fl_conv_char_to_string(fl_char c) {
    return fl_char_to_string(c);
}

/* Flow: conv.string_to_int */
FL_Option_int fl_conv_string_to_int(FL_String* s) {
    fl_int len = fl_string_len(s);
    if (len == 0) {
        return (FL_Option_int){.tag = 0};
    }
    fl_int start = 0;
    fl_bool negative = fl_false;
    FL_Option_char _fl_tmp_0 = fl_string_char_at(s, 0);
    if (_fl_tmp_0.tag == 1) {
        fl_char c = _fl_tmp_0.value;
        if (c == 45) {
            negative = fl_true;
            start = 1;
        } else {
            if (c == 43) {
                start = 1;
            }
        }
    } else {
        return (FL_Option_int){.tag = 0};
    }
    if (start >= len) {
        return (FL_Option_int){.tag = 0};
    }
    fl_int result = 0;
    fl_int i = start;
    while (i < len) {
        FL_Option_char _fl_tmp_1 = fl_string_char_at(s, i);
        if (_fl_tmp_1.tag == 1) {
            fl_char c = _fl_tmp_1.value;
            if (!fl_char_is_digit(c)) {
                return (FL_Option_int){.tag = 0};
            }
            fl_int _fl_e_1;
            FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_1);
            fl_int digit = _fl_e_1;
            fl_int _fl_e_3;
            FL_CHECKED_MUL(result, 10, &_fl_e_3);
            fl_int _fl_e_2;
            FL_CHECKED_ADD(_fl_e_3, digit, &_fl_e_2);
            result = _fl_e_2;
        } else {
            return (FL_Option_int){.tag = 0};
        }
        fl_int _fl_e_4;
        FL_CHECKED_ADD(i, 1, &_fl_e_4);
        i = _fl_e_4;
    }
    if (negative) {
        fl_int _fl_e_5;
        FL_CHECKED_SUB(0, result, &_fl_e_5);
        result = _fl_e_5;
    }
    return (FL_Option_int){.tag = 1, .value = result};
}

/* Flow: conv.string_to_int64 */
FL_Option_int64 fl_conv_string_to_int64(FL_String* s) {
    fl_int len = fl_string_len(s);
    if (len == 0) {
        return (FL_Option_int64){.tag = 0};
    }
    fl_int start = 0;
    fl_bool negative = fl_false;
    FL_Option_char _fl_tmp_2 = fl_string_char_at(s, 0);
    if (_fl_tmp_2.tag == 1) {
        fl_char c = _fl_tmp_2.value;
        if (c == 45) {
            negative = fl_true;
            start = 1;
        } else {
            if (c == 43) {
                start = 1;
            }
        }
    } else {
        return (FL_Option_int64){.tag = 0};
    }
    if (start >= len) {
        return (FL_Option_int64){.tag = 0};
    }
    fl_int64 result = ((fl_int64)0);
    fl_int i = start;
    while (i < len) {
        FL_Option_char _fl_tmp_3 = fl_string_char_at(s, i);
        if (_fl_tmp_3.tag == 1) {
            fl_char c = _fl_tmp_3.value;
            if (!fl_char_is_digit(c)) {
                return (FL_Option_int64){.tag = 0};
            }
            fl_int _fl_e_1;
            FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_1);
            fl_int64 digit = ((fl_int64)_fl_e_1);
            fl_int64 _fl_e_3;
            FL_CHECKED_MUL(result, ((fl_int64)10), &_fl_e_3);
            fl_int64 _fl_e_2;
            FL_CHECKED_ADD(_fl_e_3, digit, &_fl_e_2);
            result = _fl_e_2;
        } else {
            return (FL_Option_int64){.tag = 0};
        }
        fl_int _fl_e_4;
        FL_CHECKED_ADD(i, 1, &_fl_e_4);
        i = _fl_e_4;
    }
    if (negative) {
        fl_int64 _fl_e_5;
        FL_CHECKED_SUB(((fl_int64)0), result, &_fl_e_5);
        result = _fl_e_5;
    }
    return (FL_Option_int64){.tag = 1, .value = result};
}

/* Flow: conv.string_to_float */
FL_Option_float fl_conv_string_to_float(FL_String* s) {
    fl_int len = fl_string_len(s);
    if (len == 0) {
        return (FL_Option_float){.tag = 0};
    }
    fl_int start = 0;
    fl_bool negative = fl_false;
    FL_Option_char _fl_tmp_4 = fl_string_char_at(s, 0);
    if (_fl_tmp_4.tag == 1) {
        fl_char c = _fl_tmp_4.value;
        if (c == 45) {
            negative = fl_true;
            start = 1;
        } else {
            if (c == 43) {
                start = 1;
            }
        }
    } else {
        return (FL_Option_float){.tag = 0};
    }
    if (start >= len) {
        return (FL_Option_float){.tag = 0};
    }
    fl_float result = 0.0;
    fl_int i = start;
    fl_bool has_digits = fl_false;
    while (i < len) {
        FL_Option_char _fl_tmp_5 = fl_string_char_at(s, i);
        if (_fl_tmp_5.tag == 1) {
            fl_char c = _fl_tmp_5.value;
            if (fl_char_is_digit(c)) {
                fl_int _fl_e_1;
                FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_1);
                fl_float digit = ((fl_float)_fl_e_1);
                result = ((result * 10.0) + digit);
                has_digits = fl_true;
                fl_int _fl_e_2;
                FL_CHECKED_ADD(i, 1, &_fl_e_2);
                i = _fl_e_2;
            } else {
                i = i;
                return fl_conv_parse_float_rest(s, len, i, result, negative, has_digits);
            }
        } else {
            return (FL_Option_float){.tag = 0};
        }
    }
    if (!has_digits) {
        return (FL_Option_float){.tag = 0};
    }
    if (negative) {
        result = (0.0 - result);
    }
    return (FL_Option_float){.tag = 1, .value = result};
}

/* Flow: conv.parse_float_rest */
FL_Option_float fl_conv_parse_float_rest(FL_String* s, fl_int len, fl_int pos, fl_float int_part, fl_bool negative, fl_bool has_digits_before) {
    fl_float result = int_part;
    fl_int i = pos;
    fl_bool has_digits = has_digits_before;
    fl_bool at_dot = fl_false;
    if (i < len) {
        FL_Option_char _fl_tmp_6 = fl_string_char_at(s, i);
        if (_fl_tmp_6.tag == 1) {
            fl_char c = _fl_tmp_6.value;
            if (c == 46) {
                at_dot = fl_true;
                fl_int _fl_e_1;
                FL_CHECKED_ADD(i, 1, &_fl_e_1);
                i = _fl_e_1;
            }
        }
    }
    if (at_dot) {
        fl_float frac = 0.0;
        fl_float frac_div = 1.0;
        while (i < len) {
            FL_Option_char _fl_tmp_7 = fl_string_char_at(s, i);
            if (_fl_tmp_7.tag == 1) {
                fl_char c = _fl_tmp_7.value;
                if (fl_char_is_digit(c)) {
                    fl_int _fl_e_2;
                    FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_2);
                    fl_float digit = ((fl_float)_fl_e_2);
                    frac = ((frac * 10.0) + digit);
                    frac_div = (frac_div * 10.0);
                    has_digits = fl_true;
                    fl_int _fl_e_3;
                    FL_CHECKED_ADD(i, 1, &_fl_e_3);
                    i = _fl_e_3;
                } else {
                    return fl_conv_parse_float_exp(s, len, i, (result + (frac / frac_div)), negative, has_digits);
                }
            } else {
                return (FL_Option_float){.tag = 0};
            }
        }
        result = (result + (frac / frac_div));
    }
    if (!has_digits) {
        return (FL_Option_float){.tag = 0};
    }
    if (i < len) {
        return fl_conv_parse_float_exp(s, len, i, result, negative, has_digits);
    }
    if (negative) {
        result = (0.0 - result);
    }
    return (FL_Option_float){.tag = 1, .value = result};
}

/* Flow: conv.parse_float_exp */
FL_Option_float fl_conv_parse_float_exp(FL_String* s, fl_int len, fl_int pos, fl_float mantissa, fl_bool negative, fl_bool has_digits) {
    fl_int i = pos;
    if (!has_digits) {
        return (FL_Option_float){.tag = 0};
    }
    fl_bool at_exp = fl_false;
    if (i < len) {
        FL_Option_char _fl_tmp_8 = fl_string_char_at(s, i);
        if (_fl_tmp_8.tag == 1) {
            fl_char c = _fl_tmp_8.value;
            if ((c == 101) || (c == 69)) {
                at_exp = fl_true;
                fl_int _fl_e_1;
                FL_CHECKED_ADD(i, 1, &_fl_e_1);
                i = _fl_e_1;
            }
        }
    }
    fl_float result = mantissa;
    if (at_exp) {
        fl_bool exp_neg = fl_false;
        if (i < len) {
            FL_Option_char _fl_tmp_9 = fl_string_char_at(s, i);
            if (_fl_tmp_9.tag == 1) {
                fl_char c = _fl_tmp_9.value;
                if (c == 45) {
                    exp_neg = fl_true;
                    fl_int _fl_e_2;
                    FL_CHECKED_ADD(i, 1, &_fl_e_2);
                    i = _fl_e_2;
                } else {
                    if (c == 43) {
                        fl_int _fl_e_3;
                        FL_CHECKED_ADD(i, 1, &_fl_e_3);
                        i = _fl_e_3;
                    }
                }
            }
        }
        fl_int exp_val = 0;
        fl_bool exp_digits = fl_false;
        while (i < len) {
            FL_Option_char _fl_tmp_10 = fl_string_char_at(s, i);
            if (_fl_tmp_10.tag == 1) {
                fl_char c = _fl_tmp_10.value;
                if (fl_char_is_digit(c)) {
                    fl_int _fl_e_5;
                    FL_CHECKED_MUL(exp_val, 10, &_fl_e_5);
                    fl_int _fl_e_6;
                    FL_CHECKED_SUB(fl_char_to_code(c), fl_char_to_code(48), &_fl_e_6);
                    fl_int _fl_e_4;
                    FL_CHECKED_ADD(_fl_e_5, _fl_e_6, &_fl_e_4);
                    exp_val = _fl_e_4;
                    exp_digits = fl_true;
                } else {
                    return (FL_Option_float){.tag = 0};
                }
            } else {
                return (FL_Option_float){.tag = 0};
            }
            fl_int _fl_e_7;
            FL_CHECKED_ADD(i, 1, &_fl_e_7);
            i = _fl_e_7;
        }
        if (!exp_digits) {
            return (FL_Option_float){.tag = 0};
        }
        fl_float multiplier = 1.0;
        fl_int e = 0;
        while (e < exp_val) {
            multiplier = (multiplier * 10.0);
            fl_int _fl_e_8;
            FL_CHECKED_ADD(e, 1, &_fl_e_8);
            e = _fl_e_8;
        }
        if (exp_neg) {
            result = (result / multiplier);
        } else {
            result = (result * multiplier);
        }
    }
    if (i != len) {
        return (FL_Option_float){.tag = 0};
    }
    if (negative) {
        result = (0.0 - result);
    }
    return (FL_Option_float){.tag = 1, .value = result};
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

typedef struct fl_tests_app_log_pipeline_Severity fl_tests_app_log_pipeline_Severity;

typedef struct fl_tests_app_log_pipeline_LogEntry fl_tests_app_log_pipeline_LogEntry;

fl_tests_app_log_pipeline_Severity fl_tests_app_log_pipeline_make_severity(FL_String* name);

fl_tests_app_log_pipeline_LogEntry fl_tests_app_log_pipeline_parse_kv_log(FL_String* line);

fl_tests_app_log_pipeline_LogEntry fl_tests_app_log_pipeline_parse_csv_log(FL_String* line);

fl_tests_app_log_pipeline_LogEntry fl_tests_app_log_pipeline_parse_simple_log(FL_String* line);

fl_tests_app_log_pipeline_LogEntry fl_tests_app_log_pipeline_detect_and_parse(FL_String* line);

FL_String* fl_tests_app_log_pipeline_write_archive(fl_tests_app_log_pipeline_LogEntry entry);

FL_String* fl_tests_app_log_pipeline_update_stats(fl_tests_app_log_pipeline_LogEntry entry);

FL_String* fl_tests_app_log_pipeline_combine_output(FL_String* archived, FL_String* stats);

void fl_tests_app_log_pipeline_main(void);

struct fl_tests_app_log_pipeline_Severity {
    fl_int level;
    FL_String* name;
};

struct fl_tests_app_log_pipeline_LogEntry {
    FL_String* timestamp;
    fl_tests_app_log_pipeline_Severity severity;
    FL_String* source;
    FL_String* message;
};

FL_String* _fl_str_tests_app_log_pipeline_0 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_1 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_2 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_3 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_4 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_5 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_6 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_7 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_8 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_9 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_10 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_11 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_12 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_13 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_14 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_15 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_16 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_17 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_18 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_19 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_20 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_21 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_22 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_23 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_24 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_25 = NULL;

FL_String* _fl_str_tests_app_log_pipeline_26 = NULL;

/* Flow: tests.app_log_pipeline.make_severity */
fl_tests_app_log_pipeline_Severity fl_tests_app_log_pipeline_make_severity(FL_String* name) {
    if (fl_string_eq(name, _fl_str_tests_app_log_pipeline_0)) {
        fl_string_retain(_fl_str_tests_app_log_pipeline_0);
        return (fl_tests_app_log_pipeline_Severity){.level = 0, .name = _fl_str_tests_app_log_pipeline_0};
    }
    if (fl_string_eq(name, _fl_str_tests_app_log_pipeline_1)) {
        fl_string_retain(_fl_str_tests_app_log_pipeline_1);
        return (fl_tests_app_log_pipeline_Severity){.level = 1, .name = _fl_str_tests_app_log_pipeline_1};
    }
    if (fl_string_eq(name, _fl_str_tests_app_log_pipeline_2)) {
        fl_string_retain(_fl_str_tests_app_log_pipeline_2);
        return (fl_tests_app_log_pipeline_Severity){.level = 2, .name = _fl_str_tests_app_log_pipeline_2};
    }
    fl_string_retain(_fl_str_tests_app_log_pipeline_3);
    return (fl_tests_app_log_pipeline_Severity){.level = 3, .name = _fl_str_tests_app_log_pipeline_3};
}

/* Flow: tests.app_log_pipeline.parse_kv_log */
fl_tests_app_log_pipeline_LogEntry fl_tests_app_log_pipeline_parse_kv_log(FL_String* line) {
    FL_Array* parts = fl_string_split(line, _fl_str_tests_app_log_pipeline_4);
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* ts = fl_string_replace(((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_tests_app_log_pipeline_5), _fl_str_tests_app_log_pipeline_6, _fl_str_tests_app_log_pipeline_5);
    FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, 1);
    FL_String* level = fl_string_replace(((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_tests_app_log_pipeline_5), _fl_str_tests_app_log_pipeline_7, _fl_str_tests_app_log_pipeline_5);
    FL_Option_ptr _fl_tmp_2 = fl_array_get_safe(parts, 2);
    FL_String* src = fl_string_replace(((_fl_tmp_2.tag == 1) ? _fl_tmp_2.value : _fl_str_tests_app_log_pipeline_5), _fl_str_tests_app_log_pipeline_8, _fl_str_tests_app_log_pipeline_5);
    FL_Option_ptr _fl_tmp_3 = fl_array_get_safe(parts, 3);
    FL_String* msg = fl_string_replace(((_fl_tmp_3.tag == 1) ? _fl_tmp_3.value : _fl_str_tests_app_log_pipeline_5), _fl_str_tests_app_log_pipeline_9, _fl_str_tests_app_log_pipeline_5);
    fl_string_retain(ts);
    fl_string_retain(src);
    fl_string_retain(msg);
    return (fl_tests_app_log_pipeline_LogEntry){.timestamp = ts, .severity = fl_tests_app_log_pipeline_make_severity(level), .source = src, .message = msg};
}

/* Flow: tests.app_log_pipeline.parse_csv_log */
fl_tests_app_log_pipeline_LogEntry fl_tests_app_log_pipeline_parse_csv_log(FL_String* line) {
    FL_Array* parts = fl_string_split(line, _fl_str_tests_app_log_pipeline_10);
    FL_Option_ptr _fl_tmp_4 = fl_array_get_safe(parts, 0);
    fl_string_retain(((_fl_tmp_4.tag == 1) ? _fl_tmp_4.value : _fl_str_tests_app_log_pipeline_5));
    FL_Option_ptr _fl_tmp_5 = fl_array_get_safe(parts, 1);
    FL_Option_ptr _fl_tmp_6 = fl_array_get_safe(parts, 2);
    fl_string_retain(((_fl_tmp_6.tag == 1) ? _fl_tmp_6.value : _fl_str_tests_app_log_pipeline_5));
    FL_Option_ptr _fl_tmp_7 = fl_array_get_safe(parts, 3);
    fl_string_retain(((_fl_tmp_7.tag == 1) ? _fl_tmp_7.value : _fl_str_tests_app_log_pipeline_5));
    return (fl_tests_app_log_pipeline_LogEntry){.timestamp = ((_fl_tmp_4.tag == 1) ? _fl_tmp_4.value : _fl_str_tests_app_log_pipeline_5), .severity = fl_tests_app_log_pipeline_make_severity(((_fl_tmp_5.tag == 1) ? _fl_tmp_5.value : _fl_str_tests_app_log_pipeline_5)), .source = ((_fl_tmp_6.tag == 1) ? _fl_tmp_6.value : _fl_str_tests_app_log_pipeline_5), .message = ((_fl_tmp_7.tag == 1) ? _fl_tmp_7.value : _fl_str_tests_app_log_pipeline_5)};
}

/* Flow: tests.app_log_pipeline.parse_simple_log */
fl_tests_app_log_pipeline_LogEntry fl_tests_app_log_pipeline_parse_simple_log(FL_String* line) {
    FL_Array* parts = fl_string_split(line, _fl_str_tests_app_log_pipeline_4);
    FL_Option_ptr _fl_tmp_8 = fl_array_get_safe(parts, 0);
    fl_string_retain(((_fl_tmp_8.tag == 1) ? _fl_tmp_8.value : _fl_str_tests_app_log_pipeline_5));
    FL_Option_ptr _fl_tmp_9 = fl_array_get_safe(parts, 2);
    FL_Option_ptr _fl_tmp_10 = fl_array_get_safe(parts, 1);
    fl_string_retain(((_fl_tmp_10.tag == 1) ? _fl_tmp_10.value : _fl_str_tests_app_log_pipeline_5));
    FL_Option_ptr _fl_tmp_11 = fl_array_get_safe(parts, 3);
    fl_string_retain(((_fl_tmp_11.tag == 1) ? _fl_tmp_11.value : _fl_str_tests_app_log_pipeline_5));
    return (fl_tests_app_log_pipeline_LogEntry){.timestamp = ((_fl_tmp_8.tag == 1) ? _fl_tmp_8.value : _fl_str_tests_app_log_pipeline_5), .severity = fl_tests_app_log_pipeline_make_severity(((_fl_tmp_9.tag == 1) ? _fl_tmp_9.value : _fl_str_tests_app_log_pipeline_5)), .source = ((_fl_tmp_10.tag == 1) ? _fl_tmp_10.value : _fl_str_tests_app_log_pipeline_5), .message = ((_fl_tmp_11.tag == 1) ? _fl_tmp_11.value : _fl_str_tests_app_log_pipeline_5)};
}

/* Flow: tests.app_log_pipeline.detect_and_parse */
fl_tests_app_log_pipeline_LogEntry fl_tests_app_log_pipeline_detect_and_parse(FL_String* line) {
    if (fl_string_starts_with(line, _fl_str_tests_app_log_pipeline_6)) {
        return fl_tests_app_log_pipeline_parse_kv_log(line);
    }
    if (fl_string_contains(line, _fl_str_tests_app_log_pipeline_10)) {
        return fl_tests_app_log_pipeline_parse_csv_log(line);
    }
    return fl_tests_app_log_pipeline_parse_simple_log(line);
}

/* Flow: tests.app_log_pipeline.write_archive */
FL_String* fl_tests_app_log_pipeline_write_archive(fl_tests_app_log_pipeline_LogEntry entry) {
    FL_String* _fl_tmp_12 = fl_string_concat(_fl_str_tests_app_log_pipeline_11, entry.timestamp);
    FL_String* _fl_tmp_13 = fl_string_concat(_fl_tmp_12, _fl_str_tests_app_log_pipeline_12);
    FL_String* _fl_tmp_14 = fl_string_concat(_fl_tmp_13, entry.source);
    FL_String* _fl_tmp_15 = fl_string_concat(_fl_tmp_14, _fl_str_tests_app_log_pipeline_4);
    return fl_string_concat(_fl_tmp_15, entry.message);
}

/* Flow: tests.app_log_pipeline.update_stats */
FL_String* fl_tests_app_log_pipeline_update_stats(fl_tests_app_log_pipeline_LogEntry entry) {
    FL_String* _fl_tmp_16 = fl_string_concat(_fl_str_tests_app_log_pipeline_13, entry.severity.name);
    FL_String* _fl_tmp_17 = fl_string_concat(_fl_tmp_16, _fl_str_tests_app_log_pipeline_14);
    return fl_string_concat(_fl_tmp_17, entry.source);
}

/* Flow: tests.app_log_pipeline.combine_output */
FL_String* fl_tests_app_log_pipeline_combine_output(FL_String* archived, FL_String* stats) {
    FL_String* _fl_tmp_18 = fl_string_concat(archived, _fl_str_tests_app_log_pipeline_15);
    return fl_string_concat(_fl_tmp_18, stats);
}

/* Flow: tests.app_log_pipeline.main */
void fl_tests_app_log_pipeline_main(void) {
    FL_Array* _fl_tmp_19 = fl_array_new(5, sizeof(FL_String*), (FL_String*[]){_fl_str_tests_app_log_pipeline_16, _fl_str_tests_app_log_pipeline_17, _fl_str_tests_app_log_pipeline_18, _fl_str_tests_app_log_pipeline_19, _fl_str_tests_app_log_pipeline_20});
    fl_array_set_elem_type(_fl_tmp_19, 1);
    fl_string_retain(_fl_str_tests_app_log_pipeline_16);
    fl_string_retain(_fl_str_tests_app_log_pipeline_17);
    fl_string_retain(_fl_str_tests_app_log_pipeline_18);
    fl_string_retain(_fl_str_tests_app_log_pipeline_19);
    fl_string_retain(_fl_str_tests_app_log_pipeline_20);
    FL_Array* lines = _fl_tmp_19;
    fl_int64 _fl_tmp_20 = 0;
    while (_fl_tmp_20 < fl_array_len(lines)) {
        FL_String* line = (*((FL_String**)fl_array_get_ptr(lines, _fl_tmp_20)));
        FL_ExceptionFrame _fl_ef_0;
        _fl_exception_push((&_fl_ef_0));
        if (setjmp(_fl_ef_0.jmp) == 0) {
            fl_tests_app_log_pipeline_LogEntry entry = fl_tests_app_log_pipeline_detect_and_parse(line);
            if (fl_string_len(entry.timestamp) == 0) {
                _fl_throw(((void*)_fl_str_tests_app_log_pipeline_21), 0);
            }
            if (fl_string_len(entry.source) == 0) {
                _fl_throw(((void*)_fl_str_tests_app_log_pipeline_22), 0);
            }
            fl_tests_app_log_pipeline_LogEntry _fl_tmp_21 = entry;
            FL_String* _fl_tmp_22 = fl_tests_app_log_pipeline_write_archive(_fl_tmp_21);
            FL_String* _fl_tmp_23 = fl_tests_app_log_pipeline_update_stats(_fl_tmp_21);
            FL_String* output = fl_tests_app_log_pipeline_combine_output(_fl_tmp_22, _fl_tmp_23);
            fl_string_retain(output);
            fl_println(output);
            if (entry.severity.level <= 1) {
                FL_String* _fl_tmp_24 = fl_string_concat(_fl_str_tests_app_log_pipeline_23, entry.severity.name);
                FL_String* _fl_tmp_25 = fl_string_concat(_fl_tmp_24, _fl_str_tests_app_log_pipeline_24);
                FL_String* _fl_tmp_26 = fl_string_concat(_fl_tmp_25, entry.source);
                FL_String* _fl_tmp_27 = fl_string_concat(_fl_tmp_26, _fl_str_tests_app_log_pipeline_25);
                fl_println(fl_string_concat(_fl_tmp_27, entry.message));
                fl_string_release(_fl_tmp_24);
                fl_string_release(_fl_tmp_25);
                fl_string_release(_fl_tmp_26);
                fl_string_release(_fl_tmp_27);
            }
            _fl_exception_pop();
        } else {
            _fl_exception_pop();
            if (_fl_ef_0.exception_tag == 0) {
                FL_String* e = ((FL_String*)_fl_ef_0.exception);
                fl_println(fl_string_concat(_fl_str_tests_app_log_pipeline_26, e));
            } else {
                _fl_throw(_fl_ef_0.exception, _fl_ef_0.exception_tag);
            }
        }
        _fl_tmp_20 = (_fl_tmp_20 + 1);
    }
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_0 = fl_string_from_cstr("ERROR");
    _fl_str_tests_app_log_pipeline_0->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_1 = fl_string_from_cstr("WARN");
    _fl_str_tests_app_log_pipeline_1->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_2 = fl_string_from_cstr("INFO");
    _fl_str_tests_app_log_pipeline_2->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_3 = fl_string_from_cstr("DEBUG");
    _fl_str_tests_app_log_pipeline_3->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_4 = fl_string_from_cstr(" ");
    _fl_str_tests_app_log_pipeline_4->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_5 = fl_string_from_cstr("");
    _fl_str_tests_app_log_pipeline_5->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_6 = fl_string_from_cstr("ts=");
    _fl_str_tests_app_log_pipeline_6->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_7 = fl_string_from_cstr("level=");
    _fl_str_tests_app_log_pipeline_7->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_8 = fl_string_from_cstr("src=");
    _fl_str_tests_app_log_pipeline_8->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_9 = fl_string_from_cstr("msg=");
    _fl_str_tests_app_log_pipeline_9->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_10 = fl_string_from_cstr(",");
    _fl_str_tests_app_log_pipeline_10->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_11 = fl_string_from_cstr("ARCHIVE: [");
    _fl_str_tests_app_log_pipeline_11->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_12 = fl_string_from_cstr("] ");
    _fl_str_tests_app_log_pipeline_12->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_13 = fl_string_from_cstr("STATS: severity=");
    _fl_str_tests_app_log_pipeline_13->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_14 = fl_string_from_cstr(" source=");
    _fl_str_tests_app_log_pipeline_14->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_15 = fl_string_from_cstr("\n");
    _fl_str_tests_app_log_pipeline_15->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_16 = fl_string_from_cstr("ts=2024-01-01 level=ERROR src=api msg=timeout");
    _fl_str_tests_app_log_pipeline_16->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_17 = fl_string_from_cstr("2024-01-01,INFO,db,connected");
    _fl_str_tests_app_log_pipeline_17->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_18 = fl_string_from_cstr("2024-01-01 web WARN slow_query");
    _fl_str_tests_app_log_pipeline_18->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_19 = fl_string_from_cstr("corrupt???");
    _fl_str_tests_app_log_pipeline_19->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_20 = fl_string_from_cstr("ts=2024-01-02 level=WARN src=api msg=retry");
    _fl_str_tests_app_log_pipeline_20->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_21 = fl_string_from_cstr("empty timestamp");
    _fl_str_tests_app_log_pipeline_21->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_22 = fl_string_from_cstr("empty source");
    _fl_str_tests_app_log_pipeline_22->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_23 = fl_string_from_cstr("ALERT: ");
    _fl_str_tests_app_log_pipeline_23->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_24 = fl_string_from_cstr(" from ");
    _fl_str_tests_app_log_pipeline_24->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_25 = fl_string_from_cstr(": ");
    _fl_str_tests_app_log_pipeline_25->refcount = 2147483647;
    _fl_str_tests_app_log_pipeline_26 = fl_string_from_cstr("SKIP: ");
    _fl_str_tests_app_log_pipeline_26->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_tests_app_log_pipeline_main();
    return 0;
}
