/* Generated by reflowc - do not edit */
/* Source: tests/programs/app_csv_to_json.reflow */
#include "reflow_runtime.h"

typedef struct rf_tests_app_csv_to_json_Schema rf_tests_app_csv_to_json_Schema;

typedef struct rf_tests_app_csv_to_json_CsvRow rf_tests_app_csv_to_json_CsvRow;

RF_String* rf_conv_to_string__int(rf_int val);

rf_tests_app_csv_to_json_CsvRow rf_tests_app_csv_to_json_parse_row(rf_int idx, RF_String* line);

rf_bool rf_tests_app_csv_to_json_is_required(RF_String* name, RF_Array* required);

rf_tests_app_csv_to_json_CsvRow rf_tests_app_csv_to_json_validate(rf_tests_app_csv_to_json_CsvRow row, rf_tests_app_csv_to_json_Schema schema);

RF_String* rf_tests_app_csv_to_json_escape_json(RF_String* s);

RF_String* rf_tests_app_csv_to_json_to_json(rf_tests_app_csv_to_json_CsvRow row, rf_tests_app_csv_to_json_Schema schema);

RF_String* rf_tests_app_csv_to_json_sanitize(RF_String* line);

void rf_tests_app_csv_to_json_main(void);

struct rf_tests_app_csv_to_json_Schema {
    RF_Array* columns;
    RF_Array* required;
};

struct rf_tests_app_csv_to_json_CsvRow {
    rf_int index;
    RF_Array* fields;
};

/* ReFlow: conv.to_string[mono] */
RF_String* rf_conv_to_string__int(rf_int val) {
    return rf_int_to_string(val);
}

/* ReFlow: tests.app_csv_to_json.parse_row */
rf_tests_app_csv_to_json_CsvRow rf_tests_app_csv_to_json_parse_row(rf_int idx, RF_String* line) {
    RF_Array* fields = rf_string_split(line, rf_string_from_cstr(","));
    return (rf_tests_app_csv_to_json_CsvRow){.index = idx, .fields = fields};
}

/* ReFlow: tests.app_csv_to_json.is_required */
rf_bool rf_tests_app_csv_to_json_is_required(RF_String* name, RF_Array* required) {
    rf_int64 _rf_tmp_0 = 0;
    while (_rf_tmp_0 < rf_array_len(required)) {
        RF_String* r = (*((RF_String**)rf_array_get_ptr(required, _rf_tmp_0)));
        if (rf_string_eq(r, name)) {
            return rf_true;
        }
        _rf_tmp_0 = (_rf_tmp_0 + 1);
    }
    return rf_false;
}

/* ReFlow: tests.app_csv_to_json.validate */
rf_tests_app_csv_to_json_CsvRow rf_tests_app_csv_to_json_validate(rf_tests_app_csv_to_json_CsvRow row, rf_tests_app_csv_to_json_Schema schema) {
    RF_Array* cols = schema.columns;
    rf_int i = 0;
    while (i < rf_array_len_int(cols)) {
        RF_Option_ptr _rf_tmp_1 = rf_array_get_safe(cols, i);
        RF_String* col_name = ((_rf_tmp_1.tag == 1) ? _rf_tmp_1.value : rf_string_from_cstr(""));
        if (rf_tests_app_csv_to_json_is_required(col_name, schema.required)) {
            RF_Option_ptr _rf_tmp_2 = rf_array_get_safe(row.fields, i);
            RF_String* field_val = ((_rf_tmp_2.tag == 1) ? _rf_tmp_2.value : rf_string_from_cstr(""));
            if (rf_string_len(field_val) == 0) {
                _rf_throw(((void*)rf_string_concat(rf_string_concat(rf_string_concat(rf_string_from_cstr("missing required field '"), col_name), rf_string_from_cstr("' at row ")), rf_conv_to_string__int(row.index))), 0);
            }
        }
        rf_int _rf_e_1;
        RF_CHECKED_ADD(i, 1, &_rf_e_1);
        i = _rf_e_1;
    }
    return row;
}

/* ReFlow: tests.app_csv_to_json.escape_json */
RF_String* rf_tests_app_csv_to_json_escape_json(RF_String* s) {
    RF_String* r1 = rf_string_replace(s, rf_string_from_cstr("\\"), rf_string_from_cstr("\\\\"));
    RF_String* r2 = rf_string_replace(r1, rf_string_from_cstr("\""), rf_string_from_cstr("\\\""));
    return r2;
}

/* ReFlow: tests.app_csv_to_json.to_json */
RF_String* rf_tests_app_csv_to_json_to_json(rf_tests_app_csv_to_json_CsvRow row, rf_tests_app_csv_to_json_Schema schema) {
    RF_Array* cols = schema.columns;
    void* b = rf_sb_new();
    rf_sb_append(b, rf_string_from_cstr("{"));
    rf_int i = 0;
    while (i < rf_array_len_int(cols)) {
        if (i > 0) {
            rf_sb_append(b, rf_string_from_cstr(","));
        }
        RF_Option_ptr _rf_tmp_3 = rf_array_get_safe(cols, i);
        RF_String* col_name = ((_rf_tmp_3.tag == 1) ? _rf_tmp_3.value : rf_string_from_cstr(""));
        RF_Option_ptr _rf_tmp_4 = rf_array_get_safe(row.fields, i);
        RF_String* field_val = ((_rf_tmp_4.tag == 1) ? _rf_tmp_4.value : rf_string_from_cstr(""));
        rf_sb_append(b, rf_string_from_cstr("\""));
        rf_sb_append(b, rf_tests_app_csv_to_json_escape_json(col_name));
        rf_sb_append(b, rf_string_from_cstr("\":"));
        if (rf_string_len(field_val) > 0) {
            rf_sb_append(b, rf_string_from_cstr("\""));
            rf_sb_append(b, rf_tests_app_csv_to_json_escape_json(field_val));
            rf_sb_append(b, rf_string_from_cstr("\""));
        } else {
            rf_sb_append(b, rf_string_from_cstr("null"));
        }
        rf_int _rf_e_1;
        RF_CHECKED_ADD(i, 1, &_rf_e_1);
        i = _rf_e_1;
    }
    rf_sb_append(b, rf_string_from_cstr("}"));
    return rf_sb_build(b);
}

/* ReFlow: tests.app_csv_to_json.sanitize */
RF_String* rf_tests_app_csv_to_json_sanitize(RF_String* line) {
    RF_String* cleaned = rf_string_replace(line, rf_string_from_cstr("\""), rf_string_from_cstr(""));
    return rf_string_trim(cleaned);
}

/* ReFlow: tests.app_csv_to_json.main */
void rf_tests_app_csv_to_json_main(void) {
    RF_Array* lines = rf_array_new(5, sizeof(RF_String*), (RF_String*[]){rf_string_from_cstr("name,age,city"), rf_string_from_cstr("Alice,30,NYC"), rf_string_from_cstr("Bob,,London"), rf_string_from_cstr(",bad,data"), rf_string_from_cstr("Charlie,25,Paris")});
    rf_tests_app_csv_to_json_Schema schema = (rf_tests_app_csv_to_json_Schema){.columns = rf_array_new(3, sizeof(RF_String*), (RF_String*[]){rf_string_from_cstr("name"), rf_string_from_cstr("age"), rf_string_from_cstr("city")}), .required = rf_array_new(1, sizeof(RF_String*), (RF_String*[]){rf_string_from_cstr("name")})};
    rf_int i = 1;
    while (i < rf_array_len_int(lines)) {
        RF_Option_ptr _rf_tmp_5 = rf_array_get_safe(lines, i);
        RF_String* line = ((_rf_tmp_5.tag == 1) ? _rf_tmp_5.value : rf_string_from_cstr(""));
        RF_ExceptionFrame _rf_ef_0;
        _rf_exception_push((&_rf_ef_0));
        if (setjmp(_rf_ef_0.jmp) == 0) {
            rf_tests_app_csv_to_json_CsvRow row = rf_tests_app_csv_to_json_parse_row(i, line);
            rf_tests_app_csv_to_json_CsvRow validated = rf_tests_app_csv_to_json_validate(row, schema);
            RF_String* json_str = rf_tests_app_csv_to_json_to_json(validated, schema);
            rf_println(json_str);
            _rf_exception_pop();
        } else {
            _rf_exception_pop();
            if (_rf_ef_0.exception_tag == 0) {
                RF_String* e = ((RF_String*)_rf_ef_0.exception);
                RF_ExceptionFrame _rf_ef_1;
                _rf_exception_push((&_rf_ef_1));
                if (setjmp(_rf_ef_1.jmp) == 0) {
                    RF_String* fixed = rf_tests_app_csv_to_json_sanitize(line);
                    rf_tests_app_csv_to_json_CsvRow row = rf_tests_app_csv_to_json_parse_row(i, fixed);
                    rf_tests_app_csv_to_json_CsvRow validated = rf_tests_app_csv_to_json_validate(row, schema);
                    RF_String* json_str = rf_tests_app_csv_to_json_to_json(validated, schema);
                    rf_println(json_str);
                    _rf_exception_pop();
                } else {
                    _rf_exception_pop();
                    if (_rf_ef_1.exception_tag == 0) {
                        RF_String* e2 = ((RF_String*)_rf_ef_1.exception);
                        rf_println(rf_string_concat(rf_string_concat(rf_string_concat(rf_string_from_cstr("SKIP row "), rf_conv_to_string__int(i)), rf_string_from_cstr(": ")), e2));
                    } else {
                        _rf_throw(_rf_ef_1.exception, _rf_ef_1.exception_tag);
                    }
                }
            } else {
                _rf_throw(_rf_ef_0.exception, _rf_ef_0.exception_tag);
            }
        }
        rf_int _rf_e_1;
        RF_CHECKED_ADD(i, 1, &_rf_e_1);
        i = _rf_e_1;
    }
}

/* Entry point */
int main(int argc, char** argv) {
    _rf_runtime_init(argc, argv);
    rf_tests_app_csv_to_json_main();
    return 0;
}
