/* Generated by reflowc - do not edit */
/* Source: tests/programs/app_json_query.reflow */
#include "reflow_runtime.h"

typedef struct RF_Tuple_RF_Array_ptr_RF_String_ptr RF_Tuple_RF_Array_ptr_RF_String_ptr;

RF_String* rf_conv_to_string__int(rf_int val);

RF_Tuple_RF_Array_ptr_RF_String_ptr rf_tests_app_json_query_parse_path(RF_String* query);

rf_bool rf_tests_app_json_query_is_array_index(RF_String* segment);

RF_String* rf_tests_app_json_query_type_name(RF_JsonValue* val);

RF_Option_ptr rf_tests_app_json_query_value_length(RF_JsonValue* val);

RF_Array* rf_tests_app_json_query_resolve_segment(RF_JsonValue* val, RF_String* segment);

RF_Array* rf_tests_app_json_query_resolve(RF_JsonValue* root, RF_Array* segments);

RF_String* rf_tests_app_json_query_format_value(RF_JsonValue* val, rf_bool pretty);

void rf_tests_app_json_query_run_query(RF_JsonValue* root, RF_String* query, rf_bool pretty);

void rf_tests_app_json_query_main(void);

void rf_tests_app_json_query_run_tests(RF_JsonValue* root);

struct RF_Tuple_RF_Array_ptr_RF_String_ptr {
    RF_Array* _0;
    RF_String* _1;
};

/* ReFlow: conv.to_string[mono] */
RF_String* rf_conv_to_string__int(rf_int val) {
    return rf_int_to_string(val);
}

/* ReFlow: tests.app_json_query.parse_path */
RF_Tuple_RF_Array_ptr_RF_String_ptr rf_tests_app_json_query_parse_path(RF_String* query) {
    if (rf_string_len(query) == 0) {
        return (RF_Tuple_RF_Array_ptr_RF_String_ptr){._0 = rf_array_new(0, 0, NULL), ._1 = rf_string_from_cstr("")};
    }
    if (rf_string_starts_with(query, rf_string_from_cstr("."))) {
        return (RF_Tuple_RF_Array_ptr_RF_String_ptr){._0 = rf_array_new(0, 0, NULL), ._1 = rf_string_from_cstr("leading dot in path")};
    }
    if (rf_string_ends_with(query, rf_string_from_cstr("."))) {
        return (RF_Tuple_RF_Array_ptr_RF_String_ptr){._0 = rf_array_new(0, 0, NULL), ._1 = rf_string_from_cstr("trailing dot in path")};
    }
    RF_String* q = query;
    rf_bool has_type_suffix = rf_false;
    if (rf_string_ends_with(q, rf_string_from_cstr("?type"))) {
        rf_int _rf_e_1;
        RF_CHECKED_SUB(rf_string_len(q), 5, &_rf_e_1);
        rf_int prefix_len = _rf_e_1;
        RF_String* _rf_tmp_0;
        if (prefix_len > 0) {
            _rf_tmp_0 = rf_string_substring(q, 0, prefix_len);
        } else {
            _rf_tmp_0 = rf_string_from_cstr("");
        }
        q = _rf_tmp_0;
        has_type_suffix = rf_true;
    }
    RF_Array* segments = rf_array_new(0, 0, NULL);
    if (rf_string_len(q) > 0) {
        RF_Array* parts = rf_string_split(q, rf_string_from_cstr("."));
        rf_int i = 0;
        while (i < rf_array_len_int(parts)) {
            RF_Option_ptr _rf_tmp_1 = rf_array_get_safe(parts, i);
            if (_rf_tmp_1.tag == 1) {
                RF_String* part = _rf_tmp_1.value;
                if (rf_string_len(part) == 0) {
                    return (RF_Tuple_RF_Array_ptr_RF_String_ptr){._0 = rf_array_new(0, 0, NULL), ._1 = rf_string_from_cstr("empty segment (double dot)")};
                }
                segments = rf_array_push_ptr(segments, part);
            }
            rf_int _rf_e_2;
            RF_CHECKED_ADD(i, 1, &_rf_e_2);
            i = _rf_e_2;
        }
    }
    if (has_type_suffix) {
        segments = rf_array_push_ptr(segments, rf_string_from_cstr("?type"));
    }
    return (RF_Tuple_RF_Array_ptr_RF_String_ptr){._0 = segments, ._1 = rf_string_from_cstr("")};
}

/* ReFlow: tests.app_json_query.is_array_index */
rf_bool rf_tests_app_json_query_is_array_index(RF_String* segment) {
    if (rf_string_len(segment) == 0) {
        return rf_false;
    }
    RF_Option_int64 _rf_tmp_2 = rf_string_to_int64_opt(segment);
    if (_rf_tmp_2.tag == 1) {
        rf_int64 n = _rf_tmp_2.value;
        return (n >= 0);
    } else {
        return rf_false;
    }
}

/* ReFlow: tests.app_json_query.type_name */
RF_String* rf_tests_app_json_query_type_name(RF_JsonValue* val) {
    rf_byte tag = rf_json_type_tag(val);
    if (tag == 0) {
        return rf_string_from_cstr("null");
    }
    if (tag == 1) {
        return rf_string_from_cstr("boolean");
    }
    if (tag == 2) {
        return rf_string_from_cstr("number");
    }
    if (tag == 3) {
        return rf_string_from_cstr("number");
    }
    if (tag == 4) {
        return rf_string_from_cstr("string");
    }
    if (tag == 5) {
        return rf_string_from_cstr("array");
    }
    if (tag == 6) {
        return rf_string_from_cstr("object");
    }
    return rf_string_from_cstr("unknown");
}

/* ReFlow: tests.app_json_query.value_length */
RF_Option_ptr rf_tests_app_json_query_value_length(RF_JsonValue* val) {
    rf_byte tag = rf_json_type_tag(val);
    if (tag == 5) {
        RF_Option_ptr _rf_tmp_3 = rf_json_as_array(val);
        if (_rf_tmp_3.tag == 1) {
            RF_Array* arr = _rf_tmp_3.value;
            return (RF_Option_ptr){.tag = 1, .value = rf_json_int(rf_array_len_int(arr))};
        } else {
            return (RF_Option_ptr){.tag = 1, .value = rf_json_int(0)};
        }
    }
    if (tag == 6) {
        RF_Option_ptr _rf_tmp_4 = rf_json_keys(val);
        if (_rf_tmp_4.tag == 1) {
            RF_Array* keys = _rf_tmp_4.value;
            return (RF_Option_ptr){.tag = 1, .value = rf_json_int(rf_array_len_int(keys))};
        } else {
            return (RF_Option_ptr){.tag = 1, .value = rf_json_int(0)};
        }
    }
    if (tag == 4) {
        RF_Option_ptr _rf_tmp_5 = rf_json_as_string(val);
        if (_rf_tmp_5.tag == 1) {
            RF_String* s = _rf_tmp_5.value;
            return (RF_Option_ptr){.tag = 1, .value = rf_json_int(rf_string_len(s))};
        } else {
            return (RF_Option_ptr){.tag = 1, .value = rf_json_int(0)};
        }
    }
    return (RF_Option_ptr){.tag = 0};
}

/* ReFlow: tests.app_json_query.resolve_segment */
RF_Array* rf_tests_app_json_query_resolve_segment(RF_JsonValue* val, RF_String* segment) {
    if (rf_string_eq(segment, rf_string_from_cstr("#"))) {
        RF_Option_ptr _rf_tmp_6 = rf_tests_app_json_query_value_length(val);
        if (_rf_tmp_6.tag == 1) {
            void* v = _rf_tmp_6.value;
            return rf_array_new(1, sizeof(void*), (void*[]){v});
        } else {
            return rf_array_new(0, 0, NULL);
        }
    }
    if (rf_string_eq(segment, rf_string_from_cstr("?type"))) {
        return rf_array_new(1, sizeof(void*), (void*[]){rf_json_string(rf_tests_app_json_query_type_name(val))});
    }
    if (rf_string_eq(segment, rf_string_from_cstr("*"))) {
        RF_Option_ptr _rf_tmp_7 = rf_json_as_array(val);
        if (_rf_tmp_7.tag == 1) {
            RF_Array* arr = _rf_tmp_7.value;
            return arr;
        } else {
            return rf_array_new(0, 0, NULL);
        }
    }
    if (rf_tests_app_json_query_is_array_index(segment)) {
        RF_Option_int64 _rf_tmp_8 = rf_string_to_int64_opt(segment);
        if (_rf_tmp_8.tag == 1) {
            rf_int64 idx = _rf_tmp_8.value;
            RF_Option_ptr _rf_tmp_9 = rf_json_get_index(val, idx);
            if (_rf_tmp_9.tag == 1) {
                void* v = _rf_tmp_9.value;
                return rf_array_new(1, sizeof(void*), (void*[]){v});
            } else {
                return rf_array_new(0, 0, NULL);
            }
        }
        return rf_array_new(0, 0, NULL);
    }
    RF_Option_ptr _rf_tmp_10 = rf_json_get(val, segment);
    if (_rf_tmp_10.tag == 1) {
        void* v = _rf_tmp_10.value;
        return rf_array_new(1, sizeof(void*), (void*[]){v});
    } else {
        return rf_array_new(0, 0, NULL);
    }
}

/* ReFlow: tests.app_json_query.resolve */
RF_Array* rf_tests_app_json_query_resolve(RF_JsonValue* root, RF_Array* segments) {
    RF_Array* current = rf_array_new(1, sizeof(void*), (void*[]){root});
    rf_int i = 0;
    while (i < rf_array_len_int(segments)) {
        RF_Option_ptr _rf_tmp_11 = rf_array_get_safe(segments, i);
        if (_rf_tmp_11.tag == 1) {
            RF_String* segment = _rf_tmp_11.value;
            RF_Array* next = rf_array_new(0, 0, NULL);
            rf_int j = 0;
            while (j < rf_array_len_int(current)) {
                RF_Option_ptr _rf_tmp_12 = rf_array_get_safe(current, j);
                if (_rf_tmp_12.tag == 1) {
                    void* val = _rf_tmp_12.value;
                    next = rf_array_concat(next, rf_tests_app_json_query_resolve_segment(val, segment));
                }
                rf_int _rf_e_1;
                RF_CHECKED_ADD(j, 1, &_rf_e_1);
                j = _rf_e_1;
            }
            current = next;
        }
        rf_int _rf_e_2;
        RF_CHECKED_ADD(i, 1, &_rf_e_2);
        i = _rf_e_2;
    }
    return current;
}

/* ReFlow: tests.app_json_query.format_value */
RF_String* rf_tests_app_json_query_format_value(RF_JsonValue* val, rf_bool pretty) {
    rf_byte tag = rf_json_type_tag(val);
    if (tag == 4) {
        RF_Option_ptr _rf_tmp_13 = rf_json_as_string(val);
        return ((_rf_tmp_13.tag == 1) ? _rf_tmp_13.value : rf_string_from_cstr(""));
    }
    if (((tag == 5) || (tag == 6)) && pretty) {
        return rf_json_to_string_pretty(val, 2);
    }
    return rf_json_to_string(val);
}

/* ReFlow: tests.app_json_query.run_query */
void rf_tests_app_json_query_run_query(RF_JsonValue* root, RF_String* query, rf_bool pretty) {
    RF_Tuple_RF_Array_ptr_RF_String_ptr parsed = rf_tests_app_json_query_parse_path(query);
    RF_Array* segments = parsed._0;
    RF_String* parse_err = parsed._1;
    if (rf_string_len(parse_err) > 0) {
        rf_println(rf_string_concat(rf_string_from_cstr("ERROR: "), parse_err));
        return;
    }
    RF_Array* results = rf_tests_app_json_query_resolve(root, segments);
    if (rf_array_len_int(results) == 0) {
        rf_println(rf_string_from_cstr("(not found)"));
        return;
    }
    rf_int i = 0;
    while (i < rf_array_len_int(results)) {
        RF_Option_ptr _rf_tmp_14 = rf_array_get_safe(results, i);
        if (_rf_tmp_14.tag == 1) {
            void* val = _rf_tmp_14.value;
            rf_println(rf_tests_app_json_query_format_value(val, pretty));
        }
        rf_int _rf_e_1;
        RF_CHECKED_ADD(i, 1, &_rf_e_1);
        i = _rf_e_1;
    }
}

/* ReFlow: tests.app_json_query.main */
void rf_tests_app_json_query_main(void) {
    RF_String* test_json = rf_string_from_cstr("{\"name\":\"Alice\",\"age\":30,\"active\":true,\"nothing\":null,\"address\":{\"city\":\"New York\",\"zip\":\"10001\"},\"scores\":[95,87,92],\"users\":[{\"name\":\"Alice\",\"email\":\"alice@example.com\"},{\"name\":\"Bob\",\"email\":\"bob@example.com\"},{\"name\":\"Charlie\",\"email\":\"charlie@example.com\"}]}");
    RF_Option_ptr _rf_tmp_15 = rf_json_parse(test_json);
    if (_rf_tmp_15.tag == 1) {
        void* root = _rf_tmp_15.value;
        rf_tests_app_json_query_run_tests(root);
    } else {
        rf_println(rf_string_from_cstr("FAIL: could not parse test JSON"));
        return;
    }
}

/* ReFlow: tests.app_json_query.run_tests */
void rf_tests_app_json_query_run_tests(RF_JsonValue* root) {
    rf_println(rf_string_from_cstr("=== parse_path tests ==="));
    RF_Tuple_RF_Array_ptr_RF_String_ptr p1 = rf_tests_app_json_query_parse_path(rf_string_from_cstr("name"));
    rf_println(rf_string_concat(rf_string_concat(rf_string_from_cstr("'name' -> "), rf_conv_to_string__int(rf_array_len_int(p1._0))), rf_string_from_cstr(" segments")));
    RF_Tuple_RF_Array_ptr_RF_String_ptr p2 = rf_tests_app_json_query_parse_path(rf_string_from_cstr("users.0.email"));
    rf_println(rf_string_concat(rf_string_concat(rf_string_from_cstr("'users.0.email' -> "), rf_conv_to_string__int(rf_array_len_int(p2._0))), rf_string_from_cstr(" segments")));
    RF_Tuple_RF_Array_ptr_RF_String_ptr p3 = rf_tests_app_json_query_parse_path(rf_string_from_cstr(""));
    rf_println(rf_string_concat(rf_string_concat(rf_string_from_cstr("'' -> "), rf_conv_to_string__int(rf_array_len_int(p3._0))), rf_string_from_cstr(" segments")));
    RF_Tuple_RF_Array_ptr_RF_String_ptr p4 = rf_tests_app_json_query_parse_path(rf_string_from_cstr("foo..bar"));
    rf_println(rf_string_concat(rf_string_from_cstr("'foo..bar' -> error: "), p4._1));
    RF_Tuple_RF_Array_ptr_RF_String_ptr p5 = rf_tests_app_json_query_parse_path(rf_string_from_cstr(".leading"));
    rf_println(rf_string_concat(rf_string_from_cstr("'.leading' -> error: "), p5._1));
    RF_Tuple_RF_Array_ptr_RF_String_ptr p6 = rf_tests_app_json_query_parse_path(rf_string_from_cstr("trailing."));
    rf_println(rf_string_concat(rf_string_from_cstr("'trailing.' -> error: "), p6._1));
    RF_Tuple_RF_Array_ptr_RF_String_ptr p7 = rf_tests_app_json_query_parse_path(rf_string_from_cstr("name?type"));
    rf_println(rf_string_concat(rf_string_concat(rf_string_from_cstr("'name?type' -> "), rf_conv_to_string__int(rf_array_len_int(p7._0))), rf_string_from_cstr(" segments")));
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== Basic access ==="));
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("name"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("age"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("active"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("nothing"), rf_false);
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== Nested access ==="));
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("address.city"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("address.zip"), rf_false);
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== Array index ==="));
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("scores.0"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("scores.2"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("users.0.email"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("users.1.name"), rf_false);
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== Length operator ==="));
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("users.#"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("scores.#"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("name.#"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("address.#"), rf_false);
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== Wildcard ==="));
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("users.*.name"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("users.*.email"), rf_false);
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== Type queries ==="));
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("name?type"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("age?type"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("active?type"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("nothing?type"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("users?type"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("address?type"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("?type"), rf_false);
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== Pretty print ==="));
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("address"), rf_true);
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== Not found ==="));
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("nonexistent"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("users.99"), rf_false);
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("users.0.phone"), rf_false);
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("=== Root query ==="));
    rf_tests_app_json_query_run_query(root, rf_string_from_cstr("?type"), rf_false);
    rf_println(rf_string_from_cstr(""));
    rf_println(rf_string_from_cstr("done"));
}

/* Entry point */
int main(int argc, char** argv) {
    _rf_runtime_init(argc, argv);
    rf_tests_app_json_query_main();
    return 0;
}
