/* Generated by flowc - do not edit */
/* Source: tests/programs/app_parallel_enrich.flow */
#include "flow_runtime.h"

typedef struct fl_tests_app_parallel_enrich_Record fl_tests_app_parallel_enrich_Record;

typedef struct _fl_frame_tests_app_parallel_enrich_produce_values _fl_frame_tests_app_parallel_enrich_produce_values;

FL_String* fl_conv_to_string__int(fl_int val);

fl_int fl_tests_app_parallel_enrich_compute_score(fl_int value);

FL_String* fl_tests_app_parallel_enrich_categorize(fl_int value);

fl_int fl_tests_app_parallel_enrich_compute_hash(fl_int value);

FL_String* fl_tests_app_parallel_enrich_format_result(fl_int score, FL_String* category, fl_int hash);

FL_Option_ptr _fl_next_tests_app_parallel_enrich_produce_values(FL_Stream* self);

void _fl_free_tests_app_parallel_enrich_produce_values(FL_Stream* self);

FL_Stream* fl_tests_app_parallel_enrich_produce_values(void);

void* _fl_fanout_tests_app_parallel_enrich_main_0_0(void* _arg);

void* _fl_fanout_tests_app_parallel_enrich_main_0_1(void* _arg);

void* _fl_fanout_tests_app_parallel_enrich_main_0_2(void* _arg);

void fl_tests_app_parallel_enrich_main(void);

struct fl_tests_app_parallel_enrich_Record {
    fl_int id;
    FL_String* name;
    fl_int value;
};

struct _fl_frame_tests_app_parallel_enrich_produce_values {
    fl_int _state;
};

/* Flow: conv.to_string[mono] */
FL_String* fl_conv_to_string__int(fl_int val) {
    return fl_int_to_string(val);
}

/* Flow: tests.app_parallel_enrich.compute_score */
fl_int fl_tests_app_parallel_enrich_compute_score(fl_int value) {
    fl_int _fl_e_2;
    FL_CHECKED_MUL(value, 3, &_fl_e_2);
    fl_int _fl_e_1;
    FL_CHECKED_ADD(_fl_e_2, 1, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.app_parallel_enrich.categorize */
FL_String* fl_tests_app_parallel_enrich_categorize(fl_int value) {
    if (value > 80) {
        return fl_string_from_cstr("high");
    }
    if (value > 40) {
        return fl_string_from_cstr("medium");
    }
    return fl_string_from_cstr("low");
}

/* Flow: tests.app_parallel_enrich.compute_hash */
fl_int fl_tests_app_parallel_enrich_compute_hash(fl_int value) {
    fl_int _fl_e_2;
    FL_CHECKED_MUL(value, 31, &_fl_e_2);
    fl_int _fl_e_1;
    FL_CHECKED_ADD(_fl_e_2, 17, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.app_parallel_enrich.format_result */
FL_String* fl_tests_app_parallel_enrich_format_result(fl_int score, FL_String* category, fl_int hash) {
    return fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("score="), fl_conv_to_string__int(score)), fl_string_from_cstr(" cat=")), category), fl_string_from_cstr(" hash=")), fl_conv_to_string__int(hash));
}

/* Flow: tests.app_parallel_enrich.produce_values::next */
FL_Option_ptr _fl_next_tests_app_parallel_enrich_produce_values(FL_Stream* self) {
    _fl_frame_tests_app_parallel_enrich_produce_values* frame = ((_fl_frame_tests_app_parallel_enrich_produce_values*)self->state);
    switch (frame->_state) {
        case 0:
            goto _fl_state_0;
            break;
        case 1:
            goto _fl_state_1;
            break;
        case 2:
            goto _fl_state_2;
            break;
        case 3:
            goto _fl_state_3;
            break;
        case 4:
            goto _fl_state_4;
            break;
        default:
            goto _fl_stream_done;
            break;
    }
_fl_state_0:;
    frame->_state = 1;
    return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)90))};
_fl_state_1:;
    frame->_state = 2;
    return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)45))};
_fl_state_2:;
    frame->_state = 3;
    return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)20))};
_fl_state_3:;
    frame->_state = 4;
    return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)75))};
_fl_state_4:;
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.app_parallel_enrich.produce_values::free */
void _fl_free_tests_app_parallel_enrich_produce_values(FL_Stream* self) {
    _fl_frame_tests_app_parallel_enrich_produce_values* frame = ((_fl_frame_tests_app_parallel_enrich_produce_values*)self->state);
    free(frame);
}

/* Flow: tests.app_parallel_enrich.produce_values */
FL_Stream* fl_tests_app_parallel_enrich_produce_values(void) {
    _fl_frame_tests_app_parallel_enrich_produce_values* frame = ((_fl_frame_tests_app_parallel_enrich_produce_values*)malloc(sizeof(_fl_frame_tests_app_parallel_enrich_produce_values)));
    frame->_state = 0;
    return fl_stream_new(_fl_next_tests_app_parallel_enrich_produce_values, _fl_free_tests_app_parallel_enrich_produce_values, ((void*)frame));
}

/* Flow: tests.app_parallel_enrich.main::fanout_0_0 */
void* _fl_fanout_tests_app_parallel_enrich_main_0_0(void* _arg) {
    return ((void*)((fl_int64)fl_tests_app_parallel_enrich_compute_score(((fl_int)((fl_int64)_arg)))));
}

/* Flow: tests.app_parallel_enrich.main::fanout_0_1 */
void* _fl_fanout_tests_app_parallel_enrich_main_0_1(void* _arg) {
    return ((void*)fl_tests_app_parallel_enrich_categorize(((fl_int)((fl_int64)_arg))));
}

/* Flow: tests.app_parallel_enrich.main::fanout_0_2 */
void* _fl_fanout_tests_app_parallel_enrich_main_0_2(void* _arg) {
    return ((void*)((fl_int64)fl_tests_app_parallel_enrich_compute_hash(((fl_int)((fl_int64)_arg)))));
}

/* Flow: tests.app_parallel_enrich.main */
void fl_tests_app_parallel_enrich_main(void) {
    FL_Array* names = fl_array_new(4, sizeof(FL_String*), (FL_String*[]){fl_string_from_cstr("alpha"), fl_string_from_cstr("beta"), fl_string_from_cstr("gamma"), fl_string_from_cstr("delta")});
    FL_Array* values = fl_array_new(4, sizeof(fl_int), (fl_int[]){90, 45, 20, 75});
    fl_println(fl_string_from_cstr("=== Parallel Enrichment ==="));
    fl_int idx = 0;
    fl_int64 _fl_tmp_0 = 0;
    while (_fl_tmp_0 < fl_array_len(values)) {
        fl_int v = (*((fl_int*)fl_array_get_ptr(values, _fl_tmp_0)));
        fl_int _fl_tmp_1 = v;
        FL_FanoutBranch _fl_tmp_2[3];
        _fl_tmp_2[0].fn = _fl_fanout_tests_app_parallel_enrich_main_0_0;
        _fl_tmp_2[0].arg = ((void*)((fl_int64)_fl_tmp_1));
        _fl_tmp_2[1].fn = _fl_fanout_tests_app_parallel_enrich_main_0_1;
        _fl_tmp_2[1].arg = ((void*)((fl_int64)_fl_tmp_1));
        _fl_tmp_2[2].fn = _fl_fanout_tests_app_parallel_enrich_main_0_2;
        _fl_tmp_2[2].arg = ((void*)((fl_int64)_fl_tmp_1));
        fl_fanout_run(_fl_tmp_2, 3);
        fl_int _fl_tmp_3 = ((fl_int)((fl_int64)_fl_tmp_2[0].result));
        FL_String* _fl_tmp_4 = ((FL_String*)_fl_tmp_2[1].result);
        fl_int _fl_tmp_5 = ((fl_int)((fl_int64)_fl_tmp_2[2].result));
        fl_int _fl_tmp_6 = _fl_tmp_3;
        FL_String* _fl_tmp_7 = _fl_tmp_4;
        fl_int _fl_tmp_8 = _fl_tmp_5;
        FL_String* output = fl_tests_app_parallel_enrich_format_result(_fl_tmp_6, _fl_tmp_7, _fl_tmp_8);
        FL_Option_ptr _fl_tmp_9 = fl_array_get_safe(names, idx);
        FL_String* name = ((_fl_tmp_9.tag == 1) ? _fl_tmp_9.value : fl_string_from_cstr(""));
        fl_println(fl_string_concat(fl_string_concat(name, fl_string_from_cstr(": ")), output));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(idx, 1, &_fl_e_1);
        idx = _fl_e_1;
        _fl_tmp_0 = (_fl_tmp_0 + 1);
    }
    fl_println(fl_string_from_cstr("=== Coroutine Stream ==="));
    FL_Coroutine* source = fl_coroutine_new(fl_tests_app_parallel_enrich_produce_values());
    fl_int j = 0;
    while (!fl_coroutine_done(source)) {
        FL_Option_ptr _fl_tmp_10 = fl_coroutine_next(source);
        FL_Option_int _fl_tmp_11;
        _fl_tmp_11.tag = _fl_tmp_10.tag;
        if (_fl_tmp_10.tag == 1) {
            _fl_tmp_11.value = ((fl_int)((fl_int64)_fl_tmp_10.value));
        }
        FL_Option_int _fl_tmp_12 = _fl_tmp_11;
        if (_fl_tmp_12.tag == 1) {
            fl_int v = _fl_tmp_12.value;
            FL_Option_ptr _fl_tmp_13 = fl_array_get_safe(names, j);
            FL_String* name = ((_fl_tmp_13.tag == 1) ? _fl_tmp_13.value : fl_string_from_cstr(""));
            fl_int score = fl_tests_app_parallel_enrich_compute_score(v);
            FL_String* cat = fl_tests_app_parallel_enrich_categorize(v);
            fl_int hash = fl_tests_app_parallel_enrich_compute_hash(v);
            fl_println(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(name, fl_string_from_cstr(": score=")), fl_conv_to_string__int(score)), fl_string_from_cstr(" cat=")), cat), fl_string_from_cstr(" hash=")), fl_conv_to_string__int(hash)));
            fl_int _fl_e_2;
            FL_CHECKED_ADD(j, 1, &_fl_e_2);
            j = _fl_e_2;
        }
    }
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_app_parallel_enrich_main();
    return 0;
}
