/* Generated by flowc - do not edit */
/* Source: tests/programs/app_stream_mux.flow */
#include "flow_runtime.h"

typedef struct fl_tests_app_stream_mux_Record fl_tests_app_stream_mux_Record;

FL_String* fl_conv_to_string__int(fl_int val);

FL_String* fl_tests_app_stream_mux_route(fl_tests_app_stream_mux_Record r);

FL_String* fl_tests_app_stream_mux_format_record(fl_tests_app_stream_mux_Record r);

void fl_tests_app_stream_mux_main(void);

struct fl_tests_app_stream_mux_Record {
    FL_String* category;
    fl_int priority;
    FL_String* data;
};

/* Flow: conv.to_string[mono] */
FL_String* fl_conv_to_string__int(fl_int val) {
    return fl_int_to_string(val);
}

/* Flow: tests.app_stream_mux.route */
FL_String* fl_tests_app_stream_mux_route(fl_tests_app_stream_mux_Record r) {
    if (fl_string_eq(r.category, fl_string_from_cstr("error"))) {
        return fl_string_from_cstr("alerts");
    }
    if (fl_string_eq(r.category, fl_string_from_cstr("metric"))) {
        return fl_string_from_cstr("metrics");
    }
    if (fl_string_eq(r.category, fl_string_from_cstr("audit"))) {
        return fl_string_from_cstr("archive");
    }
    return fl_string_from_cstr("default");
}

/* Flow: tests.app_stream_mux.format_record */
FL_String* fl_tests_app_stream_mux_format_record(fl_tests_app_stream_mux_Record r) {
    return fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_concat(fl_string_from_cstr("["), r.category), fl_string_from_cstr("/")), fl_conv_to_string__int(r.priority)), fl_string_from_cstr("] ")), r.data);
}

/* Flow: tests.app_stream_mux.main */
void fl_tests_app_stream_mux_main(void) {
    FL_Array* records = fl_array_new(6, sizeof(fl_tests_app_stream_mux_Record), (fl_tests_app_stream_mux_Record[]){(fl_tests_app_stream_mux_Record){.category = fl_string_from_cstr("error"), .priority = 1, .data = fl_string_from_cstr("disk full")}, (fl_tests_app_stream_mux_Record){.category = fl_string_from_cstr("metric"), .priority = 3, .data = fl_string_from_cstr("cpu=72%")}, (fl_tests_app_stream_mux_Record){.category = fl_string_from_cstr("audit"), .priority = 2, .data = fl_string_from_cstr("user login")}, (fl_tests_app_stream_mux_Record){.category = fl_string_from_cstr("error"), .priority = 1, .data = fl_string_from_cstr("OOM")}, (fl_tests_app_stream_mux_Record){.category = fl_string_from_cstr("metric"), .priority = 3, .data = fl_string_from_cstr("mem=85%")}, (fl_tests_app_stream_mux_Record){.category = fl_string_from_cstr("info"), .priority = 4, .data = fl_string_from_cstr("startup complete")}});
    FL_Map* destinations = fl_map_new();
    fl_int64 _fl_tmp_0 = 0;
    while (_fl_tmp_0 < fl_array_len(records)) {
        fl_tests_app_stream_mux_Record r = (*((fl_tests_app_stream_mux_Record*)fl_array_get_ptr(records, _fl_tmp_0)));
        FL_String* dest = fl_tests_app_stream_mux_route(r);
        FL_String* line = fl_tests_app_stream_mux_format_record(r);
        FL_Option_ptr _fl_tmp_1 = fl_map_get_str(destinations, dest);
        FL_String* existing = ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr(""));
        destinations = fl_map_set_str(destinations, dest, fl_string_concat(fl_string_concat(existing, line), fl_string_from_cstr("\n")));
        _fl_tmp_0 = (_fl_tmp_0 + 1);
    }
    FL_Array* ks = fl_map_keys(destinations);
    fl_int64 _fl_tmp_2 = 0;
    while (_fl_tmp_2 < fl_array_len(ks)) {
        FL_String* key = (*((FL_String**)fl_array_get_ptr(ks, _fl_tmp_2)));
        fl_println(fl_string_concat(fl_string_concat(fl_string_from_cstr("=== "), key), fl_string_from_cstr(" ===")));
        FL_Option_ptr _fl_tmp_3 = fl_map_get_str(destinations, key);
        fl_println(((_fl_tmp_3.tag == 1) ? _fl_tmp_3.value : fl_string_from_cstr("")));
        _fl_tmp_2 = (_fl_tmp_2 + 1);
    }
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_app_stream_mux_main();
    return 0;
}
