/* Generated by flowc - do not edit */
/* Source: tests/programs/array_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

/* Flow: tests.array_test.main */
void fl_tests_array_test_main(void) {
    FL_Array* nums = fl_array_new(5, sizeof(fl_int), (fl_int[]){10, 20, 30, 40, 50});
    fl_int total = 0;
    fl_int64 _fl_tmp_0 = 0;
    while (_fl_tmp_0 < fl_array_len(nums)) {
        fl_int n = (*((fl_int*)fl_array_get_ptr(nums, _fl_tmp_0)));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(total, n, &_fl_e_1);
        total = _fl_e_1;
        _fl_tmp_0 = (_fl_tmp_0 + 1);
    }
    FL_String* _fl_tmp_1 = fl_string_from_cstr("sum = ");
    FL_String* _fl_tmp_2 = fl_string_concat(_fl_tmp_1, fl_int_to_string(total));
    fl_string_release(_fl_tmp_1);
    fl_println(_fl_tmp_2);
    FL_Array* _fl_tmp_4 = fl_array_new(3, sizeof(fl_int), (fl_int[]){1, 2, 3});
    fl_int64 _fl_tmp_3 = 0;
    while (_fl_tmp_3 < fl_array_len(_fl_tmp_4)) {
        fl_int n = (*((fl_int*)fl_array_get_ptr(_fl_tmp_4, _fl_tmp_3)));
        FL_String* _fl_tmp_5 = fl_string_from_cstr("  ");
        FL_String* _fl_tmp_6 = fl_string_concat(_fl_tmp_5, fl_int_to_string(n));
        fl_string_release(_fl_tmp_5);
        fl_println(_fl_tmp_6);
        _fl_tmp_3 = (_fl_tmp_3 + 1);
    }
    fl_array_release(_fl_tmp_4);
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_array_test_main();
    return 0;
}
