/* Generated by flowc - do not edit */
/* Source: tests/programs/composition_test.flow */
#include "flow_runtime.h"

fl_int fl_tests_composition_test_double(fl_int x);

fl_int fl_tests_composition_test_square(fl_int x);

fl_int fl_tests_composition_test_add_one(fl_int x);

void fl_tests_composition_test_main(void);

/* Flow: tests.composition_test.double */
fl_int fl_tests_composition_test_double(fl_int x) {
    fl_int _fl_e_1;
    FL_CHECKED_MUL(x, 2, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.composition_test.square */
fl_int fl_tests_composition_test_square(fl_int x) {
    fl_int _fl_e_1;
    FL_CHECKED_MUL(x, x, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.composition_test.add_one */
fl_int fl_tests_composition_test_add_one(fl_int x) {
    fl_int _fl_e_1;
    FL_CHECKED_ADD(x, 1, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.composition_test.main */
void fl_tests_composition_test_main(void) {
    fl_int _fl_tmp_0 = 5;
    fl_int _fl_tmp_1 = fl_tests_composition_test_double(_fl_tmp_0);
    fl_int r1 = fl_tests_composition_test_square(_fl_tmp_1);
    FL_String* _fl_tmp_2 = fl_string_from_cstr("5 -> double -> square = ");
    fl_println(fl_string_concat(_fl_tmp_2, fl_int_to_string(r1)));
    fl_int _fl_tmp_3 = 3;
    fl_int _fl_tmp_4 = fl_tests_composition_test_add_one(_fl_tmp_3);
    fl_int r2 = fl_tests_composition_test_double(_fl_tmp_4);
    FL_String* _fl_tmp_5 = fl_string_from_cstr("3 -> add_one -> double = ");
    fl_println(fl_string_concat(_fl_tmp_5, fl_int_to_string(r2)));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_composition_test_main();
    return 0;
}
