/* Generated by flowc - do not edit */
/* Source: tests/programs/congruence_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        fl_string_retain(_fl_str_string_0);
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_string_release(_fl_tmp_2);
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

typedef struct fl_tests_congruence_test_LogEntry fl_tests_congruence_test_LogEntry;

typedef struct fl_tests_congruence_test_EventRecord fl_tests_congruence_test_EventRecord;

typedef struct fl_tests_congruence_test_MetricPoint fl_tests_congruence_test_MetricPoint;

void fl_tests_congruence_test_main(void);

struct fl_tests_congruence_test_LogEntry {
    fl_int timestamp;
    FL_String* source;
};

struct fl_tests_congruence_test_EventRecord {
    fl_int timestamp;
    FL_String* source;
};

struct fl_tests_congruence_test_MetricPoint {
    fl_int timestamp;
    fl_float value;
};

FL_String* _fl_str_tests_congruence_test_0 = NULL;

FL_String* _fl_str_tests_congruence_test_1 = NULL;

FL_String* _fl_str_tests_congruence_test_2 = NULL;

FL_String* _fl_str_tests_congruence_test_3 = NULL;

FL_String* _fl_str_tests_congruence_test_4 = NULL;

FL_String* _fl_str_tests_congruence_test_5 = NULL;

/* Flow: tests.congruence_test.main */
void fl_tests_congruence_test_main(void) {
    fl_string_retain(_fl_str_tests_congruence_test_0);
    fl_tests_congruence_test_LogEntry a = (fl_tests_congruence_test_LogEntry){.timestamp = 100, .source = _fl_str_tests_congruence_test_0};
    fl_string_retain(_fl_str_tests_congruence_test_1);
    fl_tests_congruence_test_EventRecord b = (fl_tests_congruence_test_EventRecord){.timestamp = 200, .source = _fl_str_tests_congruence_test_1};
    fl_tests_congruence_test_MetricPoint c = (fl_tests_congruence_test_MetricPoint){.timestamp = 300, .value = 3.14};
    if (fl_true) {
        fl_println(_fl_str_tests_congruence_test_2);
    } else {
        fl_println(_fl_str_tests_congruence_test_3);
    }
    if (fl_false) {
        fl_println(_fl_str_tests_congruence_test_4);
    } else {
        fl_println(_fl_str_tests_congruence_test_5);
    }
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_tests_congruence_test_0 = fl_string_from_cstr("us-east-1");
    _fl_str_tests_congruence_test_0->refcount = 2147483647;
    _fl_str_tests_congruence_test_1 = fl_string_from_cstr("eu-west-1");
    _fl_str_tests_congruence_test_1->refcount = 2147483647;
    _fl_str_tests_congruence_test_2 = fl_string_from_cstr("a === b: true");
    _fl_str_tests_congruence_test_2->refcount = 2147483647;
    _fl_str_tests_congruence_test_3 = fl_string_from_cstr("a === b: false");
    _fl_str_tests_congruence_test_3->refcount = 2147483647;
    _fl_str_tests_congruence_test_4 = fl_string_from_cstr("a === c: true");
    _fl_str_tests_congruence_test_4->refcount = 2147483647;
    _fl_str_tests_congruence_test_5 = fl_string_from_cstr("a === c: false");
    _fl_str_tests_congruence_test_5->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_tests_congruence_test_main();
    return 0;
}
