/* Generated by flowc - do not edit */
/* Source: tests/programs/coroutine_kill_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

typedef struct _fl_frame_tests_coroutine_kill_test_counter _fl_frame_tests_coroutine_kill_test_counter;

FL_Option_ptr _fl_next_tests_coroutine_kill_test_counter(FL_Stream* self);

void _fl_free_tests_coroutine_kill_test_counter(FL_Stream* self);

FL_Stream* fl_tests_coroutine_kill_test_counter(void);

void fl_tests_coroutine_kill_test_main(void);

struct _fl_frame_tests_coroutine_kill_test_counter {
    fl_int _state;
    fl_int i;
};

/* Flow: tests.coroutine_kill_test.counter::next */
FL_Option_ptr _fl_next_tests_coroutine_kill_test_counter(FL_Stream* self) {
    _fl_frame_tests_coroutine_kill_test_counter* frame = ((_fl_frame_tests_coroutine_kill_test_counter*)self->state);
    switch (frame->_state) {
        case 0: {
            goto _fl_state_0;
            break;
        }
        case 1: {
            goto _fl_state_1;
            break;
        }
        default: {
            goto _fl_stream_done;
            break;
        }
    }
_fl_state_0:;
    frame->i = 0;
    while (fl_true) {
        fl_int _fl_e_1;
        FL_CHECKED_ADD(frame->i, 1, &_fl_e_1);
        frame->i = _fl_e_1;
        frame->_state = 1;
        return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)frame->i))};
_fl_state_1:;
    }
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.coroutine_kill_test.counter::free */
void _fl_free_tests_coroutine_kill_test_counter(FL_Stream* self) {
    _fl_frame_tests_coroutine_kill_test_counter* frame = ((_fl_frame_tests_coroutine_kill_test_counter*)self->state);
    free(frame);
}

/* Flow: tests.coroutine_kill_test.counter */
FL_Stream* fl_tests_coroutine_kill_test_counter(void) {
    _fl_frame_tests_coroutine_kill_test_counter* frame = ((_fl_frame_tests_coroutine_kill_test_counter*)malloc(sizeof(_fl_frame_tests_coroutine_kill_test_counter)));
    frame->_state = 0;
    return fl_stream_new(_fl_next_tests_coroutine_kill_test_counter, _fl_free_tests_coroutine_kill_test_counter, ((void*)frame));
}

/* Flow: tests.coroutine_kill_test.main */
void fl_tests_coroutine_kill_test_main(void) {
    FL_Stream* _fl_tmp_0 = fl_tests_coroutine_kill_test_counter();
    FL_Coroutine* h = fl_coroutine_new_threaded(_fl_tmp_0, 64);
    FL_Option_ptr _fl_tmp_1 = fl_coroutine_next(h);
    FL_Option_int _fl_tmp_2;
    _fl_tmp_2.tag = _fl_tmp_1.tag;
    if (_fl_tmp_1.tag == 1) {
        _fl_tmp_2.value = ((fl_int)((fl_int64)_fl_tmp_1.value));
    }
    FL_Option_int _fl_tmp_3 = _fl_tmp_2;
    if (_fl_tmp_3.tag == 1) {
        fl_int v = _fl_tmp_3.value;
        FL_String* _fl_tmp_4 = fl_string_from_cstr("v=");
        fl_println(fl_string_concat(_fl_tmp_4, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("none"));
    }
    FL_Option_ptr _fl_tmp_5 = fl_coroutine_next(h);
    FL_Option_int _fl_tmp_6;
    _fl_tmp_6.tag = _fl_tmp_5.tag;
    if (_fl_tmp_5.tag == 1) {
        _fl_tmp_6.value = ((fl_int)((fl_int64)_fl_tmp_5.value));
    }
    FL_Option_int _fl_tmp_7 = _fl_tmp_6;
    if (_fl_tmp_7.tag == 1) {
        fl_int v = _fl_tmp_7.value;
        FL_String* _fl_tmp_8 = fl_string_from_cstr("v=");
        fl_println(fl_string_concat(_fl_tmp_8, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("none"));
    }
    fl_coroutine_kill(h);
    fl_println(fl_string_from_cstr("killed"));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_coroutine_kill_test_main();
    return 0;
}
