/* Generated by flowc - do not edit */
/* Source: tests/programs/coroutine_poll_test.flow */
#include "flow_runtime.h"

typedef struct _fl_frame_tests_coroutine_poll_test_counter _fl_frame_tests_coroutine_poll_test_counter;

FL_Option_ptr _fl_next_tests_coroutine_poll_test_counter(FL_Stream* self);

void _fl_free_tests_coroutine_poll_test_counter(FL_Stream* self);

FL_Stream* fl_tests_coroutine_poll_test_counter(void);

void fl_tests_coroutine_poll_test_main(void);

struct _fl_frame_tests_coroutine_poll_test_counter {
    fl_int _state;
};

/* Flow: tests.coroutine_poll_test.counter::next */
FL_Option_ptr _fl_next_tests_coroutine_poll_test_counter(FL_Stream* self) {
    _fl_frame_tests_coroutine_poll_test_counter* frame = ((_fl_frame_tests_coroutine_poll_test_counter*)self->state);
    switch (frame->_state) {
        case 0: {
            goto _fl_state_0;
            break;
        }
        case 1: {
            goto _fl_state_1;
            break;
        }
        case 2: {
            goto _fl_state_2;
            break;
        }
        case 3: {
            goto _fl_state_3;
            break;
        }
        default: {
            goto _fl_stream_done;
            break;
        }
    }
_fl_state_0:;
    frame->_state = 1;
    return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)1))};
_fl_state_1:;
    frame->_state = 2;
    return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)2))};
_fl_state_2:;
    frame->_state = 3;
    return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)3))};
_fl_state_3:;
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.coroutine_poll_test.counter::free */
void _fl_free_tests_coroutine_poll_test_counter(FL_Stream* self) {
    _fl_frame_tests_coroutine_poll_test_counter* frame = ((_fl_frame_tests_coroutine_poll_test_counter*)self->state);
    free(frame);
}

/* Flow: tests.coroutine_poll_test.counter */
FL_Stream* fl_tests_coroutine_poll_test_counter(void) {
    _fl_frame_tests_coroutine_poll_test_counter* frame = ((_fl_frame_tests_coroutine_poll_test_counter*)malloc(sizeof(_fl_frame_tests_coroutine_poll_test_counter)));
    frame->_state = 0;
    return fl_stream_new(_fl_next_tests_coroutine_poll_test_counter, _fl_free_tests_coroutine_poll_test_counter, ((void*)frame));
}

/* Flow: tests.coroutine_poll_test.main */
void fl_tests_coroutine_poll_test_main(void) {
    FL_Stream* _fl_tmp_0 = fl_tests_coroutine_poll_test_counter();
    FL_Coroutine* gen = fl_coroutine_new_threaded(_fl_tmp_0, 64);
    FL_Option_ptr _fl_tmp_1 = fl_coroutine_try_next(gen);
    FL_Option_int _fl_tmp_2;
    _fl_tmp_2.tag = _fl_tmp_1.tag;
    if (_fl_tmp_1.tag == 1) {
        _fl_tmp_2.value = ((fl_int)((fl_int64)_fl_tmp_1.value));
    }
    FL_Option_int _fl_tmp_3 = _fl_tmp_2;
    if (_fl_tmp_3.tag == 1) {
        fl_int v = _fl_tmp_3.value;
        FL_String* _fl_tmp_4 = fl_string_from_cstr("poll=");
        fl_println(fl_string_concat(_fl_tmp_4, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("poll=none"));
    }
    FL_Option_ptr _fl_tmp_5 = fl_coroutine_try_next(gen);
    FL_Option_int _fl_tmp_6;
    _fl_tmp_6.tag = _fl_tmp_5.tag;
    if (_fl_tmp_5.tag == 1) {
        _fl_tmp_6.value = ((fl_int)((fl_int64)_fl_tmp_5.value));
    }
    FL_Option_int _fl_tmp_7 = _fl_tmp_6;
    if (_fl_tmp_7.tag == 1) {
        fl_int v = _fl_tmp_7.value;
        FL_String* _fl_tmp_8 = fl_string_from_cstr("poll=");
        fl_println(fl_string_concat(_fl_tmp_8, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("poll=none"));
    }
    FL_Option_ptr _fl_tmp_9 = fl_coroutine_try_next(gen);
    FL_Option_int _fl_tmp_10;
    _fl_tmp_10.tag = _fl_tmp_9.tag;
    if (_fl_tmp_9.tag == 1) {
        _fl_tmp_10.value = ((fl_int)((fl_int64)_fl_tmp_9.value));
    }
    FL_Option_int _fl_tmp_11 = _fl_tmp_10;
    if (_fl_tmp_11.tag == 1) {
        fl_int v = _fl_tmp_11.value;
        FL_String* _fl_tmp_12 = fl_string_from_cstr("poll=");
        fl_println(fl_string_concat(_fl_tmp_12, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("poll=none"));
    }
    FL_Option_ptr _fl_tmp_13 = fl_coroutine_try_next(gen);
    FL_Option_int _fl_tmp_14;
    _fl_tmp_14.tag = _fl_tmp_13.tag;
    if (_fl_tmp_13.tag == 1) {
        _fl_tmp_14.value = ((fl_int)((fl_int64)_fl_tmp_13.value));
    }
    FL_Option_int _fl_tmp_15 = _fl_tmp_14;
    if (_fl_tmp_15.tag == 1) {
        fl_int v = _fl_tmp_15.value;
        FL_String* _fl_tmp_16 = fl_string_from_cstr("poll=");
        fl_println(fl_string_concat(_fl_tmp_16, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("poll=none"));
    }
    FL_String* _fl_tmp_17 = fl_string_from_cstr("done=");
    fl_println(fl_string_concat(_fl_tmp_17, fl_bool_to_string(fl_coroutine_done(gen))));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_coroutine_poll_test_main();
    return 0;
}
