/* Generated by flowc - do not edit */
/* Source: tests/programs/coroutine_pool_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        fl_string_retain(_fl_str_string_0);
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_string_release(_fl_tmp_2);
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

typedef struct _fl_frame_tests_coroutine_pool_test_producer _fl_frame_tests_coroutine_pool_test_producer;

typedef struct _fl_frame_tests_coroutine_pool_test_squarer _fl_frame_tests_coroutine_pool_test_squarer;

FL_Option_ptr _fl_next_tests_coroutine_pool_test_producer(FL_Stream* self);

void _fl_free_tests_coroutine_pool_test_producer(FL_Stream* self);

FL_Stream* fl_tests_coroutine_pool_test_producer(void);

FL_Option_ptr _fl_next_tests_coroutine_pool_test_squarer(FL_Stream* self);

void _fl_free_tests_coroutine_pool_test_squarer(FL_Stream* self);

FL_Stream* fl_tests_coroutine_pool_test_squarer(FL_Stream* inbox);

void fl_tests_coroutine_pool_test_main(void);

struct _fl_frame_tests_coroutine_pool_test_producer {
    fl_int _state;
    fl_int i;
};

struct _fl_frame_tests_coroutine_pool_test_squarer {
    fl_int _state;
    FL_Stream* inbox;
    fl_int val;
};

FL_String* _fl_str_tests_coroutine_pool_test_0 = NULL;

FL_String* _fl_str_tests_coroutine_pool_test_1 = NULL;

/* Flow: tests.coroutine_pool_test.producer::next */
FL_Option_ptr _fl_next_tests_coroutine_pool_test_producer(FL_Stream* self) {
    _fl_frame_tests_coroutine_pool_test_producer* frame = ((_fl_frame_tests_coroutine_pool_test_producer*)self->state);
    switch (frame->_state) {
        case 0: {
            goto _fl_state_0;
            break;
        }
        case 1: {
            goto _fl_state_1;
            break;
        }
        default: {
            goto _fl_stream_done;
            break;
        }
    }
_fl_state_0:;
    frame->i = 1;
    while (frame->i <= 6) {
        frame->_state = 1;
        return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)frame->i))};
_fl_state_1:;
        fl_int _fl_e_1;
        FL_CHECKED_ADD(frame->i, 1, &_fl_e_1);
        frame->i = _fl_e_1;
    }
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.coroutine_pool_test.producer::free */
void _fl_free_tests_coroutine_pool_test_producer(FL_Stream* self) {
    _fl_frame_tests_coroutine_pool_test_producer* frame = ((_fl_frame_tests_coroutine_pool_test_producer*)self->state);
    free(frame);
}

/* Flow: tests.coroutine_pool_test.producer */
FL_Stream* fl_tests_coroutine_pool_test_producer(void) {
    _fl_frame_tests_coroutine_pool_test_producer* frame = ((_fl_frame_tests_coroutine_pool_test_producer*)malloc(sizeof(_fl_frame_tests_coroutine_pool_test_producer)));
    frame->_state = 0;
    return fl_stream_new(_fl_next_tests_coroutine_pool_test_producer, _fl_free_tests_coroutine_pool_test_producer, ((void*)frame));
}

/* Flow: tests.coroutine_pool_test.squarer::next */
FL_Option_ptr _fl_next_tests_coroutine_pool_test_squarer(FL_Stream* self) {
    _fl_frame_tests_coroutine_pool_test_squarer* frame = ((_fl_frame_tests_coroutine_pool_test_squarer*)self->state);
    switch (frame->_state) {
        case 0: {
            goto _fl_state_0;
            break;
        }
        case 1: {
            goto _fl_state_1;
            break;
        }
        default: {
            goto _fl_stream_done;
            break;
        }
    }
_fl_state_0:;
    while (1) {
        FL_Option_ptr _fl_tmp_0 = fl_stream_next(frame->inbox);
        if (_fl_tmp_0.tag == 0) {
            break;
        }
        frame->val = ((fl_int)((fl_uint64)_fl_tmp_0.value));
        frame->_state = 1;
        fl_int _fl_e_1;
        FL_CHECKED_MUL(frame->val, frame->val, &_fl_e_1);
        return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)_fl_e_1))};
_fl_state_1:;
    }
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.coroutine_pool_test.squarer::free */
void _fl_free_tests_coroutine_pool_test_squarer(FL_Stream* self) {
    _fl_frame_tests_coroutine_pool_test_squarer* frame = ((_fl_frame_tests_coroutine_pool_test_squarer*)self->state);
    free(frame);
}

/* Flow: tests.coroutine_pool_test.squarer */
FL_Stream* fl_tests_coroutine_pool_test_squarer(FL_Stream* inbox) {
    _fl_frame_tests_coroutine_pool_test_squarer* frame = ((_fl_frame_tests_coroutine_pool_test_squarer*)malloc(sizeof(_fl_frame_tests_coroutine_pool_test_squarer)));
    frame->_state = 0;
    frame->inbox = inbox;
    return fl_stream_new(_fl_next_tests_coroutine_pool_test_squarer, _fl_free_tests_coroutine_pool_test_squarer, ((void*)frame));
}

/* Flow: tests.coroutine_pool_test.main */
void fl_tests_coroutine_pool_test_main(void) {
    FL_Stream* _fl_tmp_1 = fl_tests_coroutine_pool_test_producer();
    FL_Coroutine* _fl_tmp_2 = fl_coroutine_new_threaded(_fl_tmp_1, 64);
    FL_Channel* _fl_tmp_3 = fl_coroutine_get_channel(_fl_tmp_2);
    FL_Pool* _fl_tmp_4 = fl_pool_new(((void*)fl_tests_coroutine_pool_test_squarer), 3, _fl_tmp_3, 64);
    FL_Coroutine* _fl_tmp_5 = fl_pool_as_coroutine(_fl_tmp_4);
    FL_Coroutine* result = _fl_tmp_5;
    fl_int count = 0;
    while (!fl_coroutine_done(result)) {
        FL_Option_ptr _fl_tmp_6 = fl_coroutine_next(result);
        FL_Option_int _fl_tmp_7;
        _fl_tmp_7.tag = _fl_tmp_6.tag;
        if (_fl_tmp_6.tag == 1) {
            _fl_tmp_7.value = ((fl_int)((fl_int64)_fl_tmp_6.value));
        }
        FL_Option_int _fl_tmp_8 = _fl_tmp_7;
        if (_fl_tmp_8.tag == 1) {
            fl_int v = _fl_tmp_8.value;
            fl_int _fl_e_1;
            FL_CHECKED_ADD(count, 1, &_fl_e_1);
            count = _fl_e_1;
        }
    }
    FL_String* _fl_tmp_9 = _fl_str_tests_coroutine_pool_test_0;
    FL_String* _fl_tmp_10 = fl_string_concat(_fl_tmp_9, fl_int_to_string(count));
    fl_string_release(_fl_tmp_9);
    fl_println(_fl_tmp_10);
    fl_println(_fl_str_tests_coroutine_pool_test_1);
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_tests_coroutine_pool_test_0 = fl_string_from_cstr("count: ");
    _fl_str_tests_coroutine_pool_test_0->refcount = 2147483647;
    _fl_str_tests_coroutine_pool_test_1 = fl_string_from_cstr("done");
    _fl_str_tests_coroutine_pool_test_1->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_tests_coroutine_pool_test_main();
    return 0;
}
