/* Generated by flowc - do not edit */
/* Source: tests/programs/coroutine_capacity_send_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

typedef struct _fl_frame_tests_coroutine_capacity_send_test_echo_worker _fl_frame_tests_coroutine_capacity_send_test_echo_worker;

FL_Option_ptr _fl_next_tests_coroutine_capacity_send_test_echo_worker(FL_Stream* self);

void _fl_free_tests_coroutine_capacity_send_test_echo_worker(FL_Stream* self);

FL_Stream* fl_tests_coroutine_capacity_send_test_echo_worker(FL_Stream* inbox);

void fl_tests_coroutine_capacity_send_test_main(void);

struct _fl_frame_tests_coroutine_capacity_send_test_echo_worker {
    fl_int _state;
    FL_Stream* inbox;
    fl_bool running;
    fl_bool got_any;
    FL_String* msg;
};

/* Flow: tests.coroutine_capacity_send_test.echo_worker::next */
FL_Option_ptr _fl_next_tests_coroutine_capacity_send_test_echo_worker(FL_Stream* self) {
    _fl_frame_tests_coroutine_capacity_send_test_echo_worker* frame = ((_fl_frame_tests_coroutine_capacity_send_test_echo_worker*)self->state);
    switch (frame->_state) {
        case 0: {
            goto _fl_state_0;
            break;
        }
        case 1: {
            goto _fl_state_1;
            break;
        }
        default: {
            goto _fl_stream_done;
            break;
        }
    }
_fl_state_0:;
    frame->running = fl_true;
    while (frame->running) {
        frame->got_any = fl_false;
        while (1) {
            FL_Option_ptr _fl_tmp_0 = fl_stream_next(frame->inbox);
            if (_fl_tmp_0.tag == 0) {
                break;
            }
            frame->msg = ((FL_String*)_fl_tmp_0.value);
            frame->got_any = fl_true;
            frame->_state = 1;
            return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)fl_string_concat(fl_string_from_cstr("echo: "), frame->msg)))};
_fl_state_1:;
        }
        if (!frame->got_any) {
            frame->running = fl_false;
        }
    }
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.coroutine_capacity_send_test.echo_worker::free */
void _fl_free_tests_coroutine_capacity_send_test_echo_worker(FL_Stream* self) {
    _fl_frame_tests_coroutine_capacity_send_test_echo_worker* frame = ((_fl_frame_tests_coroutine_capacity_send_test_echo_worker*)self->state);
    free(frame);
}

/* Flow: tests.coroutine_capacity_send_test.echo_worker */
FL_Stream* fl_tests_coroutine_capacity_send_test_echo_worker(FL_Stream* inbox) {
    _fl_frame_tests_coroutine_capacity_send_test_echo_worker* frame = ((_fl_frame_tests_coroutine_capacity_send_test_echo_worker*)malloc(sizeof(_fl_frame_tests_coroutine_capacity_send_test_echo_worker)));
    frame->_state = 0;
    frame->inbox = inbox;
    return fl_stream_new(_fl_next_tests_coroutine_capacity_send_test_echo_worker, _fl_free_tests_coroutine_capacity_send_test_echo_worker, ((void*)frame));
}

/* Flow: tests.coroutine_capacity_send_test.main */
void fl_tests_coroutine_capacity_send_test_main(void) {
    FL_Channel* _fl_tmp_1 = fl_channel_new(16);
    FL_Stream* _fl_tmp_2 = fl_stream_from_channel_nonblocking(_fl_tmp_1);
    FL_Stream* _fl_tmp_3 = fl_tests_coroutine_capacity_send_test_echo_worker(_fl_tmp_2);
    FL_Coroutine* _fl_tmp_4 = fl_coroutine_new_threaded(_fl_tmp_3, 8);
    fl_coroutine_set_input(_fl_tmp_4, _fl_tmp_1);
    FL_Coroutine* w = _fl_tmp_4;
    fl_coroutine_send(w, ((void*)fl_string_from_cstr("hello")));
    fl_coroutine_send(w, ((void*)fl_string_from_cstr("world")));
    FL_Option_ptr _fl_tmp_5 = fl_coroutine_next(w);
    if (_fl_tmp_5.tag == 1) {
        FL_String* v = _fl_tmp_5.value;
        fl_println(v);
    } else {
        fl_println(fl_string_from_cstr("none"));
    }
    FL_Option_ptr _fl_tmp_6 = fl_coroutine_next(w);
    if (_fl_tmp_6.tag == 1) {
        FL_String* v = _fl_tmp_6.value;
        fl_println(v);
    } else {
        fl_println(fl_string_from_cstr("none"));
    }
    fl_println(fl_string_from_cstr("test complete"));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_coroutine_capacity_send_test_main();
    return 0;
}
