/* Generated by flowc - do not edit */
/* Source: tests/programs/coroutine_multi_test.flow */
#include "flow_runtime.h"

typedef struct _fl_frame_tests_coroutine_multi_test_naturals _fl_frame_tests_coroutine_multi_test_naturals;

FL_Option_ptr _fl_next_tests_coroutine_multi_test_naturals(FL_Stream* self);

void _fl_free_tests_coroutine_multi_test_naturals(FL_Stream* self);

FL_Stream* fl_tests_coroutine_multi_test_naturals(fl_int start);

void fl_tests_coroutine_multi_test_main(void);

struct _fl_frame_tests_coroutine_multi_test_naturals {
    fl_int _state;
    fl_int start;
    fl_int i;
};

/* Flow: tests.coroutine_multi_test.naturals::next */
FL_Option_ptr _fl_next_tests_coroutine_multi_test_naturals(FL_Stream* self) {
    _fl_frame_tests_coroutine_multi_test_naturals* frame = ((_fl_frame_tests_coroutine_multi_test_naturals*)self->state);
    switch (frame->_state) {
        case 0: {
            goto _fl_state_0;
            break;
        }
        case 1: {
            goto _fl_state_1;
            break;
        }
        default: {
            goto _fl_stream_done;
            break;
        }
    }
_fl_state_0:;
    frame->i = frame->start;
    while (fl_true) {
        frame->_state = 1;
        return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)frame->i))};
_fl_state_1:;
        fl_int _fl_e_1;
        FL_CHECKED_ADD(frame->i, 1, &_fl_e_1);
        frame->i = _fl_e_1;
    }
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.coroutine_multi_test.naturals::free */
void _fl_free_tests_coroutine_multi_test_naturals(FL_Stream* self) {
    _fl_frame_tests_coroutine_multi_test_naturals* frame = ((_fl_frame_tests_coroutine_multi_test_naturals*)self->state);
    free(frame);
}

/* Flow: tests.coroutine_multi_test.naturals */
FL_Stream* fl_tests_coroutine_multi_test_naturals(fl_int start) {
    _fl_frame_tests_coroutine_multi_test_naturals* frame = ((_fl_frame_tests_coroutine_multi_test_naturals*)malloc(sizeof(_fl_frame_tests_coroutine_multi_test_naturals)));
    frame->_state = 0;
    frame->start = start;
    return fl_stream_new(_fl_next_tests_coroutine_multi_test_naturals, _fl_free_tests_coroutine_multi_test_naturals, ((void*)frame));
}

/* Flow: tests.coroutine_multi_test.main */
void fl_tests_coroutine_multi_test_main(void) {
    FL_Stream* _fl_tmp_0 = fl_tests_coroutine_multi_test_naturals(0);
    FL_Coroutine* a = fl_coroutine_new_threaded(_fl_tmp_0, 64);
    FL_Stream* _fl_tmp_1 = fl_tests_coroutine_multi_test_naturals(100);
    FL_Coroutine* b = fl_coroutine_new_threaded(_fl_tmp_1, 64);
    FL_Option_ptr _fl_tmp_2 = fl_coroutine_next(a);
    FL_Option_int _fl_tmp_3;
    _fl_tmp_3.tag = _fl_tmp_2.tag;
    if (_fl_tmp_2.tag == 1) {
        _fl_tmp_3.value = ((fl_int)((fl_int64)_fl_tmp_2.value));
    }
    FL_Option_int _fl_tmp_4 = _fl_tmp_3;
    if (_fl_tmp_4.tag == 1) {
        fl_int v = _fl_tmp_4.value;
        FL_String* _fl_tmp_5 = fl_string_from_cstr("a=");
        fl_println(fl_string_concat(_fl_tmp_5, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("a=none"));
    }
    FL_Option_ptr _fl_tmp_6 = fl_coroutine_next(b);
    FL_Option_int _fl_tmp_7;
    _fl_tmp_7.tag = _fl_tmp_6.tag;
    if (_fl_tmp_6.tag == 1) {
        _fl_tmp_7.value = ((fl_int)((fl_int64)_fl_tmp_6.value));
    }
    FL_Option_int _fl_tmp_8 = _fl_tmp_7;
    if (_fl_tmp_8.tag == 1) {
        fl_int v = _fl_tmp_8.value;
        FL_String* _fl_tmp_9 = fl_string_from_cstr("b=");
        fl_println(fl_string_concat(_fl_tmp_9, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("b=none"));
    }
    FL_Option_ptr _fl_tmp_10 = fl_coroutine_next(a);
    FL_Option_int _fl_tmp_11;
    _fl_tmp_11.tag = _fl_tmp_10.tag;
    if (_fl_tmp_10.tag == 1) {
        _fl_tmp_11.value = ((fl_int)((fl_int64)_fl_tmp_10.value));
    }
    FL_Option_int _fl_tmp_12 = _fl_tmp_11;
    if (_fl_tmp_12.tag == 1) {
        fl_int v = _fl_tmp_12.value;
        FL_String* _fl_tmp_13 = fl_string_from_cstr("a=");
        fl_println(fl_string_concat(_fl_tmp_13, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("a=none"));
    }
    FL_Option_ptr _fl_tmp_14 = fl_coroutine_next(b);
    FL_Option_int _fl_tmp_15;
    _fl_tmp_15.tag = _fl_tmp_14.tag;
    if (_fl_tmp_14.tag == 1) {
        _fl_tmp_15.value = ((fl_int)((fl_int64)_fl_tmp_14.value));
    }
    FL_Option_int _fl_tmp_16 = _fl_tmp_15;
    if (_fl_tmp_16.tag == 1) {
        fl_int v = _fl_tmp_16.value;
        FL_String* _fl_tmp_17 = fl_string_from_cstr("b=");
        fl_println(fl_string_concat(_fl_tmp_17, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("b=none"));
    }
    FL_String* _fl_tmp_18 = fl_string_from_cstr("a_done=");
    fl_println(fl_string_concat(_fl_tmp_18, fl_bool_to_string(fl_coroutine_done(a))));
    FL_String* _fl_tmp_19 = fl_string_from_cstr("b_done=");
    fl_println(fl_string_concat(_fl_tmp_19, fl_bool_to_string(fl_coroutine_done(b))));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_coroutine_multi_test_main();
    return 0;
}
