/* Generated by flowc - do not edit */
/* Source: tests/programs/default_params.flow */
#include "flow_runtime.h"

FL_String* fl_main_greet(FL_String* name, FL_String* greeting);

fl_int fl_main_add(fl_int a, fl_int b, fl_int c);

void fl_main_main(void);

/* Flow: main.greet */
FL_String* fl_main_greet(FL_String* name, FL_String* greeting) {
    return fl_string_concat(fl_string_concat(fl_string_concat(greeting, fl_string_from_cstr(", ")), name), fl_string_from_cstr("!"));
}

/* Flow: main.add */
fl_int fl_main_add(fl_int a, fl_int b, fl_int c) {
    fl_int _fl_e_2;
    FL_CHECKED_ADD(a, b, &_fl_e_2);
    fl_int _fl_e_1;
    FL_CHECKED_ADD(_fl_e_2, c, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: main.main */
void fl_main_main(void) {
    fl_println(fl_main_greet(fl_string_from_cstr("World"), fl_string_from_cstr("Hello")));
    fl_println(fl_main_greet(fl_string_from_cstr("World"), fl_string_from_cstr("Hi")));
    fl_println(fl_int_to_string(fl_main_add(1, 10, 20)));
    fl_println(fl_int_to_string(fl_main_add(1, 2, 20)));
    fl_println(fl_int_to_string(fl_main_add(1, 2, 3)));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_main_main();
    return 0;
}
