/* Generated by flowc - do not edit */
/* Source: tests/programs/enum_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_string_release(_fl_tmp_2);
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

FL_String* fl_main_color_name(fl_int c);

fl_int fl_main_main(void);

typedef enum {
    fl_main_Color_Red = 0,
    fl_main_Color_Green = 1,
    fl_main_Color_Blue = 2
} fl_main_Color;

typedef enum {
    fl_main_Direction_North = 0,
    fl_main_Direction_South = 1,
    fl_main_Direction_East = 2,
    fl_main_Direction_West = 3
} fl_main_Direction;

typedef enum {
    fl_main_Offset_A = 10,
    fl_main_Offset_B = 11,
    fl_main_Offset_C = 12,
    fl_main_Offset_D = 20
} fl_main_Offset;

FL_String* _fl_str_main_0 = NULL;

FL_String* _fl_str_main_1 = NULL;

FL_String* _fl_str_main_2 = NULL;

/* Flow: main.color_name */
FL_String* fl_main_color_name(fl_int c) {
    if (c == fl_main_Color_Red) {
        return _fl_str_main_0;
    }
    if (c == fl_main_Color_Green) {
        return _fl_str_main_1;
    }
    return _fl_str_main_2;
}

/* Flow: main.main */
fl_int fl_main_main(void) {
    fl_println(fl_main_color_name(fl_main_Color_Red));
    fl_println(fl_main_color_name(fl_main_Color_Green));
    fl_println(fl_main_color_name(fl_main_Color_Blue));
    fl_int x = fl_main_Direction_North;
    FL_String* _fl_tmp_0 = fl_int_to_string(x);
    fl_println(_fl_tmp_0);
    fl_string_release(_fl_tmp_0);
    FL_String* _fl_tmp_1 = fl_int_to_string(((fl_int)fl_main_Direction_West));
    fl_println(_fl_tmp_1);
    fl_string_release(_fl_tmp_1);
    FL_String* _fl_tmp_2 = fl_int_to_string(((fl_int)fl_main_Offset_A));
    fl_println(_fl_tmp_2);
    fl_string_release(_fl_tmp_2);
    FL_String* _fl_tmp_3 = fl_int_to_string(((fl_int)fl_main_Offset_B));
    fl_println(_fl_tmp_3);
    fl_string_release(_fl_tmp_3);
    FL_String* _fl_tmp_4 = fl_int_to_string(((fl_int)fl_main_Offset_D));
    fl_println(_fl_tmp_4);
    fl_string_release(_fl_tmp_4);
    return 0;
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_main_0 = fl_string_from_cstr("red");
    _fl_str_main_0->refcount = 2147483647;
    _fl_str_main_1 = fl_string_from_cstr("green");
    _fl_str_main_1->refcount = 2147483647;
    _fl_str_main_2 = fl_string_from_cstr("blue");
    _fl_str_main_2->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_main_main();
    return 0;
}
