/* Generated by flowc - do not edit */
/* Source: tests/programs/exception_retry_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

fl_int fl_tests_exception_retry_test_parse_value(FL_String* s);

void fl_tests_exception_retry_test_main(void);

/* Flow: tests.exception_retry_test.parse_value */
fl_int fl_tests_exception_retry_test_parse_value(FL_String* s) {
    if (fl_string_eq(s, fl_string_from_cstr("bad"))) {
        _fl_throw(((void*)fl_string_from_cstr("parse error")), 0);
    }
    return 42;
}

/* Flow: tests.exception_retry_test.main */
void fl_tests_exception_retry_test_main(void) {
    FL_ExceptionFrame _fl_ef_0;
    fl_bool _fl_ef_0_caught = fl_true;
    _fl_exception_push((&_fl_ef_0));
    if (setjmp(_fl_ef_0.jmp) == 0) {
        fl_int val = fl_tests_exception_retry_test_parse_value(fl_string_from_cstr("bad"));
        FL_String* _fl_tmp_0 = fl_string_from_cstr("got: ");
        FL_String* _fl_tmp_1 = fl_string_concat(_fl_tmp_0, fl_int_to_string(val));
        fl_string_release(_fl_tmp_0);
        fl_println(_fl_tmp_1);
        _fl_exception_pop();
    } else {
        _fl_exception_pop();
        _fl_ef_0_caught = fl_false;
        if (_fl_ef_0.exception_tag == 0) {
            fl_int _fl_tmp_2 = 0;
            FL_String* ex = ((FL_String*)_fl_ef_0.exception);
            while (_fl_tmp_2 < 2) {
                _fl_tmp_2 = (_fl_tmp_2 + 1);
                fl_println(fl_string_from_cstr("retry attempt"));
                _fl_exception_push((&_fl_ef_0));
                if (setjmp(_fl_ef_0.jmp) == 0) {
                    fl_int val = fl_tests_exception_retry_test_parse_value(fl_string_from_cstr("bad"));
                    FL_String* _fl_tmp_4 = fl_string_from_cstr("got: ");
                    FL_String* _fl_tmp_5 = fl_string_concat(_fl_tmp_4, fl_int_to_string(val));
                    fl_string_release(_fl_tmp_4);
                    fl_println(_fl_tmp_5);
                    _fl_exception_pop();
                    goto _fl_tmp_3;
                } else {
                    _fl_exception_pop();
                    ex = ((FL_String*)_fl_ef_0.exception);
                }
            }
            fl_println(fl_string_from_cstr("retries exhausted, caught"));
_fl_tmp_3:;
            _fl_ef_0_caught = fl_true;
        }
    }
    fl_println(fl_string_from_cstr("finally after retry"));
    if (!_fl_ef_0_caught) {
        _fl_throw(_fl_ef_0.exception, _fl_ef_0.exception_tag);
    }
    fl_println(fl_string_from_cstr("done"));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_exception_retry_test_main();
    return 0;
}
