/* Generated by reflowc - do not edit */
/* Source: tests/programs/exception_finally_test.reflow */
#include "reflow_runtime.h"

/* ReFlow: tests.exception_finally_test.main */
void rf_tests_exception_finally_test_main(void) {
    RF_ExceptionFrame _rf_ef_0;
    rf_bool _rf_ef_0_caught = rf_true;
    _rf_exception_push((&_rf_ef_0));
    if (setjmp(_rf_ef_0.jmp) == 0) {
        rf_println(rf_string_from_cstr("no error"));
        _rf_exception_pop();
    } else {
        _rf_exception_pop();
        _rf_ef_0_caught = rf_false;
    }
    rf_println(rf_string_from_cstr("finally 1"));
    if (!_rf_ef_0_caught) {
        _rf_throw(_rf_ef_0.exception, _rf_ef_0.exception_tag);
    }
    RF_ExceptionFrame _rf_ef_1;
    rf_bool _rf_ef_1_caught = rf_true;
    _rf_exception_push((&_rf_ef_1));
    if (setjmp(_rf_ef_1.jmp) == 0) {
        _rf_throw(((void*)rf_string_from_cstr("boom")), 0);
        _rf_exception_pop();
    } else {
        _rf_exception_pop();
        _rf_ef_1_caught = rf_false;
        if (_rf_ef_1.exception_tag == 0) {
            RF_String* ex = ((RF_String*)_rf_ef_1.exception);
            rf_println(rf_string_from_cstr("caught boom"));
            _rf_ef_1_caught = rf_true;
        }
    }
    rf_println(rf_string_from_cstr("finally 2"));
    if (!_rf_ef_1_caught) {
        _rf_throw(_rf_ef_1.exception, _rf_ef_1.exception_tag);
    }
    RF_ExceptionFrame _rf_ef_2;
    _rf_exception_push((&_rf_ef_2));
    if (setjmp(_rf_ef_2.jmp) == 0) {
        RF_ExceptionFrame _rf_ef_3;
        _rf_exception_push((&_rf_ef_3));
        if (setjmp(_rf_ef_3.jmp) == 0) {
            _rf_throw(((void*)rf_string_from_cstr("inner")), 0);
            _rf_exception_pop();
        } else {
            _rf_exception_pop();
            if (_rf_ef_3.exception_tag == 0) {
                RF_String* ex = ((RF_String*)_rf_ef_3.exception);
                rf_println(rf_string_from_cstr("inner caught"));
                _rf_throw(((void*)rf_string_from_cstr("outer")), 0);
            } else {
                _rf_throw(_rf_ef_3.exception, _rf_ef_3.exception_tag);
            }
        }
        _rf_exception_pop();
    } else {
        _rf_exception_pop();
        if (_rf_ef_2.exception_tag == 0) {
            RF_String* ex = ((RF_String*)_rf_ef_2.exception);
            rf_println(rf_string_from_cstr("outer caught"));
        } else {
            _rf_throw(_rf_ef_2.exception, _rf_ef_2.exception_tag);
        }
    }
    RF_ExceptionFrame _rf_ef_4;
    _rf_exception_push((&_rf_ef_4));
    if (setjmp(_rf_ef_4.jmp) == 0) {
        RF_ExceptionFrame _rf_ef_5;
        rf_bool _rf_ef_5_caught = rf_true;
        _rf_exception_push((&_rf_ef_5));
        if (setjmp(_rf_ef_5.jmp) == 0) {
            _rf_throw(((void*)rf_string_from_cstr("propagated")), 0);
            _rf_exception_pop();
        } else {
            _rf_exception_pop();
            _rf_ef_5_caught = rf_false;
        }
        rf_println(rf_string_from_cstr("inner finally"));
        if (!_rf_ef_5_caught) {
            _rf_throw(_rf_ef_5.exception, _rf_ef_5.exception_tag);
        }
        _rf_exception_pop();
    } else {
        _rf_exception_pop();
        if (_rf_ef_4.exception_tag == 0) {
            RF_String* ex = ((RF_String*)_rf_ef_4.exception);
            rf_println(rf_string_from_cstr("outer caught propagated"));
        } else {
            _rf_throw(_rf_ef_4.exception, _rf_ef_4.exception_tag);
        }
    }
    rf_println(rf_string_from_cstr("all done"));
}

/* Entry point */
int main(int argc, char** argv) {
    _rf_runtime_init(argc, argv);
    rf_tests_exception_finally_test_main();
    return 0;
}
