/* Generated by flowc - do not edit */
/* Source: tests/programs/if_let_test.flow */
#include "flow_runtime.h"

typedef struct FL_Result_fl_int_FL_String_ptr FL_Result_fl_int_FL_String_ptr;

FL_Option_int fl_tests_if_let_test_find_positive(fl_int x);

FL_Result_fl_int_FL_String_ptr fl_tests_if_let_test_safe_divide(fl_int a, fl_int b);

void fl_tests_if_let_test_main(void);

struct FL_Result_fl_int_FL_String_ptr {
    fl_byte tag;
    fl_int ok_val;
    FL_String* err_val;
};

/* Flow: tests.if_let_test.find_positive */
FL_Option_int fl_tests_if_let_test_find_positive(fl_int x) {
    if (x > 0) {
        return (FL_Option_int){.tag = 1, .value = x};
    }
    return (FL_Option_int){.tag = 0};
}

/* Flow: tests.if_let_test.safe_divide */
FL_Result_fl_int_FL_String_ptr fl_tests_if_let_test_safe_divide(fl_int a, fl_int b) {
    if (b == 0) {
        return (FL_Result_fl_int_FL_String_ptr){.tag = 1, .err_val = fl_string_from_cstr("division by zero")};
    }
    fl_int _fl_e_1;
    FL_CHECKED_DIV(a, b, &_fl_e_1);
    return (FL_Result_fl_int_FL_String_ptr){.tag = 0, .ok_val = _fl_e_1};
}

/* Flow: tests.if_let_test.main */
void fl_tests_if_let_test_main(void) {
    FL_Option_int _fl_tmp_0 = fl_tests_if_let_test_find_positive(42);
    if (_fl_tmp_0.tag == 1) {
        fl_int v = _fl_tmp_0.value;
        FL_String* _fl_tmp_1 = fl_string_from_cstr("found: ");
        fl_println(fl_string_concat(_fl_tmp_1, fl_int_to_string(v)));
    }
    FL_Option_int _fl_tmp_2 = fl_tests_if_let_test_find_positive((-5));
    if (_fl_tmp_2.tag == 1) {
        fl_int v = _fl_tmp_2.value;
        FL_String* _fl_tmp_3 = fl_string_from_cstr("found: ");
        fl_println(fl_string_concat(_fl_tmp_3, fl_int_to_string(v)));
    } else {
        fl_println(fl_string_from_cstr("not found"));
    }
    FL_Result_fl_int_FL_String_ptr _fl_tmp_4 = fl_tests_if_let_test_safe_divide(10, 2);
    if (_fl_tmp_4.tag == 0) {
        fl_int v = _fl_tmp_4.ok_val;
        FL_String* _fl_tmp_5 = fl_string_from_cstr("divided: ");
        fl_println(fl_string_concat(_fl_tmp_5, fl_int_to_string(v)));
    } else {
        FL_String* _ = _fl_tmp_4.err_val;
    }
    FL_Result_fl_int_FL_String_ptr _fl_tmp_6 = fl_tests_if_let_test_safe_divide(10, 0);
    if (_fl_tmp_6.tag == 0) {
        fl_int v = _fl_tmp_6.ok_val;
        FL_String* _fl_tmp_7 = fl_string_from_cstr("divided: ");
        fl_println(fl_string_concat(_fl_tmp_7, fl_int_to_string(v)));
    } else {
        FL_String* _ = _fl_tmp_6.err_val;
        fl_println(fl_string_from_cstr("division failed"));
    }
    FL_Result_fl_int_FL_String_ptr _fl_tmp_8 = fl_tests_if_let_test_safe_divide(10, 0);
    if (_fl_tmp_8.tag == 0) {
        fl_int _ = _fl_tmp_8.ok_val;
    } else {
        FL_String* e = _fl_tmp_8.err_val;
        FL_String* _fl_tmp_9 = fl_string_from_cstr("error: ");
        fl_println(fl_string_concat(_fl_tmp_9, e));
    }
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_if_let_test_main();
    return 0;
}
