/* Generated by flowc - do not edit */
/* Source: tests/programs/lambda_basic.flow */
#include "flow_runtime.h"

fl_int _fl_clfn_tests_lambda_basic_main_0(void* _env, fl_int x);

fl_int _fl_clfn_tests_lambda_basic_main_1(void* _env, fl_int a, fl_int b);

void fl_tests_lambda_basic_main(void);

/* Flow: tests.lambda_basic.main::lambda0 */
fl_int _fl_clfn_tests_lambda_basic_main_0(void* _env, fl_int x) {
    fl_int _fl_e_1;
    FL_CHECKED_MUL(x, 2, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.lambda_basic.main::lambda1 */
fl_int _fl_clfn_tests_lambda_basic_main_1(void* _env, fl_int a, fl_int b) {
    fl_int _fl_e_1;
    FL_CHECKED_ADD(a, b, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.lambda_basic.main */
void fl_tests_lambda_basic_main(void) {
    FL_Closure* _fl_tmp_0 = ((FL_Closure*)malloc(sizeof(FL_Closure)));
    _fl_tmp_0->fn = ((void*)_fl_clfn_tests_lambda_basic_main_0);
    _fl_tmp_0->env = NULL;
    FL_Closure* dbl = _fl_tmp_0;
    FL_Closure* _fl_tmp_1 = dbl;
    fl_int result = ((fl_int (*)(void*, fl_int))_fl_tmp_1->fn)(_fl_tmp_1->env, 5);
    FL_String* _fl_tmp_2 = fl_string_from_cstr("dbl(5) = ");
    fl_println(fl_string_concat(_fl_tmp_2, fl_int_to_string(result)));
    FL_Closure* _fl_tmp_3 = ((FL_Closure*)malloc(sizeof(FL_Closure)));
    _fl_tmp_3->fn = ((void*)_fl_clfn_tests_lambda_basic_main_1);
    _fl_tmp_3->env = NULL;
    FL_Closure* add = _fl_tmp_3;
    FL_Closure* _fl_tmp_4 = add;
    fl_int sum = ((fl_int (*)(void*, fl_int, fl_int))_fl_tmp_4->fn)(_fl_tmp_4->env, 3, 7);
    FL_String* _fl_tmp_5 = fl_string_from_cstr("add(3, 7) = ");
    fl_println(fl_string_concat(_fl_tmp_5, fl_int_to_string(sum)));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_lambda_basic_main();
    return 0;
}
