/* Generated by flowc - do not edit */
/* Source: tests/programs/lambda_capture.flow */
#include "flow_runtime.h"

typedef struct _fl_closure_tests_lambda_capture_main_0 _fl_closure_tests_lambda_capture_main_0;

typedef struct _fl_closure_tests_lambda_capture_main_1 _fl_closure_tests_lambda_capture_main_1;

fl_int _fl_clfn_tests_lambda_capture_main_0(void* _env, fl_int x);

fl_int _fl_clfn_tests_lambda_capture_main_1(void* _env, fl_int x);

void fl_tests_lambda_capture_main(void);

struct _fl_closure_tests_lambda_capture_main_0 {
    fl_int y;
};

struct _fl_closure_tests_lambda_capture_main_1 {
    fl_int a;
    fl_int b;
};

/* Flow: tests.lambda_capture.main::lambda0 */
fl_int _fl_clfn_tests_lambda_capture_main_0(void* _env, fl_int x) {
    _fl_closure_tests_lambda_capture_main_0* _frame = ((_fl_closure_tests_lambda_capture_main_0*)_env);
    fl_int _fl_e_1;
    FL_CHECKED_ADD(x, _frame->y, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.lambda_capture.main::lambda1 */
fl_int _fl_clfn_tests_lambda_capture_main_1(void* _env, fl_int x) {
    _fl_closure_tests_lambda_capture_main_1* _frame = ((_fl_closure_tests_lambda_capture_main_1*)_env);
    fl_int _fl_e_2;
    FL_CHECKED_MUL(x, _frame->a, &_fl_e_2);
    fl_int _fl_e_1;
    FL_CHECKED_ADD(_fl_e_2, _frame->b, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.lambda_capture.main */
void fl_tests_lambda_capture_main(void) {
    fl_int y = 10;
    _fl_closure_tests_lambda_capture_main_0* _fl_tmp_0 = ((_fl_closure_tests_lambda_capture_main_0*)malloc(sizeof(_fl_closure_tests_lambda_capture_main_0)));
    _fl_tmp_0->y = y;
    FL_Closure* _fl_tmp_1 = ((FL_Closure*)malloc(sizeof(FL_Closure)));
    _fl_tmp_1->fn = ((void*)_fl_clfn_tests_lambda_capture_main_0);
    _fl_tmp_1->env = ((void*)_fl_tmp_0);
    FL_Closure* add_y = _fl_tmp_1;
    FL_Closure* _fl_tmp_2 = add_y;
    fl_int r1 = ((fl_int (*)(void*, fl_int))_fl_tmp_2->fn)(_fl_tmp_2->env, 5);
    FL_String* _fl_tmp_3 = fl_string_from_cstr("5 + 10 = ");
    fl_println(fl_string_concat(_fl_tmp_3, fl_int_to_string(r1)));
    fl_int a = 3;
    fl_int b = 4;
    _fl_closure_tests_lambda_capture_main_1* _fl_tmp_4 = ((_fl_closure_tests_lambda_capture_main_1*)malloc(sizeof(_fl_closure_tests_lambda_capture_main_1)));
    _fl_tmp_4->a = a;
    _fl_tmp_4->b = b;
    FL_Closure* _fl_tmp_5 = ((FL_Closure*)malloc(sizeof(FL_Closure)));
    _fl_tmp_5->fn = ((void*)_fl_clfn_tests_lambda_capture_main_1);
    _fl_tmp_5->env = ((void*)_fl_tmp_4);
    FL_Closure* compute = _fl_tmp_5;
    FL_Closure* _fl_tmp_6 = compute;
    fl_int r2 = ((fl_int (*)(void*, fl_int))_fl_tmp_6->fn)(_fl_tmp_6->env, 2);
    FL_String* _fl_tmp_7 = fl_string_from_cstr("2 * 3 + 4 = ");
    fl_println(fl_string_concat(_fl_tmp_7, fl_int_to_string(r2)));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_lambda_capture_main();
    return 0;
}
