/* Generated by flowc - do not edit */
/* Source: tests/programs/mono_assert.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        fl_string_retain(_fl_str_string_0);
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
        fl_string_release(_fl_tmp_2);
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

void fl_mono_assert_my_assert_eq__int(fl_int expected, fl_int actual, FL_String* msg);

void fl_mono_assert_my_assert_eq__string(FL_String* expected, FL_String* actual, FL_String* msg);

void fl_mono_assert_main(void);

FL_String* _fl_str_mono_assert_0 = NULL;

FL_String* _fl_str_mono_assert_1 = NULL;

FL_String* _fl_str_mono_assert_2 = NULL;

FL_String* _fl_str_mono_assert_3 = NULL;

FL_String* _fl_str_mono_assert_4 = NULL;

/* Flow: mono_assert.my_assert_eq[mono] */
void fl_mono_assert_my_assert_eq__int(fl_int expected, fl_int actual, FL_String* msg) {
    if (!(expected == actual)) {
        FL_String* _fl_tmp_0 = _fl_str_mono_assert_4;
        FL_String* _fl_tmp_1 = fl_string_concat(_fl_tmp_0, msg);
        fl_string_release(_fl_tmp_0);
        fl_eprintln(_fl_tmp_1);
        fl_sys_exit(1);
        fl_string_release(_fl_tmp_1);
    }
}

/* Flow: mono_assert.my_assert_eq[mono] */
void fl_mono_assert_my_assert_eq__string(FL_String* expected, FL_String* actual, FL_String* msg) {
    if (!fl_string_eq(expected, actual)) {
        FL_String* _fl_tmp_2 = _fl_str_mono_assert_4;
        FL_String* _fl_tmp_3 = fl_string_concat(_fl_tmp_2, msg);
        fl_string_release(_fl_tmp_2);
        fl_eprintln(_fl_tmp_3);
        fl_sys_exit(1);
        fl_string_release(_fl_tmp_3);
    }
}

/* Flow: mono_assert.main */
void fl_mono_assert_main(void) {
    fl_mono_assert_my_assert_eq__int(42, 42, _fl_str_mono_assert_0);
    fl_mono_assert_my_assert_eq__string(_fl_str_mono_assert_1, _fl_str_mono_assert_1, _fl_str_mono_assert_2);
    fl_println(_fl_str_mono_assert_3);
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_mono_assert_0 = fl_string_from_cstr("int equality");
    _fl_str_mono_assert_0->refcount = 2147483647;
    _fl_str_mono_assert_1 = fl_string_from_cstr("hello");
    _fl_str_mono_assert_1->refcount = 2147483647;
    _fl_str_mono_assert_2 = fl_string_from_cstr("string equality");
    _fl_str_mono_assert_2->refcount = 2147483647;
    _fl_str_mono_assert_3 = fl_string_from_cstr("all passed");
    _fl_str_mono_assert_3->refcount = 2147483647;
    _fl_str_mono_assert_4 = fl_string_from_cstr("FAIL: ");
    _fl_str_mono_assert_4->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_mono_assert_main();
    return 0;
}
