/* Generated by flowc - do not edit */
/* Source: tests/programs/mono_checked_add.flow */
#include "flow_runtime.h"

fl_int fl_mono_checked_add_add_generic__int(fl_int a, fl_int b);

fl_float fl_mono_checked_add_add_generic__float(fl_float a, fl_float b);

FL_String* fl_conv_to_string__int(fl_int val);

FL_String* fl_conv_to_string__float(fl_float val);

void fl_mono_checked_add_main(void);

/* Flow: mono_checked_add.add_generic[mono] */
fl_int fl_mono_checked_add_add_generic__int(fl_int a, fl_int b) {
    fl_int _fl_e_1;
    FL_CHECKED_ADD(a, b, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: mono_checked_add.add_generic[mono] */
fl_float fl_mono_checked_add_add_generic__float(fl_float a, fl_float b) {
    return (a + b);
}

/* Flow: conv.to_string[mono] */
FL_String* fl_conv_to_string__int(fl_int val) {
    return fl_int_to_string(val);
}

/* Flow: conv.to_string[mono] */
FL_String* fl_conv_to_string__float(fl_float val) {
    return fl_float_to_string(val);
}

/* Flow: mono_checked_add.main */
void fl_mono_checked_add_main(void) {
    fl_int x = fl_mono_checked_add_add_generic__int(3, 4);
    fl_float y = fl_mono_checked_add_add_generic__float(1.5, 2.5);
    fl_println(fl_conv_to_string__int(x));
    fl_println(fl_conv_to_string__float(y));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_mono_checked_add_main();
    return 0;
}
