/* Generated by flowc - do not edit */
/* Source: tests/programs/multi_main.flow */
#include "flow_runtime.h"

/* From: tests/programs/multi_helper.flow */

/* Flow: tests.programs.multi_helper.double */
fl_int fl_tests_programs_multi_helper_double(fl_int x) {
    fl_int _fl_e_1;
    FL_CHECKED_MUL(x, 2, &_fl_e_1);
    return _fl_e_1;
}

FL_String* fl_conv_to_string__int(fl_int val);

void fl_tests_programs_multi_main_main(void);

/* Flow: conv.to_string[mono] */
FL_String* fl_conv_to_string__int(fl_int val) {
    return fl_int_to_string(val);
}

/* Flow: tests.programs.multi_main.main */
void fl_tests_programs_multi_main_main(void) {
    fl_int result = fl_tests_programs_multi_helper_double(21);
    fl_println(fl_conv_to_string__int(result));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_programs_multi_main_main();
    return 0;
}
