/* Generated by flowc - do not edit */
/* Source: tests/programs/option_propagate_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        fl_string_retain(_fl_str_string_0);
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_string_release(_fl_tmp_2);
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

FL_Option_int fl_tests_option_propagate_test_find_positive(fl_int x);

FL_Option_int fl_tests_option_propagate_test_double_positive(fl_int x);

void fl_tests_option_propagate_test_main(void);

FL_String* _fl_str_tests_option_propagate_test_0 = NULL;

FL_String* _fl_str_tests_option_propagate_test_1 = NULL;

/* Flow: tests.option_propagate_test.find_positive */
FL_Option_int fl_tests_option_propagate_test_find_positive(fl_int x) {
    if (x > 0) {
        return (FL_Option_int){.tag = 1, .value = x};
    }
    return (FL_Option_int){.tag = 0};
}

/* Flow: tests.option_propagate_test.double_positive */
FL_Option_int fl_tests_option_propagate_test_double_positive(fl_int x) {
    FL_Option_int _fl_tmp_0 = fl_tests_option_propagate_test_find_positive(x);
    if (_fl_tmp_0.tag == 0) {
        return (FL_Option_int){.tag = 0};
    }
    fl_int _fl_tmp_1 = _fl_tmp_0.value;
    fl_int v = _fl_tmp_1;
    fl_int _fl_e_1;
    FL_CHECKED_MUL(v, 2, &_fl_e_1);
    return (FL_Option_int){.tag = 1, .value = _fl_e_1};
}

/* Flow: tests.option_propagate_test.main */
void fl_tests_option_propagate_test_main(void) {
    FL_Option_int _fl_tmp_2 = fl_tests_option_propagate_test_double_positive(5);
    if (_fl_tmp_2.tag == 1) {
        fl_int v = _fl_tmp_2.value;
        FL_String* _fl_tmp_3 = _fl_str_tests_option_propagate_test_0;
        FL_String* _fl_tmp_4 = fl_string_concat(_fl_tmp_3, fl_int_to_string(v));
        fl_string_release(_fl_tmp_3);
        fl_println(_fl_tmp_4);
    } else {
        fl_println(_fl_str_tests_option_propagate_test_1);
    }
    FL_Option_int _fl_tmp_5 = fl_tests_option_propagate_test_double_positive((-3));
    if (_fl_tmp_5.tag == 1) {
        fl_int v = _fl_tmp_5.value;
        FL_String* _fl_tmp_6 = _fl_str_tests_option_propagate_test_0;
        FL_String* _fl_tmp_7 = fl_string_concat(_fl_tmp_6, fl_int_to_string(v));
        fl_string_release(_fl_tmp_6);
        fl_println(_fl_tmp_7);
    } else {
        fl_println(_fl_str_tests_option_propagate_test_1);
    }
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_tests_option_propagate_test_0 = fl_string_from_cstr("result: ");
    _fl_str_tests_option_propagate_test_0->refcount = 2147483647;
    _fl_str_tests_option_propagate_test_1 = fl_string_from_cstr("none");
    _fl_str_tests_option_propagate_test_1->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_tests_option_propagate_test_main();
    return 0;
}
