/* Generated by flowc - do not edit */
/* Source: tests/programs/parallel_fanout_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_string_release(_fl_tmp_2);
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

fl_int fl_tests_parallel_fanout_test_double(fl_int x);

fl_int fl_tests_parallel_fanout_test_square(fl_int x);

fl_int fl_tests_parallel_fanout_test_add(fl_int a, fl_int b);

FL_String* fl_tests_parallel_fanout_test_greet(FL_String* s);

FL_String* fl_tests_parallel_fanout_test_shout(FL_String* s);

FL_String* fl_tests_parallel_fanout_test_both(FL_String* a, FL_String* b);

void* _fl_fanout_tests_parallel_fanout_test_main_0_0(void* _arg);

void* _fl_fanout_tests_parallel_fanout_test_main_0_1(void* _arg);

void* _fl_fanout_tests_parallel_fanout_test_main_1_0(void* _arg);

void* _fl_fanout_tests_parallel_fanout_test_main_1_1(void* _arg);

void fl_tests_parallel_fanout_test_main(void);

FL_String* _fl_str_tests_parallel_fanout_test_0 = NULL;

FL_String* _fl_str_tests_parallel_fanout_test_1 = NULL;

FL_String* _fl_str_tests_parallel_fanout_test_2 = NULL;

FL_String* _fl_str_tests_parallel_fanout_test_3 = NULL;

FL_String* _fl_str_tests_parallel_fanout_test_4 = NULL;

FL_String* _fl_str_tests_parallel_fanout_test_5 = NULL;

/* Flow: tests.parallel_fanout_test.double */
fl_int fl_tests_parallel_fanout_test_double(fl_int x) {
    fl_int _fl_e_1;
    FL_CHECKED_MUL(x, 2, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.parallel_fanout_test.square */
fl_int fl_tests_parallel_fanout_test_square(fl_int x) {
    fl_int _fl_e_1;
    FL_CHECKED_MUL(x, x, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.parallel_fanout_test.add */
fl_int fl_tests_parallel_fanout_test_add(fl_int a, fl_int b) {
    fl_int _fl_e_1;
    FL_CHECKED_ADD(a, b, &_fl_e_1);
    return _fl_e_1;
}

/* Flow: tests.parallel_fanout_test.greet */
FL_String* fl_tests_parallel_fanout_test_greet(FL_String* s) {
    FL_String* _fl_tmp_0 = _fl_str_tests_parallel_fanout_test_0;
    FL_String* _fl_tmp_1 = fl_string_concat(_fl_tmp_0, s);
    FL_String* _fl_tmp_2 = fl_string_concat(_fl_tmp_1, _fl_str_tests_parallel_fanout_test_1);
    fl_string_release(_fl_tmp_0);
    fl_string_release(_fl_tmp_1);
    return _fl_tmp_2;
}

/* Flow: tests.parallel_fanout_test.shout */
FL_String* fl_tests_parallel_fanout_test_shout(FL_String* s) {
    FL_String* _fl_tmp_3 = s;
    FL_String* _fl_tmp_4 = fl_string_concat(_fl_tmp_3, _fl_str_tests_parallel_fanout_test_2);
    fl_string_release(_fl_tmp_3);
    return _fl_tmp_4;
}

/* Flow: tests.parallel_fanout_test.both */
FL_String* fl_tests_parallel_fanout_test_both(FL_String* a, FL_String* b) {
    FL_String* _fl_tmp_5 = a;
    FL_String* _fl_tmp_6 = fl_string_concat(_fl_tmp_5, _fl_str_tests_parallel_fanout_test_3);
    FL_String* _fl_tmp_7 = fl_string_concat(_fl_tmp_6, b);
    fl_string_release(_fl_tmp_5);
    fl_string_release(_fl_tmp_6);
    return _fl_tmp_7;
}

/* Flow: tests.parallel_fanout_test.main::fanout_0_0 */
void* _fl_fanout_tests_parallel_fanout_test_main_0_0(void* _arg) {
    return ((void*)((fl_int64)fl_tests_parallel_fanout_test_double(((fl_int)((fl_int64)_arg)))));
}

/* Flow: tests.parallel_fanout_test.main::fanout_0_1 */
void* _fl_fanout_tests_parallel_fanout_test_main_0_1(void* _arg) {
    return ((void*)((fl_int64)fl_tests_parallel_fanout_test_square(((fl_int)((fl_int64)_arg)))));
}

/* Flow: tests.parallel_fanout_test.main::fanout_1_0 */
void* _fl_fanout_tests_parallel_fanout_test_main_1_0(void* _arg) {
    return ((void*)fl_tests_parallel_fanout_test_greet(((FL_String*)_arg)));
}

/* Flow: tests.parallel_fanout_test.main::fanout_1_1 */
void* _fl_fanout_tests_parallel_fanout_test_main_1_1(void* _arg) {
    return ((void*)fl_tests_parallel_fanout_test_shout(((FL_String*)_arg)));
}

/* Flow: tests.parallel_fanout_test.main */
void fl_tests_parallel_fanout_test_main(void) {
    fl_int _fl_tmp_8 = 5;
    FL_FanoutBranch _fl_tmp_9[2];
    _fl_tmp_9[0].fn = _fl_fanout_tests_parallel_fanout_test_main_0_0;
    _fl_tmp_9[0].arg = ((void*)((fl_int64)_fl_tmp_8));
    _fl_tmp_9[1].fn = _fl_fanout_tests_parallel_fanout_test_main_0_1;
    _fl_tmp_9[1].arg = ((void*)((fl_int64)_fl_tmp_8));
    fl_fanout_run(_fl_tmp_9, 2);
    fl_int _fl_tmp_10 = ((fl_int)((fl_int64)_fl_tmp_9[0].result));
    fl_int _fl_tmp_11 = ((fl_int)((fl_int64)_fl_tmp_9[1].result));
    fl_int _fl_tmp_12 = _fl_tmp_10;
    fl_int _fl_tmp_13 = _fl_tmp_11;
    fl_int r1 = fl_tests_parallel_fanout_test_add(_fl_tmp_12, _fl_tmp_13);
    FL_String* _fl_tmp_14 = _fl_str_tests_parallel_fanout_test_4;
    FL_String* _fl_tmp_15 = fl_string_concat(_fl_tmp_14, fl_int_to_string(r1));
    fl_string_release(_fl_tmp_14);
    fl_println(_fl_tmp_15);
    FL_String* _fl_tmp_16 = _fl_str_tests_parallel_fanout_test_5;
    FL_FanoutBranch _fl_tmp_17[2];
    _fl_tmp_17[0].fn = _fl_fanout_tests_parallel_fanout_test_main_1_0;
    _fl_tmp_17[0].arg = ((void*)_fl_tmp_16);
    _fl_tmp_17[1].fn = _fl_fanout_tests_parallel_fanout_test_main_1_1;
    _fl_tmp_17[1].arg = ((void*)_fl_tmp_16);
    fl_fanout_run(_fl_tmp_17, 2);
    FL_String* _fl_tmp_18 = ((FL_String*)_fl_tmp_17[0].result);
    FL_String* _fl_tmp_19 = ((FL_String*)_fl_tmp_17[1].result);
    FL_String* _fl_tmp_20 = _fl_tmp_18;
    FL_String* _fl_tmp_21 = _fl_tmp_19;
    FL_String* r2 = fl_tests_parallel_fanout_test_both(_fl_tmp_20, _fl_tmp_21);
    fl_string_retain(r2);
    fl_println(r2);
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_tests_parallel_fanout_test_0 = fl_string_from_cstr("Hello, ");
    _fl_str_tests_parallel_fanout_test_0->refcount = 2147483647;
    _fl_str_tests_parallel_fanout_test_1 = fl_string_from_cstr("!");
    _fl_str_tests_parallel_fanout_test_1->refcount = 2147483647;
    _fl_str_tests_parallel_fanout_test_2 = fl_string_from_cstr("!!!");
    _fl_str_tests_parallel_fanout_test_2->refcount = 2147483647;
    _fl_str_tests_parallel_fanout_test_3 = fl_string_from_cstr(" and ");
    _fl_str_tests_parallel_fanout_test_3->refcount = 2147483647;
    _fl_str_tests_parallel_fanout_test_4 = fl_string_from_cstr("parallel: ");
    _fl_str_tests_parallel_fanout_test_4->refcount = 2147483647;
    _fl_str_tests_parallel_fanout_test_5 = fl_string_from_cstr("hello");
    _fl_str_tests_parallel_fanout_test_5->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_tests_parallel_fanout_test_main();
    return 0;
}
