/* Generated by flowc - do not edit */
/* Source: tests/programs/recursive_sum.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

typedef struct fl_tests_recursive_sum_Tree_Leaf fl_tests_recursive_sum_Tree_Leaf;

typedef struct fl_tests_recursive_sum_Tree_Node fl_tests_recursive_sum_Tree_Node;

typedef struct fl_tests_recursive_sum_Tree fl_tests_recursive_sum_Tree;

fl_int fl_tests_recursive_sum_sum_tree(fl_tests_recursive_sum_Tree t);

void fl_tests_recursive_sum_main(void);

struct fl_tests_recursive_sum_Tree_Leaf {
    fl_int value;
};

struct fl_tests_recursive_sum_Tree_Node {
    fl_tests_recursive_sum_Tree* left;
    fl_tests_recursive_sum_Tree* right;
};

struct fl_tests_recursive_sum_Tree {
    fl_byte tag;
    fl_tests_recursive_sum_Tree_Leaf Leaf;
    fl_tests_recursive_sum_Tree_Node Node;
};

/* Flow: tests.recursive_sum.sum_tree */
fl_int fl_tests_recursive_sum_sum_tree(fl_tests_recursive_sum_Tree t) {
    fl_tests_recursive_sum_Tree _fl_tmp_0 = t;
    switch (_fl_tmp_0.tag) {
        case 0: {
            fl_int v = _fl_tmp_0.Leaf.value;
            return v;
            break;
        }
        case 1: {
            fl_tests_recursive_sum_Tree l = (*_fl_tmp_0.Node.left);
            fl_tests_recursive_sum_Tree r = (*_fl_tmp_0.Node.right);
            fl_int _fl_e_1;
            FL_CHECKED_ADD(fl_tests_recursive_sum_sum_tree(l), fl_tests_recursive_sum_sum_tree(r), &_fl_e_1);
            return _fl_e_1;
            break;
        }
    }
}

/* Flow: tests.recursive_sum.main */
void fl_tests_recursive_sum_main(void) {
    fl_tests_recursive_sum_Tree* _fl_tmp_1 = ((fl_tests_recursive_sum_Tree*)malloc(sizeof(fl_tests_recursive_sum_Tree)));
    (*_fl_tmp_1) = (fl_tests_recursive_sum_Tree){.tag = 0, .Leaf = (fl_tests_recursive_sum_Tree_Leaf){.value = 1}};
    fl_tests_recursive_sum_Tree* _fl_tmp_2 = ((fl_tests_recursive_sum_Tree*)malloc(sizeof(fl_tests_recursive_sum_Tree)));
    (*_fl_tmp_2) = (fl_tests_recursive_sum_Tree){.tag = 0, .Leaf = (fl_tests_recursive_sum_Tree_Leaf){.value = 2}};
    fl_tests_recursive_sum_Tree* _fl_tmp_3 = ((fl_tests_recursive_sum_Tree*)malloc(sizeof(fl_tests_recursive_sum_Tree)));
    (*_fl_tmp_3) = (fl_tests_recursive_sum_Tree){.tag = 1, .Node = (fl_tests_recursive_sum_Tree_Node){.left = _fl_tmp_1, .right = _fl_tmp_2}};
    fl_tests_recursive_sum_Tree* _fl_tmp_4 = ((fl_tests_recursive_sum_Tree*)malloc(sizeof(fl_tests_recursive_sum_Tree)));
    (*_fl_tmp_4) = (fl_tests_recursive_sum_Tree){.tag = 0, .Leaf = (fl_tests_recursive_sum_Tree_Leaf){.value = 3}};
    fl_tests_recursive_sum_Tree tree = (fl_tests_recursive_sum_Tree){.tag = 1, .Node = (fl_tests_recursive_sum_Tree_Node){.left = _fl_tmp_3, .right = _fl_tmp_4}};
    FL_String* _fl_tmp_5 = fl_string_from_cstr("Sum: ");
    FL_String* _fl_tmp_6 = fl_string_concat(_fl_tmp_5, fl_int_to_string(fl_tests_recursive_sum_sum_tree(tree)));
    fl_string_release(_fl_tmp_5);
    fl_println(_fl_tmp_6);
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_recursive_sum_main();
    return 0;
}
