/* Generated by reflowc - do not edit */
/* Source: tests/programs/recursive_expr.reflow */
#include "reflow_runtime.h"

typedef struct rf_tests_recursive_expr_Expr_Lit rf_tests_recursive_expr_Expr_Lit;

typedef struct rf_tests_recursive_expr_Expr_Add rf_tests_recursive_expr_Expr_Add;

typedef struct rf_tests_recursive_expr_Expr_Neg rf_tests_recursive_expr_Expr_Neg;

typedef struct rf_tests_recursive_expr_Expr rf_tests_recursive_expr_Expr;

rf_int rf_tests_recursive_expr_eval(rf_tests_recursive_expr_Expr e);

void rf_tests_recursive_expr_main(void);

struct rf_tests_recursive_expr_Expr_Lit {
    rf_int value;
};

struct rf_tests_recursive_expr_Expr_Add {
    rf_tests_recursive_expr_Expr* left;
    rf_tests_recursive_expr_Expr* right;
};

struct rf_tests_recursive_expr_Expr_Neg {
    rf_tests_recursive_expr_Expr* inner;
};

struct rf_tests_recursive_expr_Expr {
    rf_byte tag;
    rf_tests_recursive_expr_Expr_Lit Lit;
    rf_tests_recursive_expr_Expr_Add Add;
    rf_tests_recursive_expr_Expr_Neg Neg;
};

/* ReFlow: tests.recursive_expr.eval */
rf_int rf_tests_recursive_expr_eval(rf_tests_recursive_expr_Expr e) {
    rf_tests_recursive_expr_Expr _rf_tmp_0 = e;
    switch (_rf_tmp_0.tag) {
        case 0:
            rf_int v = _rf_tmp_0.Lit.value;
            return v;
            break;
        case 1:
            rf_tests_recursive_expr_Expr l = (*_rf_tmp_0.Add.left);
            rf_tests_recursive_expr_Expr r = (*_rf_tmp_0.Add.right);
            rf_int _rf_e_1;
            RF_CHECKED_ADD(rf_tests_recursive_expr_eval(l), rf_tests_recursive_expr_eval(r), &_rf_e_1);
            return _rf_e_1;
            break;
        case 2:
            rf_tests_recursive_expr_Expr x = (*_rf_tmp_0.Neg.inner);
            rf_int _rf_e_2;
            RF_CHECKED_SUB(0, rf_tests_recursive_expr_eval(x), &_rf_e_2);
            return _rf_e_2;
            break;
    }
}

/* ReFlow: tests.recursive_expr.main */
void rf_tests_recursive_expr_main(void) {
    rf_tests_recursive_expr_Expr* _rf_tmp_1 = ((rf_tests_recursive_expr_Expr*)malloc(sizeof(rf_tests_recursive_expr_Expr)));
    (*_rf_tmp_1) = (rf_tests_recursive_expr_Expr){.tag = 0, .Lit = (rf_tests_recursive_expr_Expr_Lit){.value = 3}};
    rf_tests_recursive_expr_Expr* _rf_tmp_2 = ((rf_tests_recursive_expr_Expr*)malloc(sizeof(rf_tests_recursive_expr_Expr)));
    (*_rf_tmp_2) = (rf_tests_recursive_expr_Expr){.tag = 0, .Lit = (rf_tests_recursive_expr_Expr_Lit){.value = 4}};
    rf_tests_recursive_expr_Expr* _rf_tmp_3 = ((rf_tests_recursive_expr_Expr*)malloc(sizeof(rf_tests_recursive_expr_Expr)));
    (*_rf_tmp_3) = (rf_tests_recursive_expr_Expr){.tag = 1, .Add = (rf_tests_recursive_expr_Expr_Add){.left = _rf_tmp_1, .right = _rf_tmp_2}};
    rf_tests_recursive_expr_Expr* _rf_tmp_4 = ((rf_tests_recursive_expr_Expr*)malloc(sizeof(rf_tests_recursive_expr_Expr)));
    (*_rf_tmp_4) = (rf_tests_recursive_expr_Expr){.tag = 0, .Lit = (rf_tests_recursive_expr_Expr_Lit){.value = 10}};
    rf_tests_recursive_expr_Expr* _rf_tmp_5 = ((rf_tests_recursive_expr_Expr*)malloc(sizeof(rf_tests_recursive_expr_Expr)));
    (*_rf_tmp_5) = (rf_tests_recursive_expr_Expr){.tag = 2, .Neg = (rf_tests_recursive_expr_Expr_Neg){.inner = _rf_tmp_3}};
    rf_tests_recursive_expr_Expr e = (rf_tests_recursive_expr_Expr){.tag = 1, .Add = (rf_tests_recursive_expr_Expr_Add){.left = _rf_tmp_4, .right = _rf_tmp_5}};
    RF_String* _rf_tmp_6 = rf_string_from_cstr("Result: ");
    rf_println(rf_string_concat(_rf_tmp_6, rf_int_to_string(rf_tests_recursive_expr_eval(e))));
}

/* Entry point */
int main(int argc, char** argv) {
    _rf_runtime_init(argc, argv);
    rf_tests_recursive_expr_main();
    return 0;
}
