/* Generated by flowc - do not edit */
/* Source: tests/programs/recursive_expr.flow */
#include "flow_runtime.h"

typedef struct fl_tests_recursive_expr_Expr_Lit fl_tests_recursive_expr_Expr_Lit;

typedef struct fl_tests_recursive_expr_Expr_Add fl_tests_recursive_expr_Expr_Add;

typedef struct fl_tests_recursive_expr_Expr_Neg fl_tests_recursive_expr_Expr_Neg;

typedef struct fl_tests_recursive_expr_Expr fl_tests_recursive_expr_Expr;

fl_int fl_tests_recursive_expr_eval(fl_tests_recursive_expr_Expr e);

void fl_tests_recursive_expr_main(void);

struct fl_tests_recursive_expr_Expr_Lit {
    fl_int value;
};

struct fl_tests_recursive_expr_Expr_Add {
    fl_tests_recursive_expr_Expr* left;
    fl_tests_recursive_expr_Expr* right;
};

struct fl_tests_recursive_expr_Expr_Neg {
    fl_tests_recursive_expr_Expr* inner;
};

struct fl_tests_recursive_expr_Expr {
    fl_byte tag;
    fl_tests_recursive_expr_Expr_Lit Lit;
    fl_tests_recursive_expr_Expr_Add Add;
    fl_tests_recursive_expr_Expr_Neg Neg;
};

/* Flow: tests.recursive_expr.eval */
fl_int fl_tests_recursive_expr_eval(fl_tests_recursive_expr_Expr e) {
    fl_tests_recursive_expr_Expr _fl_tmp_0 = e;
    switch (_fl_tmp_0.tag) {
        case 0:
            fl_int v = _fl_tmp_0.Lit.value;
            return v;
            break;
        case 1:
            fl_tests_recursive_expr_Expr l = (*_fl_tmp_0.Add.left);
            fl_tests_recursive_expr_Expr r = (*_fl_tmp_0.Add.right);
            fl_int _fl_e_1;
            FL_CHECKED_ADD(fl_tests_recursive_expr_eval(l), fl_tests_recursive_expr_eval(r), &_fl_e_1);
            return _fl_e_1;
            break;
        case 2:
            fl_tests_recursive_expr_Expr x = (*_fl_tmp_0.Neg.inner);
            fl_int _fl_e_2;
            FL_CHECKED_SUB(0, fl_tests_recursive_expr_eval(x), &_fl_e_2);
            return _fl_e_2;
            break;
    }
}

/* Flow: tests.recursive_expr.main */
void fl_tests_recursive_expr_main(void) {
    fl_tests_recursive_expr_Expr* _fl_tmp_1 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_1) = (fl_tests_recursive_expr_Expr){.tag = 0, .Lit = (fl_tests_recursive_expr_Expr_Lit){.value = 3}};
    fl_tests_recursive_expr_Expr* _fl_tmp_2 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_2) = (fl_tests_recursive_expr_Expr){.tag = 0, .Lit = (fl_tests_recursive_expr_Expr_Lit){.value = 4}};
    fl_tests_recursive_expr_Expr* _fl_tmp_3 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_3) = (fl_tests_recursive_expr_Expr){.tag = 1, .Add = (fl_tests_recursive_expr_Expr_Add){.left = _fl_tmp_1, .right = _fl_tmp_2}};
    fl_tests_recursive_expr_Expr* _fl_tmp_4 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_4) = (fl_tests_recursive_expr_Expr){.tag = 0, .Lit = (fl_tests_recursive_expr_Expr_Lit){.value = 10}};
    fl_tests_recursive_expr_Expr* _fl_tmp_5 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_5) = (fl_tests_recursive_expr_Expr){.tag = 2, .Neg = (fl_tests_recursive_expr_Expr_Neg){.inner = _fl_tmp_3}};
    fl_tests_recursive_expr_Expr e = (fl_tests_recursive_expr_Expr){.tag = 1, .Add = (fl_tests_recursive_expr_Expr_Add){.left = _fl_tmp_4, .right = _fl_tmp_5}};
    FL_String* _fl_tmp_6 = fl_string_from_cstr("Result: ");
    fl_println(fl_string_concat(_fl_tmp_6, fl_int_to_string(fl_tests_recursive_expr_eval(e))));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_recursive_expr_main();
    return 0;
}
