/* Generated by flowc - do not edit */
/* Source: tests/programs/recursive_expr.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        fl_string_retain(_fl_str_string_0);
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_string_release(_fl_tmp_2);
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

typedef struct fl_tests_recursive_expr_Expr_Lit fl_tests_recursive_expr_Expr_Lit;

typedef struct fl_tests_recursive_expr_Expr_Add fl_tests_recursive_expr_Expr_Add;

typedef struct fl_tests_recursive_expr_Expr_Neg fl_tests_recursive_expr_Expr_Neg;

typedef struct fl_tests_recursive_expr_Expr fl_tests_recursive_expr_Expr;

fl_int fl_tests_recursive_expr_eval(fl_tests_recursive_expr_Expr e);

void fl_tests_recursive_expr_main(void);

struct fl_tests_recursive_expr_Expr_Lit {
    fl_int value;
};

struct fl_tests_recursive_expr_Expr_Add {
    fl_tests_recursive_expr_Expr* left;
    fl_tests_recursive_expr_Expr* right;
};

struct fl_tests_recursive_expr_Expr_Neg {
    fl_tests_recursive_expr_Expr* inner;
};

struct fl_tests_recursive_expr_Expr {
    fl_byte tag;
    fl_tests_recursive_expr_Expr_Lit Lit;
    fl_tests_recursive_expr_Expr_Add Add;
    fl_tests_recursive_expr_Expr_Neg Neg;
};

FL_String* _fl_str_tests_recursive_expr_0 = NULL;

/* Flow: tests.recursive_expr.eval */
fl_int fl_tests_recursive_expr_eval(fl_tests_recursive_expr_Expr e) {
    fl_tests_recursive_expr_Expr _fl_tmp_0 = e;
    switch (_fl_tmp_0.tag) {
        case 0: {
            fl_int v = _fl_tmp_0.Lit.value;
            return v;
            break;
        }
        case 1: {
            fl_tests_recursive_expr_Expr l = (*_fl_tmp_0.Add.left);
            fl_tests_recursive_expr_Expr r = (*_fl_tmp_0.Add.right);
            fl_int _fl_e_1;
            FL_CHECKED_ADD(fl_tests_recursive_expr_eval(l), fl_tests_recursive_expr_eval(r), &_fl_e_1);
            return _fl_e_1;
            break;
        }
        case 2: {
            fl_tests_recursive_expr_Expr x = (*_fl_tmp_0.Neg.inner);
            fl_int _fl_e_2;
            FL_CHECKED_SUB(0, fl_tests_recursive_expr_eval(x), &_fl_e_2);
            return _fl_e_2;
            break;
        }
    }
}

/* Flow: tests.recursive_expr.main */
void fl_tests_recursive_expr_main(void) {
    fl_tests_recursive_expr_Expr* _fl_tmp_1 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_1) = (fl_tests_recursive_expr_Expr){.tag = 0, .Lit = (fl_tests_recursive_expr_Expr_Lit){.value = 3}};
    fl_tests_recursive_expr_Expr* _fl_tmp_2 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_2) = (fl_tests_recursive_expr_Expr){.tag = 0, .Lit = (fl_tests_recursive_expr_Expr_Lit){.value = 4}};
    fl_tests_recursive_expr_Expr* _fl_tmp_3 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_3) = (fl_tests_recursive_expr_Expr){.tag = 1, .Add = (fl_tests_recursive_expr_Expr_Add){.left = _fl_tmp_1, .right = _fl_tmp_2}};
    fl_tests_recursive_expr_Expr* _fl_tmp_4 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_4) = (fl_tests_recursive_expr_Expr){.tag = 0, .Lit = (fl_tests_recursive_expr_Expr_Lit){.value = 10}};
    fl_tests_recursive_expr_Expr* _fl_tmp_5 = ((fl_tests_recursive_expr_Expr*)malloc(sizeof(fl_tests_recursive_expr_Expr)));
    (*_fl_tmp_5) = (fl_tests_recursive_expr_Expr){.tag = 2, .Neg = (fl_tests_recursive_expr_Expr_Neg){.inner = _fl_tmp_3}};
    fl_tests_recursive_expr_Expr e = (fl_tests_recursive_expr_Expr){.tag = 1, .Add = (fl_tests_recursive_expr_Expr_Add){.left = _fl_tmp_4, .right = _fl_tmp_5}};
    FL_String* _fl_tmp_6 = fl_int_to_string(fl_tests_recursive_expr_eval(e));
    FL_String* _fl_tmp_7 = _fl_str_tests_recursive_expr_0;
    FL_String* _fl_tmp_8 = fl_string_concat(_fl_tmp_7, _fl_tmp_6);
    fl_string_release(_fl_tmp_6);
    fl_string_release(_fl_tmp_7);
    fl_println(_fl_tmp_8);
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_tests_recursive_expr_0 = fl_string_from_cstr("Result: ");
    _fl_str_tests_recursive_expr_0->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_tests_recursive_expr_main();
    return 0;
}
