/* Generated by flowc - do not edit */
/* Source: tests/programs/stdlib_net_smoke.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

/* Flow: stdlib_net_smoke.main */
void fl_stdlib_net_smoke_main(void) {
    FL_Option_ptr listener = fl_net_listen(fl_string_from_cstr("127.0.0.1"), 0);
    FL_Option_ptr _fl_tmp_0 = listener;
    if (_fl_tmp_0.tag == 1) {
        void* l = _fl_tmp_0.value;
        fl_println(fl_string_from_cstr("listen ok"));
        fl_net_close(l);
    } else {
        fl_println(fl_string_from_cstr("listen failed"));
    }
    fl_println(fl_string_from_cstr("done"));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_stdlib_net_smoke_main();
    return 0;
}
