/* Generated by flowc - do not edit */
/* Source: tests/programs/stdlib_string_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_old_2 = result;
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_2 != result) {
            fl_string_release(_fl_old_2);
        }
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

FL_String* _fl_str_tests_stdlib_string_test_0 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_1 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_2 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_3 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_4 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_5 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_6 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_7 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_8 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_9 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_10 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_11 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_12 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_13 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_14 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_15 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_16 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_17 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_18 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_19 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_20 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_21 = NULL;

FL_String* _fl_str_tests_stdlib_string_test_22 = NULL;

/* Flow: tests.stdlib_string_test.main */
void fl_tests_stdlib_string_test_main(void) {
    FL_String* s = _fl_str_tests_stdlib_string_test_0;
    fl_string_retain(s);
    FL_Option_char ch = fl_string_char_at(s, 0);
    FL_Option_char _fl_tmp_0 = ch;
    if (_fl_tmp_0.tag == 1) {
        fl_char c = _fl_tmp_0.value;
        FL_String* _fl_tmp_1 = _fl_str_tests_stdlib_string_test_1;
        FL_String* _fl_tmp_2 = fl_string_concat(_fl_tmp_1, fl_char_to_string(c));
        fl_string_release(_fl_tmp_1);
        fl_println(_fl_tmp_2);
    } else {
        fl_println(_fl_str_tests_stdlib_string_test_2);
    }
    FL_String* sub = fl_string_substring(s, 7, 12);
    FL_String* _fl_tmp_3 = _fl_str_tests_stdlib_string_test_3;
    FL_String* _fl_tmp_4 = fl_string_concat(_fl_tmp_3, sub);
    fl_string_release(_fl_tmp_3);
    fl_println(_fl_tmp_4);
    FL_Option_int idx = fl_string_index_of(s, _fl_str_tests_stdlib_string_test_4);
    FL_Option_int _fl_tmp_5 = idx;
    if (_fl_tmp_5.tag == 1) {
        fl_int i = _fl_tmp_5.value;
        FL_String* _fl_tmp_6 = _fl_str_tests_stdlib_string_test_5;
        FL_String* _fl_tmp_7 = fl_string_concat(_fl_tmp_6, fl_int_to_string(i));
        fl_string_release(_fl_tmp_6);
        fl_println(_fl_tmp_7);
    } else {
        fl_println(_fl_str_tests_stdlib_string_test_6);
    }
    FL_String* _fl_tmp_8 = _fl_str_tests_stdlib_string_test_7;
    FL_String* _fl_tmp_9 = fl_string_concat(_fl_tmp_8, fl_bool_to_string(fl_string_contains(s, _fl_str_tests_stdlib_string_test_4)));
    fl_string_release(_fl_tmp_8);
    fl_println(_fl_tmp_9);
    FL_String* _fl_tmp_10 = _fl_str_tests_stdlib_string_test_8;
    FL_String* _fl_tmp_11 = fl_string_concat(_fl_tmp_10, fl_bool_to_string(fl_string_starts_with(s, _fl_str_tests_stdlib_string_test_9)));
    fl_string_release(_fl_tmp_10);
    fl_println(_fl_tmp_11);
    FL_String* _fl_tmp_12 = _fl_str_tests_stdlib_string_test_10;
    FL_String* _fl_tmp_13 = fl_string_concat(_fl_tmp_12, fl_bool_to_string(fl_string_ends_with(s, _fl_str_tests_stdlib_string_test_11)));
    fl_string_release(_fl_tmp_12);
    fl_println(_fl_tmp_13);
    FL_String* lower = fl_string_to_lower(_fl_str_tests_stdlib_string_test_12);
    FL_String* _fl_tmp_14 = _fl_str_tests_stdlib_string_test_13;
    FL_String* _fl_tmp_15 = fl_string_concat(_fl_tmp_14, lower);
    fl_string_release(_fl_tmp_14);
    fl_println(_fl_tmp_15);
    FL_String* upper = fl_string_to_upper(_fl_str_tests_stdlib_string_test_14);
    FL_String* _fl_tmp_16 = _fl_str_tests_stdlib_string_test_15;
    FL_String* _fl_tmp_17 = fl_string_concat(_fl_tmp_16, upper);
    fl_string_release(_fl_tmp_16);
    fl_println(_fl_tmp_17);
    FL_String* trimmed = fl_string_trim(_fl_str_tests_stdlib_string_test_16);
    FL_String* _fl_tmp_18 = _fl_str_tests_stdlib_string_test_17;
    FL_String* _fl_tmp_19 = fl_string_concat(_fl_tmp_18, trimmed);
    FL_String* _fl_tmp_20 = fl_string_concat(_fl_tmp_19, _fl_str_tests_stdlib_string_test_18);
    fl_string_release(_fl_tmp_18);
    fl_string_release(_fl_tmp_19);
    fl_println(_fl_tmp_20);
    FL_String* replaced = fl_string_replace(_fl_str_tests_stdlib_string_test_19, _fl_str_tests_stdlib_string_test_20, _fl_str_tests_stdlib_string_test_21);
    FL_String* _fl_tmp_21 = _fl_str_tests_stdlib_string_test_22;
    FL_String* _fl_tmp_22 = fl_string_concat(_fl_tmp_21, replaced);
    fl_string_release(_fl_tmp_21);
    fl_println(_fl_tmp_22);
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_0 = fl_string_from_cstr("Hello, World!");
    _fl_str_tests_stdlib_string_test_0->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_1 = fl_string_from_cstr("char_at(0): ");
    _fl_str_tests_stdlib_string_test_1->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_2 = fl_string_from_cstr("char_at(0): none");
    _fl_str_tests_stdlib_string_test_2->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_3 = fl_string_from_cstr("substring(7,12): ");
    _fl_str_tests_stdlib_string_test_3->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_4 = fl_string_from_cstr("World");
    _fl_str_tests_stdlib_string_test_4->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_5 = fl_string_from_cstr("index_of World: ");
    _fl_str_tests_stdlib_string_test_5->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_6 = fl_string_from_cstr("index_of World: none");
    _fl_str_tests_stdlib_string_test_6->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_7 = fl_string_from_cstr("contains World: ");
    _fl_str_tests_stdlib_string_test_7->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_8 = fl_string_from_cstr("starts_with Hello: ");
    _fl_str_tests_stdlib_string_test_8->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_9 = fl_string_from_cstr("Hello");
    _fl_str_tests_stdlib_string_test_9->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_10 = fl_string_from_cstr("ends_with !: ");
    _fl_str_tests_stdlib_string_test_10->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_11 = fl_string_from_cstr("!");
    _fl_str_tests_stdlib_string_test_11->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_12 = fl_string_from_cstr("HELLO");
    _fl_str_tests_stdlib_string_test_12->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_13 = fl_string_from_cstr("to_lower: ");
    _fl_str_tests_stdlib_string_test_13->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_14 = fl_string_from_cstr("hello");
    _fl_str_tests_stdlib_string_test_14->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_15 = fl_string_from_cstr("to_upper: ");
    _fl_str_tests_stdlib_string_test_15->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_16 = fl_string_from_cstr("  hi  ");
    _fl_str_tests_stdlib_string_test_16->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_17 = fl_string_from_cstr("trim: [");
    _fl_str_tests_stdlib_string_test_17->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_18 = fl_string_from_cstr("]");
    _fl_str_tests_stdlib_string_test_18->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_19 = fl_string_from_cstr("aabaa");
    _fl_str_tests_stdlib_string_test_19->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_20 = fl_string_from_cstr("a");
    _fl_str_tests_stdlib_string_test_20->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_21 = fl_string_from_cstr("x");
    _fl_str_tests_stdlib_string_test_21->refcount = 2147483647;
    _fl_str_tests_stdlib_string_test_22 = fl_string_from_cstr("replace: ");
    _fl_str_tests_stdlib_string_test_22->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_tests_stdlib_string_test_main();
    return 0;
}
