/* Generated by flowc - do not edit */
/* Source: tests/programs/stdlib_io_test.flow */
#include "flow_runtime.h"

/* Flow: tests.stdlib_io_test.main */
void fl_tests_stdlib_io_test_main(void) {
    FL_String* tmp = fl_tmpfile_create(fl_string_from_cstr(".txt"), fl_string_from_cstr("hello from flow"));
    FL_Option_ptr contents = fl_read_file(tmp);
    FL_Option_ptr _fl_tmp_0 = contents;
    if (_fl_tmp_0.tag == 1) {
        FL_String* s = _fl_tmp_0.value;
        FL_String* _fl_tmp_1 = fl_string_from_cstr("read: ");
        fl_println(fl_string_concat(_fl_tmp_1, s));
    } else {
        fl_println(fl_string_from_cstr("read: none"));
    }
    fl_tmpfile_remove(tmp);
    FL_Option_ptr after = fl_read_file(tmp);
    FL_Option_ptr _fl_tmp_2 = after;
    if (_fl_tmp_2.tag == 1) {
        FL_String* s = _fl_tmp_2.value;
        FL_String* _fl_tmp_3 = fl_string_from_cstr("after remove: ");
        fl_println(fl_string_concat(_fl_tmp_3, s));
    } else {
        fl_println(fl_string_from_cstr("after remove: none"));
    }
    fl_bool wrote = fl_write_file(tmp, fl_string_from_cstr("overwrite test"));
    FL_String* _fl_tmp_4 = fl_string_from_cstr("write_file: ");
    fl_println(fl_string_concat(_fl_tmp_4, fl_bool_to_string(wrote)));
    FL_Option_ptr contents2 = fl_read_file(tmp);
    FL_Option_ptr _fl_tmp_5 = contents2;
    if (_fl_tmp_5.tag == 1) {
        FL_String* s = _fl_tmp_5.value;
        FL_String* _fl_tmp_6 = fl_string_from_cstr("read2: ");
        fl_println(fl_string_concat(_fl_tmp_6, s));
    } else {
        fl_println(fl_string_from_cstr("read2: none"));
    }
    fl_tmpfile_remove(tmp);
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_stdlib_io_test_main();
    return 0;
}
