/* Generated by flowc - do not edit */
/* Source: tests/programs/stdlib_char_test.flow */
#include "flow_runtime.h"

/* Flow: tests.stdlib_char_test.main */
void fl_tests_stdlib_char_test_main(void) {
    FL_String* _fl_tmp_0 = fl_string_from_cstr("is_digit '5': ");
    fl_println(fl_string_concat(_fl_tmp_0, fl_bool_to_string(fl_char_is_digit(53))));
    FL_String* _fl_tmp_1 = fl_string_from_cstr("is_digit 'a': ");
    fl_println(fl_string_concat(_fl_tmp_1, fl_bool_to_string(fl_char_is_digit(97))));
    FL_String* _fl_tmp_2 = fl_string_from_cstr("is_alpha 'Z': ");
    fl_println(fl_string_concat(_fl_tmp_2, fl_bool_to_string(fl_char_is_alpha(90))));
    FL_String* _fl_tmp_3 = fl_string_from_cstr("is_alpha '3': ");
    fl_println(fl_string_concat(_fl_tmp_3, fl_bool_to_string(fl_char_is_alpha(51))));
    FL_String* _fl_tmp_4 = fl_string_from_cstr("is_alphanumeric 'a': ");
    fl_println(fl_string_concat(_fl_tmp_4, fl_bool_to_string(fl_char_is_alphanumeric(97))));
    FL_String* _fl_tmp_5 = fl_string_from_cstr("is_alphanumeric '!': ");
    fl_println(fl_string_concat(_fl_tmp_5, fl_bool_to_string(fl_char_is_alphanumeric(33))));
    FL_String* _fl_tmp_6 = fl_string_from_cstr("is_whitespace ' ': ");
    fl_println(fl_string_concat(_fl_tmp_6, fl_bool_to_string(fl_char_is_whitespace(32))));
    FL_String* _fl_tmp_7 = fl_string_from_cstr("is_whitespace 'x': ");
    fl_println(fl_string_concat(_fl_tmp_7, fl_bool_to_string(fl_char_is_whitespace(120))));
    FL_String* _fl_tmp_8 = fl_string_from_cstr("to_code 'A': ");
    fl_println(fl_string_concat(_fl_tmp_8, fl_int_to_string(fl_char_to_int(65))));
    fl_char ch = fl_int_to_char(66);
    FL_String* _fl_tmp_9 = fl_string_from_cstr("from_code 66: ");
    fl_println(fl_string_concat(_fl_tmp_9, fl_char_to_string(ch)));
    FL_String* _fl_tmp_10 = fl_string_from_cstr("to_string 'R': ");
    fl_println(fl_string_concat(_fl_tmp_10, fl_char_to_string(82)));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_stdlib_char_test_main();
    return 0;
}
