/* Generated by flowc - do not edit */
/* Source: tests/programs/stdlib_generic_sort.flow */
#include "flow_runtime.h"

FL_Array* fl_sort_sort__int(FL_Array* arr);

FL_Array* fl_sort_sort__string(FL_Array* arr);

FL_String* fl_conv_to_string__int(fl_int val);

void fl_stdlib_generic_sort_main(void);

fl_int _fl_clfn_sort_sort_0(void* _env, fl_int a, fl_int b);

fl_int _fl_srtwrap_sort_sort_1(void* _env, void* _a, void* _b);

fl_int _fl_clfn_sort_sort_2(void* _env, FL_String* a, FL_String* b);

fl_int _fl_srtwrap_sort_sort_3(void* _env, void* _a, void* _b);

/* Flow: sort.sort[mono] */
FL_Array* fl_sort_sort__int(FL_Array* arr) {
    FL_Closure* _fl_tmp_2 = ((FL_Closure*)malloc(sizeof(FL_Closure)));
    _fl_tmp_2->fn = ((void*)_fl_clfn_sort_sort_0);
    _fl_tmp_2->env = NULL;
    FL_Closure* _fl_tmp_3 = ((FL_Closure*)malloc(sizeof(FL_Closure)));
    _fl_tmp_3->fn = ((void*)_fl_srtwrap_sort_sort_1);
    _fl_tmp_3->env = ((void*)_fl_tmp_2);
    return fl_sort_array_by(arr, _fl_tmp_3);
}

/* Flow: sort.sort[mono] */
FL_Array* fl_sort_sort__string(FL_Array* arr) {
    FL_Closure* _fl_tmp_4 = ((FL_Closure*)malloc(sizeof(FL_Closure)));
    _fl_tmp_4->fn = ((void*)_fl_clfn_sort_sort_2);
    _fl_tmp_4->env = NULL;
    FL_Closure* _fl_tmp_5 = ((FL_Closure*)malloc(sizeof(FL_Closure)));
    _fl_tmp_5->fn = ((void*)_fl_srtwrap_sort_sort_3);
    _fl_tmp_5->env = ((void*)_fl_tmp_4);
    return fl_sort_array_by(arr, _fl_tmp_5);
}

/* Flow: conv.to_string[mono] */
FL_String* fl_conv_to_string__int(fl_int val) {
    return fl_int_to_string(val);
}

/* Flow: stdlib_generic_sort.main */
void fl_stdlib_generic_sort_main(void) {
    FL_Array* ints = fl_sort_sort__int(fl_array_new(5, sizeof(fl_int), (fl_int[]){3, 1, 4, 1, 5}));
    FL_Array* strs = fl_sort_sort__string(fl_array_new(3, sizeof(FL_String*), (FL_String*[]){fl_string_from_cstr("banana"), fl_string_from_cstr("apple"), fl_string_from_cstr("cherry")}));
    fl_int64 _fl_tmp_0 = 0;
    while (_fl_tmp_0 < fl_array_len(ints)) {
        fl_int n = (*((fl_int*)fl_array_get_ptr(ints, _fl_tmp_0)));
        fl_println(fl_conv_to_string__int(n));
        _fl_tmp_0 = (_fl_tmp_0 + 1);
    }
    fl_int64 _fl_tmp_1 = 0;
    while (_fl_tmp_1 < fl_array_len(strs)) {
        FL_String* s = (*((FL_String**)fl_array_get_ptr(strs, _fl_tmp_1)));
        fl_println(s);
        _fl_tmp_1 = (_fl_tmp_1 + 1);
    }
}

/* Flow: sort.sort::lambda0 */
fl_int _fl_clfn_sort_sort_0(void* _env, fl_int a, fl_int b) {
    return _fl_compare(a, b);
}

/* Flow: sort.sort::sort_cmp_wrapper */
fl_int _fl_srtwrap_sort_sort_1(void* _env, void* _a, void* _b) {
    FL_Closure* _inner = ((FL_Closure*)_env);
    fl_int a_val = (*((fl_int*)_a));
    fl_int b_val = (*((fl_int*)_b));
    return ((fl_int (*)(void*, fl_int, fl_int))_inner->fn)(_inner->env, a_val, b_val);
}

/* Flow: sort.sort::lambda2 */
fl_int _fl_clfn_sort_sort_2(void* _env, FL_String* a, FL_String* b) {
    return fl_string_cmp(a, b);
}

/* Flow: sort.sort::sort_cmp_wrapper */
fl_int _fl_srtwrap_sort_sort_3(void* _env, void* _a, void* _b) {
    FL_Closure* _inner = ((FL_Closure*)_env);
    FL_String* a_val = (*((FL_String**)_a));
    FL_String* b_val = (*((FL_String**)_b));
    return ((fl_int (*)(void*, FL_String*, FL_String*))_inner->fn)(_inner->env, a_val, b_val);
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_stdlib_generic_sort_main();
    return 0;
}
