/* Generated by reflowc - do not edit */
/* Source: tests/programs/stdlib_path_test.reflow */
#include "reflow_runtime.h"

/* ReFlow: tests.stdlib_path_test.main */
void rf_tests_stdlib_path_test_main(void) {
    RF_String* _rf_tmp_0 = rf_string_from_cstr("join: ");
    rf_println(rf_string_concat(_rf_tmp_0, rf_path_join(rf_string_from_cstr("foo"), rf_string_from_cstr("bar.txt"))));
    RF_String* _rf_tmp_1 = rf_string_from_cstr("stem: ");
    rf_println(rf_string_concat(_rf_tmp_1, rf_path_stem(rf_string_from_cstr("foo/bar.txt"))));
    RF_String* _rf_tmp_2 = rf_string_from_cstr("parent: ");
    rf_println(rf_string_concat(_rf_tmp_2, rf_path_parent(rf_string_from_cstr("foo/bar.txt"))));
    RF_String* _rf_tmp_3 = rf_string_from_cstr("with_suffix: ");
    rf_println(rf_string_concat(_rf_tmp_3, rf_path_with_suffix(rf_string_from_cstr("foo/bar.txt"), rf_string_from_cstr(".c"))));
    RF_String* _rf_tmp_4 = rf_string_from_cstr("exists Makefile: ");
    rf_println(rf_string_concat(_rf_tmp_4, rf_bool_to_string(rf_path_exists(rf_string_from_cstr("Makefile")))));
    RF_String* _rf_tmp_5 = rf_string_from_cstr("exists nope.xyz: ");
    rf_println(rf_string_concat(_rf_tmp_5, rf_bool_to_string(rf_path_exists(rf_string_from_cstr("nope.xyz")))));
}

/* Entry point */
int main(int argc, char** argv) {
    _rf_runtime_init(argc, argv);
    rf_tests_stdlib_path_test_main();
    return 0;
}
