/* Generated by flowc - do not edit */
/* Source: tests/programs/stdlib_path_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

/* From: stdlib/path.flow */

FL_String* fl_path_join(FL_Array* segments);

FL_String* fl_path_stem(FL_String* p);

FL_String* fl_path_parent(FL_String* p);

FL_String* fl_path_with_suffix(FL_String* p, FL_String* suffix);

FL_Option_ptr fl_path_extension(FL_String* p);

FL_Option_ptr fl_path_walk(FL_String* dir);

/* Flow: path.join */
FL_String* fl_path_join(FL_Array* segments) {
    FL_String* result = fl_string_from_cstr("");
    fl_int64 _fl_tmp_0 = 0;
    while (_fl_tmp_0 < fl_array_len(segments)) {
        FL_String* seg = (*((FL_String**)fl_array_get_ptr(segments, _fl_tmp_0)));
        if (fl_string_len(result) == 0) {
            result = seg;
        } else {
            if (fl_string_len(seg) > 0) {
                fl_int _fl_e_1;
                FL_CHECKED_SUB(fl_string_len(result), 1, &_fl_e_1);
                FL_Option_char _fl_tmp_1 = fl_string_char_at(result, _fl_e_1);
                if (_fl_tmp_1.tag == 1) {
                    fl_char last = _fl_tmp_1.value;
                    if (last == 47) {
                        result = fl_string_concat(result, seg);
                    } else {
                        result = fl_string_concat(fl_string_concat(result, fl_string_from_cstr("/")), seg);
                    }
                } else {
                    result = fl_string_concat(fl_string_concat(result, fl_string_from_cstr("/")), seg);
                }
            }
        }
        _fl_tmp_0 = (_fl_tmp_0 + 1);
    }
    return result;
}

/* Flow: path.stem */
FL_String* fl_path_stem(FL_String* p) {
    fl_int len = fl_string_len(p);
    fl_int start = 0;
    fl_int _fl_e_1;
    FL_CHECKED_SUB(len, 1, &_fl_e_1);
    fl_int i = _fl_e_1;
    while (i >= 0) {
        FL_Option_char _fl_tmp_2 = fl_string_char_at(p, i);
        if (_fl_tmp_2.tag == 1) {
            fl_char c = _fl_tmp_2.value;
            if (c == 47) {
                fl_int _fl_e_2;
                FL_CHECKED_ADD(i, 1, &_fl_e_2);
                start = _fl_e_2;
                i = (-1);
            } else {
                fl_int _fl_e_3;
                FL_CHECKED_SUB(i, 1, &_fl_e_3);
                i = _fl_e_3;
            }
        } else {
            fl_int _fl_e_4;
            FL_CHECKED_SUB(i, 1, &_fl_e_4);
            i = _fl_e_4;
        }
    }
    fl_int end = len;
    fl_int _fl_e_5;
    FL_CHECKED_SUB(len, 1, &_fl_e_5);
    i = _fl_e_5;
    while (i >= start) {
        FL_Option_char _fl_tmp_3 = fl_string_char_at(p, i);
        if (_fl_tmp_3.tag == 1) {
            fl_char c = _fl_tmp_3.value;
            if (c == 46) {
                end = i;
                i = (-1);
            } else {
                fl_int _fl_e_6;
                FL_CHECKED_SUB(i, 1, &_fl_e_6);
                i = _fl_e_6;
            }
        } else {
            fl_int _fl_e_7;
            FL_CHECKED_SUB(i, 1, &_fl_e_7);
            i = _fl_e_7;
        }
    }
    return fl_string_substring(p, start, end);
}

/* Flow: path.parent */
FL_String* fl_path_parent(FL_String* p) {
    fl_int len = fl_string_len(p);
    if (len > 1) {
        fl_int _fl_e_1;
        FL_CHECKED_SUB(len, 1, &_fl_e_1);
        FL_Option_char _fl_tmp_4 = fl_string_char_at(p, _fl_e_1);
        if (_fl_tmp_4.tag == 1) {
            fl_char c = _fl_tmp_4.value;
            if (c == 47) {
                fl_int _fl_e_2;
                FL_CHECKED_SUB(len, 1, &_fl_e_2);
                len = _fl_e_2;
            }
        }
    }
    fl_int _fl_e_3;
    FL_CHECKED_SUB(0, 1, &_fl_e_3);
    fl_int last_slash = _fl_e_3;
    fl_int _fl_e_4;
    FL_CHECKED_SUB(len, 1, &_fl_e_4);
    fl_int i = _fl_e_4;
    while (i >= 0) {
        FL_Option_char _fl_tmp_5 = fl_string_char_at(p, i);
        if (_fl_tmp_5.tag == 1) {
            fl_char c = _fl_tmp_5.value;
            if (c == 47) {
                last_slash = i;
                i = (-1);
            } else {
                fl_int _fl_e_5;
                FL_CHECKED_SUB(i, 1, &_fl_e_5);
                i = _fl_e_5;
            }
        } else {
            fl_int _fl_e_6;
            FL_CHECKED_SUB(i, 1, &_fl_e_6);
            i = _fl_e_6;
        }
    }
    if (last_slash < 0) {
        return fl_string_from_cstr(".");
    }
    if (last_slash == 0) {
        return fl_string_from_cstr("/");
    }
    return fl_string_substring(p, 0, last_slash);
}

/* Flow: path.with_suffix */
FL_String* fl_path_with_suffix(FL_String* p, FL_String* suffix) {
    fl_int len = fl_string_len(p);
    fl_int _fl_e_1;
    FL_CHECKED_SUB(0, 1, &_fl_e_1);
    fl_int dot = _fl_e_1;
    fl_int _fl_e_2;
    FL_CHECKED_SUB(0, 1, &_fl_e_2);
    fl_int last_slash = _fl_e_2;
    fl_int _fl_e_3;
    FL_CHECKED_SUB(len, 1, &_fl_e_3);
    fl_int i = _fl_e_3;
    while (i >= 0) {
        FL_Option_char _fl_tmp_6 = fl_string_char_at(p, i);
        if (_fl_tmp_6.tag == 1) {
            fl_char c = _fl_tmp_6.value;
            if ((c == 47) && (last_slash < 0)) {
                last_slash = i;
                i = (-1);
            } else {
                if ((c == 46) && (dot < 0)) {
                    dot = i;
                }
            }
        }
        if (i >= 0) {
            fl_int _fl_e_4;
            FL_CHECKED_SUB(i, 1, &_fl_e_4);
            i = _fl_e_4;
        }
    }
    fl_int _fl_tmp_7;
    if ((dot >= 0) && (dot > last_slash)) {
        _fl_tmp_7 = dot;
    } else {
        _fl_tmp_7 = len;
    }
    fl_int base_end = _fl_tmp_7;
    return fl_string_concat(fl_string_substring(p, 0, base_end), suffix);
}

/* Flow: path.extension */
FL_Option_ptr fl_path_extension(FL_String* p) {
    fl_int len = fl_string_len(p);
    fl_int base_start = 0;
    fl_int _fl_e_1;
    FL_CHECKED_SUB(len, 1, &_fl_e_1);
    fl_int i = _fl_e_1;
    while (i >= 0) {
        FL_Option_char _fl_tmp_8 = fl_string_char_at(p, i);
        if (_fl_tmp_8.tag == 1) {
            fl_char c = _fl_tmp_8.value;
            if (c == 47) {
                fl_int _fl_e_2;
                FL_CHECKED_ADD(i, 1, &_fl_e_2);
                base_start = _fl_e_2;
                i = (-1);
            } else {
                fl_int _fl_e_3;
                FL_CHECKED_SUB(i, 1, &_fl_e_3);
                i = _fl_e_3;
            }
        } else {
            fl_int _fl_e_4;
            FL_CHECKED_SUB(i, 1, &_fl_e_4);
            i = _fl_e_4;
        }
    }
    fl_int _fl_e_5;
    FL_CHECKED_SUB(0, 1, &_fl_e_5);
    fl_int dot = _fl_e_5;
    fl_int _fl_e_6;
    FL_CHECKED_SUB(len, 1, &_fl_e_6);
    i = _fl_e_6;
    while (i >= base_start) {
        FL_Option_char _fl_tmp_9 = fl_string_char_at(p, i);
        if (_fl_tmp_9.tag == 1) {
            fl_char c = _fl_tmp_9.value;
            if (c == 46) {
                dot = i;
                i = (-1);
            } else {
                fl_int _fl_e_7;
                FL_CHECKED_SUB(i, 1, &_fl_e_7);
                i = _fl_e_7;
            }
        } else {
            fl_int _fl_e_8;
            FL_CHECKED_SUB(i, 1, &_fl_e_8);
            i = _fl_e_8;
        }
    }
    if ((dot < 0) || (dot == base_start)) {
        return (FL_Option_ptr){.tag = 0};
    }
    return (FL_Option_ptr){.tag = 1, .value = fl_string_substring(p, dot, len)};
}

/* Flow: path.walk */
FL_Option_ptr fl_path_walk(FL_String* dir) {
    FL_Option_ptr _fl_tmp_10 = fl_path_list_dir(dir);
    if (_fl_tmp_10.tag == 1) {
        FL_Array* entries = _fl_tmp_10.value;
        FL_Array* result = fl_array_new(0, 0, NULL);
        fl_int64 _fl_tmp_11 = 0;
        while (_fl_tmp_11 < fl_array_len(entries)) {
            FL_String* entry = (*((FL_String**)fl_array_get_ptr(entries, _fl_tmp_11)));
            FL_String* full = fl_path_join(fl_array_new(2, sizeof(FL_String*), (FL_String*[]){dir, entry}));
            result = fl_array_push_ptr(result, full);
            if (fl_path_is_dir(full)) {
                FL_Option_ptr _fl_tmp_12 = fl_path_walk(full);
                if (_fl_tmp_12.tag == 1) {
                    FL_Array* children = _fl_tmp_12.value;
                    result = fl_array_concat(result, children);
                }
            }
            _fl_tmp_11 = (_fl_tmp_11 + 1);
        }
        return (FL_Option_ptr){.tag = 1, .value = result};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

/* Flow: tests.stdlib_path_test.main */
void fl_tests_stdlib_path_test_main(void) {
    FL_String* _fl_tmp_0 = fl_string_from_cstr("join: ");
    fl_println(fl_string_concat(_fl_tmp_0, fl_path_join(fl_array_new(2, sizeof(FL_String*), (FL_String*[]){fl_string_from_cstr("foo"), fl_string_from_cstr("bar.txt")}))));
    FL_String* _fl_tmp_1 = fl_string_from_cstr("stem: ");
    fl_println(fl_string_concat(_fl_tmp_1, fl_path_stem(fl_string_from_cstr("foo/bar.txt"))));
    FL_String* _fl_tmp_2 = fl_string_from_cstr("parent: ");
    fl_println(fl_string_concat(_fl_tmp_2, fl_path_parent(fl_string_from_cstr("foo/bar.txt"))));
    FL_String* _fl_tmp_3 = fl_string_from_cstr("with_suffix: ");
    fl_println(fl_string_concat(_fl_tmp_3, fl_path_with_suffix(fl_string_from_cstr("foo/bar.txt"), fl_string_from_cstr(".c"))));
    FL_String* _fl_tmp_4 = fl_string_from_cstr("exists Makefile: ");
    fl_println(fl_string_concat(_fl_tmp_4, fl_bool_to_string(fl_path_exists(fl_string_from_cstr("Makefile")))));
    FL_String* _fl_tmp_5 = fl_string_from_cstr("exists nope.xyz: ");
    fl_println(fl_string_concat(_fl_tmp_5, fl_bool_to_string(fl_path_exists(fl_string_from_cstr("nope.xyz")))));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_stdlib_path_test_main();
    return 0;
}
