/* Generated by flowc - do not edit */
/* Source: tests/programs/stdlib_string_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

/* Flow: tests.stdlib_string_test.main */
void fl_tests_stdlib_string_test_main(void) {
    FL_String* s = fl_string_from_cstr("Hello, World!");
    FL_Option_char ch = fl_string_char_at(s, 0);
    FL_Option_char _fl_tmp_0 = ch;
    if (_fl_tmp_0.tag == 1) {
        fl_char c = _fl_tmp_0.value;
        FL_String* _fl_tmp_1 = fl_string_from_cstr("char_at(0): ");
        FL_String* _fl_tmp_2 = fl_string_concat(_fl_tmp_1, fl_char_to_string(c));
        fl_string_release(_fl_tmp_1);
        fl_println(_fl_tmp_2);
    } else {
        fl_println(fl_string_from_cstr("char_at(0): none"));
    }
    FL_String* sub = fl_string_substring(s, 7, 12);
    FL_String* _fl_tmp_3 = fl_string_from_cstr("substring(7,12): ");
    FL_String* _fl_tmp_4 = fl_string_concat(_fl_tmp_3, sub);
    fl_string_release(_fl_tmp_3);
    fl_println(_fl_tmp_4);
    FL_Option_int idx = fl_string_index_of(s, fl_string_from_cstr("World"));
    FL_Option_int _fl_tmp_5 = idx;
    if (_fl_tmp_5.tag == 1) {
        fl_int i = _fl_tmp_5.value;
        FL_String* _fl_tmp_6 = fl_string_from_cstr("index_of World: ");
        FL_String* _fl_tmp_7 = fl_string_concat(_fl_tmp_6, fl_int_to_string(i));
        fl_string_release(_fl_tmp_6);
        fl_println(_fl_tmp_7);
    } else {
        fl_println(fl_string_from_cstr("index_of World: none"));
    }
    FL_String* _fl_tmp_8 = fl_string_from_cstr("contains World: ");
    FL_String* _fl_tmp_9 = fl_string_concat(_fl_tmp_8, fl_bool_to_string(fl_string_contains(s, fl_string_from_cstr("World"))));
    fl_string_release(_fl_tmp_8);
    fl_println(_fl_tmp_9);
    FL_String* _fl_tmp_10 = fl_string_from_cstr("starts_with Hello: ");
    FL_String* _fl_tmp_11 = fl_string_concat(_fl_tmp_10, fl_bool_to_string(fl_string_starts_with(s, fl_string_from_cstr("Hello"))));
    fl_string_release(_fl_tmp_10);
    fl_println(_fl_tmp_11);
    FL_String* _fl_tmp_12 = fl_string_from_cstr("ends_with !: ");
    FL_String* _fl_tmp_13 = fl_string_concat(_fl_tmp_12, fl_bool_to_string(fl_string_ends_with(s, fl_string_from_cstr("!"))));
    fl_string_release(_fl_tmp_12);
    fl_println(_fl_tmp_13);
    FL_String* lower = fl_string_to_lower(fl_string_from_cstr("HELLO"));
    FL_String* _fl_tmp_14 = fl_string_from_cstr("to_lower: ");
    FL_String* _fl_tmp_15 = fl_string_concat(_fl_tmp_14, lower);
    fl_string_release(_fl_tmp_14);
    fl_println(_fl_tmp_15);
    FL_String* upper = fl_string_to_upper(fl_string_from_cstr("hello"));
    FL_String* _fl_tmp_16 = fl_string_from_cstr("to_upper: ");
    FL_String* _fl_tmp_17 = fl_string_concat(_fl_tmp_16, upper);
    fl_string_release(_fl_tmp_16);
    fl_println(_fl_tmp_17);
    FL_String* trimmed = fl_string_trim(fl_string_from_cstr("  hi  "));
    FL_String* _fl_tmp_18 = fl_string_from_cstr("trim: [");
    FL_String* _fl_tmp_19 = fl_string_concat(_fl_tmp_18, trimmed);
    FL_String* _fl_tmp_20 = fl_string_concat(_fl_tmp_19, fl_string_from_cstr("]"));
    fl_string_release(_fl_tmp_18);
    fl_string_release(_fl_tmp_19);
    fl_println(_fl_tmp_20);
    FL_String* replaced = fl_string_replace(fl_string_from_cstr("aabaa"), fl_string_from_cstr("a"), fl_string_from_cstr("x"));
    FL_String* _fl_tmp_21 = fl_string_from_cstr("replace: ");
    FL_String* _fl_tmp_22 = fl_string_concat(_fl_tmp_21, replaced);
    fl_string_release(_fl_tmp_21);
    fl_println(_fl_tmp_22);
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_stdlib_string_test_main();
    return 0;
}
