/* Generated by flowc - do not edit */
/* Source: tests/programs/stream_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        return fl_string_from_cstr("");
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : fl_string_from_cstr(""));
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        result = fl_string_concat(fl_string_concat(result, sep), ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : fl_string_from_cstr("")));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, fl_string_from_cstr("\n"))};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

typedef struct _fl_frame_tests_stream_test_range _fl_frame_tests_stream_test_range;

FL_Option_ptr _fl_next_tests_stream_test_range(FL_Stream* self);

void _fl_free_tests_stream_test_range(FL_Stream* self);

FL_Stream* fl_tests_stream_test_range(fl_int n);

void fl_tests_stream_test_main(void);

struct _fl_frame_tests_stream_test_range {
    fl_int _state;
    fl_int n;
    fl_int i;
};

/* Flow: tests.stream_test.range::next */
FL_Option_ptr _fl_next_tests_stream_test_range(FL_Stream* self) {
    _fl_frame_tests_stream_test_range* frame = ((_fl_frame_tests_stream_test_range*)self->state);
    switch (frame->_state) {
        case 0: {
            goto _fl_state_0;
            break;
        }
        case 1: {
            goto _fl_state_1;
            break;
        }
        default: {
            goto _fl_stream_done;
            break;
        }
    }
_fl_state_0:;
    frame->i = 0;
    while (frame->i < frame->n) {
        frame->_state = 1;
        return (FL_Option_ptr){.tag = 1, .value = ((void*)((fl_uint64)frame->i))};
_fl_state_1:;
        fl_int _fl_e_1;
        FL_CHECKED_ADD(frame->i, 1, &_fl_e_1);
        frame->i = _fl_e_1;
    }
_fl_stream_done:;
    frame->_state = -1;
    return (FL_Option_ptr){.tag = 0, .value = NULL};
}

/* Flow: tests.stream_test.range::free */
void _fl_free_tests_stream_test_range(FL_Stream* self) {
    _fl_frame_tests_stream_test_range* frame = ((_fl_frame_tests_stream_test_range*)self->state);
    free(frame);
}

/* Flow: tests.stream_test.range */
FL_Stream* fl_tests_stream_test_range(fl_int n) {
    _fl_frame_tests_stream_test_range* frame = ((_fl_frame_tests_stream_test_range*)malloc(sizeof(_fl_frame_tests_stream_test_range)));
    frame->_state = 0;
    frame->n = n;
    return fl_stream_new(_fl_next_tests_stream_test_range, _fl_free_tests_stream_test_range, ((void*)frame));
}

/* Flow: tests.stream_test.main */
void fl_tests_stream_test_main(void) {
    FL_Stream* _fl_tmp_1 = fl_tests_stream_test_range(5);
    while (1) {
        FL_Option_ptr _fl_tmp_0 = fl_stream_next(_fl_tmp_1);
        if (_fl_tmp_0.tag == 0) {
            break;
        }
        fl_int x = ((fl_int)((fl_uint64)_fl_tmp_0.value));
        FL_String* _fl_tmp_2 = fl_string_from_cstr("  ");
        fl_println(fl_string_concat(_fl_tmp_2, fl_int_to_string(x)));
    }
    fl_int total = 0;
    FL_Stream* _fl_tmp_4 = fl_tests_stream_test_range(10);
    while (1) {
        FL_Option_ptr _fl_tmp_3 = fl_stream_next(_fl_tmp_4);
        if (_fl_tmp_3.tag == 0) {
            break;
        }
        fl_int x = ((fl_int)((fl_uint64)_fl_tmp_3.value));
        fl_int _fl_e_1;
        FL_CHECKED_ADD(total, x, &_fl_e_1);
        total = _fl_e_1;
    }
    FL_String* _fl_tmp_5 = fl_string_from_cstr("sum 0..9 = ");
    fl_println(fl_string_concat(_fl_tmp_5, fl_int_to_string(total)));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_stream_test_main();
    return 0;
}
