/* Generated by reflowc - do not edit */
/* Source: tests/programs/struct_test.reflow */
#include "reflow_runtime.h"

typedef struct rf_tests_struct_test_Point rf_tests_struct_test_Point;

typedef struct rf_tests_struct_test_Counter rf_tests_struct_test_Counter;

rf_int rf_tests_struct_test_Counter_current(rf_tests_struct_test_Counter* self);

void rf_tests_struct_test_Counter_display(rf_tests_struct_test_Counter* self);

void rf_tests_struct_test_main(void);

struct rf_tests_struct_test_Point {
    rf_float x;
    rf_float y;
};

struct rf_tests_struct_test_Counter {
    rf_int value;
};

/* ReFlow: tests.struct_test.Counter.current */
rf_int rf_tests_struct_test_Counter_current(rf_tests_struct_test_Counter* self) {
    return self->value;
}

/* ReFlow: tests.struct_test.Counter.display */
void rf_tests_struct_test_Counter_display(rf_tests_struct_test_Counter* self) {
    RF_String* _rf_tmp_0 = rf_string_from_cstr("counter = ");
    rf_println(rf_string_concat(_rf_tmp_0, rf_int_to_string(self->value)));
}

/* ReFlow: tests.struct_test.main */
void rf_tests_struct_test_main(void) {
    rf_tests_struct_test_Point p = (rf_tests_struct_test_Point){.x = 3.0, .y = 4.0};
    RF_String* _rf_tmp_1 = rf_string_from_cstr("point: (");
    RF_String* _rf_tmp_2 = rf_string_concat(_rf_tmp_1, rf_float_to_string(p.x));
    RF_String* _rf_tmp_3 = rf_string_concat(_rf_tmp_2, rf_string_from_cstr(", "));
    RF_String* _rf_tmp_4 = rf_string_concat(_rf_tmp_3, rf_float_to_string(p.y));
    rf_println(rf_string_concat(_rf_tmp_4, rf_string_from_cstr(")")));
    rf_tests_struct_test_Counter c = (rf_tests_struct_test_Counter){.value = 0};
    rf_tests_struct_test_Counter_display((&c));
    c.value = 10;
    rf_tests_struct_test_Counter_display((&c));
    RF_String* _rf_tmp_5 = rf_string_from_cstr("current = ");
    rf_println(rf_string_concat(_rf_tmp_5, rf_int_to_string(rf_tests_struct_test_Counter_current((&c)))));
}

/* Entry point */
int main(int argc, char** argv) {
    _rf_runtime_init(argc, argv);
    rf_tests_struct_test_main();
    return 0;
}
