/* Generated by reflowc - do not edit */
/* Source: tests/programs/sum_type_test.reflow */
#include "reflow_runtime.h"

typedef struct rf_tests_sum_type_test_Shape_Circle rf_tests_sum_type_test_Shape_Circle;

typedef struct rf_tests_sum_type_test_Shape_Rectangle rf_tests_sum_type_test_Shape_Rectangle;

typedef struct rf_tests_sum_type_test_Shape_Square rf_tests_sum_type_test_Shape_Square;

typedef struct rf_tests_sum_type_test_Shape rf_tests_sum_type_test_Shape;

typedef struct rf_tests_sum_type_test_Direction rf_tests_sum_type_test_Direction;

rf_float rf_tests_sum_type_test_area(rf_tests_sum_type_test_Shape s);

rf_tests_sum_type_test_Direction rf_tests_sum_type_test_opposite(rf_tests_sum_type_test_Direction d);

RF_String* rf_tests_sum_type_test_dir_name(rf_tests_sum_type_test_Direction d);

void rf_tests_sum_type_test_main(void);

struct rf_tests_sum_type_test_Shape_Circle {
    rf_float radius;
};

struct rf_tests_sum_type_test_Shape_Rectangle {
    rf_float width;
    rf_float height;
};

struct rf_tests_sum_type_test_Shape_Square {
    rf_float side;
};

struct rf_tests_sum_type_test_Shape {
    rf_byte tag;
    rf_tests_sum_type_test_Shape_Circle Circle;
    rf_tests_sum_type_test_Shape_Rectangle Rectangle;
    rf_tests_sum_type_test_Shape_Square Square;
};

struct rf_tests_sum_type_test_Direction {
    rf_byte tag;
};

/* ReFlow: tests.sum_type_test.area */
rf_float rf_tests_sum_type_test_area(rf_tests_sum_type_test_Shape s) {
    rf_tests_sum_type_test_Shape _rf_tmp_0 = s;
    switch (_rf_tmp_0.tag) {
        case 0:
            rf_float r = _rf_tmp_0.Circle.radius;
            return ((3.14159 * r) * r);
            break;
        case 1:
            rf_float w = _rf_tmp_0.Rectangle.width;
            rf_float h = _rf_tmp_0.Rectangle.height;
            return (w * h);
            break;
        case 2:
            rf_float sd = _rf_tmp_0.Square.side;
            return (sd * sd);
            break;
    }
}

/* ReFlow: tests.sum_type_test.opposite */
rf_tests_sum_type_test_Direction rf_tests_sum_type_test_opposite(rf_tests_sum_type_test_Direction d) {
    rf_tests_sum_type_test_Direction _rf_tmp_1 = d;
    switch (_rf_tmp_1.tag) {
        case 0:
            return (rf_tests_sum_type_test_Direction){.tag = 1};
            break;
        case 1:
            return (rf_tests_sum_type_test_Direction){.tag = 0};
            break;
        case 2:
            return (rf_tests_sum_type_test_Direction){.tag = 3};
            break;
        case 3:
            return (rf_tests_sum_type_test_Direction){.tag = 2};
            break;
    }
}

/* ReFlow: tests.sum_type_test.dir_name */
RF_String* rf_tests_sum_type_test_dir_name(rf_tests_sum_type_test_Direction d) {
    rf_tests_sum_type_test_Direction _rf_tmp_2 = d;
    switch (_rf_tmp_2.tag) {
        case 0:
            return rf_string_from_cstr("North");
            break;
        case 1:
            return rf_string_from_cstr("South");
            break;
        case 2:
            return rf_string_from_cstr("East");
            break;
        case 3:
            return rf_string_from_cstr("West");
            break;
    }
}

/* ReFlow: tests.sum_type_test.main */
void rf_tests_sum_type_test_main(void) {
    rf_tests_sum_type_test_Shape c = (rf_tests_sum_type_test_Shape){.tag = 0, .Circle = (rf_tests_sum_type_test_Shape_Circle){.radius = 5.0}};
    rf_tests_sum_type_test_Shape r = (rf_tests_sum_type_test_Shape){.tag = 1, .Rectangle = (rf_tests_sum_type_test_Shape_Rectangle){.width = 3.0, .height = 4.0}};
    rf_tests_sum_type_test_Shape sq = (rf_tests_sum_type_test_Shape){.tag = 2, .Square = (rf_tests_sum_type_test_Shape_Square){.side = 7.0}};
    RF_String* _rf_tmp_3 = rf_string_from_cstr("circle area = ");
    rf_println(rf_string_concat(_rf_tmp_3, rf_float_to_string(rf_tests_sum_type_test_area(c))));
    RF_String* _rf_tmp_4 = rf_string_from_cstr("rect area = ");
    rf_println(rf_string_concat(_rf_tmp_4, rf_float_to_string(rf_tests_sum_type_test_area(r))));
    RF_String* _rf_tmp_5 = rf_string_from_cstr("square area = ");
    rf_println(rf_string_concat(_rf_tmp_5, rf_float_to_string(rf_tests_sum_type_test_area(sq))));
    rf_tests_sum_type_test_Direction d = (rf_tests_sum_type_test_Direction){.tag = 0};
    rf_tests_sum_type_test_Direction o = rf_tests_sum_type_test_opposite(d);
    RF_String* _rf_tmp_6 = rf_string_from_cstr("opposite of ");
    RF_String* _rf_tmp_7 = rf_string_concat(_rf_tmp_6, rf_tests_sum_type_test_dir_name(d));
    RF_String* _rf_tmp_8 = rf_string_concat(_rf_tmp_7, rf_string_from_cstr(" is "));
    rf_println(rf_string_concat(_rf_tmp_8, rf_tests_sum_type_test_dir_name(o)));
}

/* Entry point */
int main(int argc, char** argv) {
    _rf_runtime_init(argc, argv);
    rf_tests_sum_type_test_main();
    return 0;
}
