/* Generated by flowc - do not edit */
/* Source: tests/programs/throw_tail_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        fl_string_retain(_fl_str_string_0);
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_string_release(_fl_tmp_2);
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

fl_int fl_tests_throw_tail_test_always_throws(void);

fl_int fl_tests_throw_tail_test_maybe_throws(fl_bool fail);

void fl_tests_throw_tail_test_main(void);

FL_String* _fl_str_tests_throw_tail_test_0 = NULL;

FL_String* _fl_str_tests_throw_tail_test_1 = NULL;

FL_String* _fl_str_tests_throw_tail_test_2 = NULL;

FL_String* _fl_str_tests_throw_tail_test_3 = NULL;

FL_String* _fl_str_tests_throw_tail_test_4 = NULL;

FL_String* _fl_str_tests_throw_tail_test_5 = NULL;

FL_String* _fl_str_tests_throw_tail_test_6 = NULL;

/* Flow: tests.throw_tail_test.always_throws */
fl_int fl_tests_throw_tail_test_always_throws(void) {
    _fl_throw(((void*)_fl_str_tests_throw_tail_test_0), 0);
}

/* Flow: tests.throw_tail_test.maybe_throws */
fl_int fl_tests_throw_tail_test_maybe_throws(fl_bool fail) {
    if (fail) {
        _fl_throw(((void*)_fl_str_tests_throw_tail_test_1), 0);
    }
    return 42;
}

/* Flow: tests.throw_tail_test.main */
void fl_tests_throw_tail_test_main(void) {
    fl_int a = fl_tests_throw_tail_test_maybe_throws(fl_false);
    FL_String* _fl_tmp_0 = _fl_str_tests_throw_tail_test_2;
    FL_String* _fl_tmp_1 = fl_string_concat(_fl_tmp_0, fl_int_to_string(a));
    fl_string_release(_fl_tmp_0);
    fl_println(_fl_tmp_1);
    FL_ExceptionFrame _fl_ef_0;
    _fl_exception_push((&_fl_ef_0));
    if (setjmp(_fl_ef_0.jmp) == 0) {
        fl_int b = fl_tests_throw_tail_test_always_throws();
        FL_String* _fl_tmp_2 = _fl_str_tests_throw_tail_test_3;
        FL_String* _fl_tmp_3 = fl_string_concat(_fl_tmp_2, fl_int_to_string(b));
        fl_string_release(_fl_tmp_2);
        fl_println(_fl_tmp_3);
        _fl_exception_pop();
    } else {
        _fl_exception_pop();
        if (_fl_ef_0.exception_tag == 0) {
            FL_String* ex = ((FL_String*)_fl_ef_0.exception);
            FL_String* _fl_tmp_4 = _fl_str_tests_throw_tail_test_4;
            FL_String* _fl_tmp_5 = fl_string_concat(_fl_tmp_4, ex);
            fl_string_release(_fl_tmp_4);
            fl_println(_fl_tmp_5);
        } else {
            _fl_throw(_fl_ef_0.exception, _fl_ef_0.exception_tag);
        }
    }
    FL_ExceptionFrame _fl_ef_1;
    _fl_exception_push((&_fl_ef_1));
    if (setjmp(_fl_ef_1.jmp) == 0) {
        fl_int c = fl_tests_throw_tail_test_maybe_throws(fl_true);
        FL_String* _fl_tmp_6 = _fl_str_tests_throw_tail_test_5;
        FL_String* _fl_tmp_7 = fl_string_concat(_fl_tmp_6, fl_int_to_string(c));
        fl_string_release(_fl_tmp_6);
        fl_println(_fl_tmp_7);
        _fl_exception_pop();
    } else {
        _fl_exception_pop();
        if (_fl_ef_1.exception_tag == 0) {
            FL_String* ex = ((FL_String*)_fl_ef_1.exception);
            FL_String* _fl_tmp_8 = _fl_str_tests_throw_tail_test_4;
            FL_String* _fl_tmp_9 = fl_string_concat(_fl_tmp_8, ex);
            fl_string_release(_fl_tmp_8);
            fl_println(_fl_tmp_9);
        } else {
            _fl_throw(_fl_ef_1.exception, _fl_ef_1.exception_tag);
        }
    }
    fl_println(_fl_str_tests_throw_tail_test_6);
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_tests_throw_tail_test_0 = fl_string_from_cstr("always");
    _fl_str_tests_throw_tail_test_0->refcount = 2147483647;
    _fl_str_tests_throw_tail_test_1 = fl_string_from_cstr("failed");
    _fl_str_tests_throw_tail_test_1->refcount = 2147483647;
    _fl_str_tests_throw_tail_test_2 = fl_string_from_cstr("a=");
    _fl_str_tests_throw_tail_test_2->refcount = 2147483647;
    _fl_str_tests_throw_tail_test_3 = fl_string_from_cstr("b=");
    _fl_str_tests_throw_tail_test_3->refcount = 2147483647;
    _fl_str_tests_throw_tail_test_4 = fl_string_from_cstr("caught: ");
    _fl_str_tests_throw_tail_test_4->refcount = 2147483647;
    _fl_str_tests_throw_tail_test_5 = fl_string_from_cstr("c=");
    _fl_str_tests_throw_tail_test_5->refcount = 2147483647;
    _fl_str_tests_throw_tail_test_6 = fl_string_from_cstr("done");
    _fl_str_tests_throw_tail_test_6->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_tests_throw_tail_test_main();
    return 0;
}
