/* Generated by flowc - do not edit */
/* Source: tests/programs/tuple_test.flow */
#include "flow_runtime.h"

/* From: stdlib/string.flow */

FL_String* _fl_str_string_0 = NULL;

/* Flow: string.join */
FL_String* fl_string_join(FL_String* sep, FL_Array* parts) {
    fl_int n = fl_array_len_int(parts);
    if (n == 0) {
        fl_string_retain(_fl_str_string_0);
        return _fl_str_string_0;
    }
    FL_Option_ptr _fl_tmp_0 = fl_array_get_safe(parts, 0);
    FL_String* result = ((_fl_tmp_0.tag == 1) ? _fl_tmp_0.value : _fl_str_string_0);
    fl_string_retain(result);
    fl_int i = 1;
    while (i < n) {
        FL_Option_ptr _fl_tmp_1 = fl_array_get_safe(parts, i);
        FL_String* _fl_tmp_2 = fl_string_concat(result, sep);
        FL_String* _fl_old_3 = result;
        result = fl_string_concat(_fl_tmp_2, ((_fl_tmp_1.tag == 1) ? _fl_tmp_1.value : _fl_str_string_0));
        if (_fl_old_3 != result) {
            fl_string_release(_fl_old_3);
        }
        fl_string_release(_fl_tmp_2);
        fl_int _fl_e_1;
        FL_CHECKED_ADD(i, 1, &_fl_e_1);
        i = _fl_e_1;
    }
    return result;
}

/* From: stdlib/io.flow */

FL_String* _fl_str_io_0 = NULL;

/* Flow: io.read_file_lines */
FL_Option_ptr fl_io_read_file_lines(FL_String* p) {
    FL_Option_ptr _fl_tmp_0 = fl_read_file(p);
    if (_fl_tmp_0.tag == 1) {
        FL_String* content = _fl_tmp_0.value;
        return (FL_Option_ptr){.tag = 1, .value = fl_string_split(content, _fl_str_io_0)};
    } else {
        return (FL_Option_ptr){.tag = 0};
    }
}

typedef struct FL_Tuple_fl_int_fl_int FL_Tuple_fl_int_fl_int;

FL_Tuple_fl_int_fl_int fl_tests_tuple_test_swap(fl_int a, fl_int b);

void fl_tests_tuple_test_main(void);

struct FL_Tuple_fl_int_fl_int {
    fl_int _0;
    fl_int _1;
};

FL_String* _fl_str_tests_tuple_test_0 = NULL;

FL_String* _fl_str_tests_tuple_test_1 = NULL;

FL_String* _fl_str_tests_tuple_test_2 = NULL;

FL_String* _fl_str_tests_tuple_test_3 = NULL;

/* Flow: tests.tuple_test.swap */
FL_Tuple_fl_int_fl_int fl_tests_tuple_test_swap(fl_int a, fl_int b) {
    return (FL_Tuple_fl_int_fl_int){._0 = b, ._1 = a};
}

/* Flow: tests.tuple_test.main */
void fl_tests_tuple_test_main(void) {
    FL_Tuple_fl_int_fl_int pair = (FL_Tuple_fl_int_fl_int){._0 = 42, ._1 = 99};
    FL_String* _fl_tmp_0 = _fl_str_tests_tuple_test_0;
    FL_String* _fl_tmp_1 = fl_string_concat(_fl_tmp_0, fl_int_to_string(pair._0));
    FL_String* _fl_tmp_2 = fl_string_concat(_fl_tmp_1, _fl_str_tests_tuple_test_1);
    FL_String* _fl_tmp_3 = fl_string_concat(_fl_tmp_2, fl_int_to_string(pair._1));
    FL_String* _fl_tmp_4 = fl_string_concat(_fl_tmp_3, _fl_str_tests_tuple_test_2);
    fl_string_release(_fl_tmp_0);
    fl_string_release(_fl_tmp_1);
    fl_string_release(_fl_tmp_2);
    fl_string_release(_fl_tmp_3);
    fl_println(_fl_tmp_4);
    FL_Tuple_fl_int_fl_int result = fl_tests_tuple_test_swap(10, 20);
    FL_String* _fl_tmp_5 = _fl_str_tests_tuple_test_3;
    FL_String* _fl_tmp_6 = fl_string_concat(_fl_tmp_5, fl_int_to_string(result._0));
    FL_String* _fl_tmp_7 = fl_string_concat(_fl_tmp_6, _fl_str_tests_tuple_test_1);
    FL_String* _fl_tmp_8 = fl_string_concat(_fl_tmp_7, fl_int_to_string(result._1));
    FL_String* _fl_tmp_9 = fl_string_concat(_fl_tmp_8, _fl_str_tests_tuple_test_2);
    fl_string_release(_fl_tmp_5);
    fl_string_release(_fl_tmp_6);
    fl_string_release(_fl_tmp_7);
    fl_string_release(_fl_tmp_8);
    fl_println(_fl_tmp_9);
}

static void _fl_init_statics(void) {
    _fl_str_string_0 = fl_string_from_cstr("");
    _fl_str_string_0->refcount = 2147483647;
    _fl_str_io_0 = fl_string_from_cstr("\n");
    _fl_str_io_0->refcount = 2147483647;
    _fl_str_tests_tuple_test_0 = fl_string_from_cstr("pair = (");
    _fl_str_tests_tuple_test_0->refcount = 2147483647;
    _fl_str_tests_tuple_test_1 = fl_string_from_cstr(", ");
    _fl_str_tests_tuple_test_1->refcount = 2147483647;
    _fl_str_tests_tuple_test_2 = fl_string_from_cstr(")");
    _fl_str_tests_tuple_test_2->refcount = 2147483647;
    _fl_str_tests_tuple_test_3 = fl_string_from_cstr("swap(10, 20) = (");
    _fl_str_tests_tuple_test_3->refcount = 2147483647;
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    _fl_init_statics();
    fl_tests_tuple_test_main();
    return 0;
}
