/* Generated by flowc - do not edit */
/* Source: tests/programs/tuple_test.flow */
#include "flow_runtime.h"

typedef struct FL_Tuple_fl_int_fl_int FL_Tuple_fl_int_fl_int;

FL_Tuple_fl_int_fl_int fl_tests_tuple_test_swap(fl_int a, fl_int b);

void fl_tests_tuple_test_main(void);

struct FL_Tuple_fl_int_fl_int {
    fl_int _0;
    fl_int _1;
};

/* Flow: tests.tuple_test.swap */
FL_Tuple_fl_int_fl_int fl_tests_tuple_test_swap(fl_int a, fl_int b) {
    return (FL_Tuple_fl_int_fl_int){._0 = b, ._1 = a};
}

/* Flow: tests.tuple_test.main */
void fl_tests_tuple_test_main(void) {
    FL_Tuple_fl_int_fl_int pair = (FL_Tuple_fl_int_fl_int){._0 = 42, ._1 = 99};
    FL_String* _fl_tmp_0 = fl_string_from_cstr("pair = (");
    FL_String* _fl_tmp_1 = fl_string_concat(_fl_tmp_0, fl_int_to_string(pair._0));
    FL_String* _fl_tmp_2 = fl_string_concat(_fl_tmp_1, fl_string_from_cstr(", "));
    FL_String* _fl_tmp_3 = fl_string_concat(_fl_tmp_2, fl_int_to_string(pair._1));
    fl_println(fl_string_concat(_fl_tmp_3, fl_string_from_cstr(")")));
    FL_Tuple_fl_int_fl_int result = fl_tests_tuple_test_swap(10, 20);
    FL_String* _fl_tmp_4 = fl_string_from_cstr("swap(10, 20) = (");
    FL_String* _fl_tmp_5 = fl_string_concat(_fl_tmp_4, fl_int_to_string(result._0));
    FL_String* _fl_tmp_6 = fl_string_concat(_fl_tmp_5, fl_string_from_cstr(", "));
    FL_String* _fl_tmp_7 = fl_string_concat(_fl_tmp_6, fl_int_to_string(result._1));
    fl_println(fl_string_concat(_fl_tmp_7, fl_string_from_cstr(")")));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_tuple_test_main();
    return 0;
}
