/* Generated by flowc - do not edit */
/* Source: tests/programs/typeof_test.flow */
#include "flow_runtime.h"

typedef struct FL_Tuple_fl_int_fl_int FL_Tuple_fl_int_fl_int;

void fl_tests_typeof_test_main(void);

struct FL_Tuple_fl_int_fl_int {
    fl_int _0;
    fl_int _1;
};

/* Flow: tests.typeof_test.main */
void fl_tests_typeof_test_main(void) {
    fl_int x = 42;
    fl_println(fl_string_from_cstr("int"));
    FL_String* s = fl_string_from_cstr("hello");
    fl_println(fl_string_from_cstr("string"));
    fl_bool b = fl_true;
    fl_println(fl_string_from_cstr("bool"));
    fl_float f = 3.14;
    fl_println(fl_string_from_cstr("float"));
    FL_Tuple_fl_int_fl_int t = (FL_Tuple_fl_int_fl_int){._0 = 1, ._1 = 2};
    fl_println(fl_string_from_cstr("int_int"));
}

/* Entry point */
int main(int argc, char** argv) {
    _fl_runtime_init(argc, argv);
    fl_tests_typeof_test_main();
    return 0;
}
