# compiler/emitter.py — LModule → C string.
# No decisions. Pure formatting.
#
# Implements RT-8-1-1 through RT-8-5-3.
from __future__ import annotations

from compiler.errors import EmitError
from compiler.lowering import (
    # Top-level
    LModule, LTypeDef, LFnDef, LStaticDef, LEnumDef,
    # Types
    LType, LInt, LFloat, LBool, LChar, LByte, LPtr, LStruct, LVoid, LFnPtr,
    # Expressions
    LExpr, LLit, LVar, LCall, LIndirectCall, LBinOp, LUnary,
    LFieldAccess, LArrow, LIndex, LCast, LAddrOf, LDeref, LBoxDeref,
    LCompound, LCheckedArith, LSizeOf, LTernary, LArrayData, LOptDerefAs,
    # Statements
    LStmt, LVarDecl, LArrayDecl, LAssign, LReturn, LIf, LWhile, LBlock,
    LExprStmt, LGoto, LLabel, LSwitch, LBreak, LContinue,
)


# Map checked arithmetic operators to runtime macros.
_CHECKED_OP_MAP: dict[str, str] = {
    "+": "FL_CHECKED_ADD",
    "-": "FL_CHECKED_SUB",
    "*": "FL_CHECKED_MUL",
    "/": "FL_CHECKED_DIV",
    "%": "FL_CHECKED_MOD",
    "</": "FL_CHECKED_FLOOR_DIV",
}


class Emitter:
    """Formats an LModule as a C source string."""

    def __init__(self, module: LModule, source_file: str, *,
                 is_root: bool = True,
                 extra_static_inits: list[tuple[str, str]] | None = None,
                 line_directives: bool = False) -> None:
        self._module = module
        self._source_file = source_file
        self._is_root = is_root
        self._extra_static_inits = extra_static_inits or []
        self._line_directives = line_directives

        # Output buffer
        self._out: list[str] = []
        self._indent_level: int = 0

        # Temp variable management (reset per function)
        self._tmp_counter: int = 0
        self._pre_stmts: list[str] = []

        # Deferred static string inits (name, init_expr) — initialized at runtime
        self._deferred_static_inits: list[tuple[str, str]] = []

        # Track last emitted #line to avoid duplicates
        self._last_line_directive: int | None = None

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def _emit_line_directive(self, source_line: int | None) -> None:
        """Emit a #line directive if line_directives is enabled and line changed."""
        if not self._line_directives or source_line is None:
            return
        if source_line == self._last_line_directive:
            return
        self._last_line_directive = source_line
        self._out.append(f'#line {source_line} "{self._source_file}"\n')

    @property
    def deferred_static_inits(self) -> list[tuple[str, str]]:
        """Return deferred static inits collected during emit (for multi-module)."""
        return self._deferred_static_inits

    def emit(self) -> str:
        """Emit the full C source string."""
        if self._is_root:
            self._emit_header()
        else:
            self._blank()
            self._emitln(f"/* From: {self._source_file} */")
        self._emit_extern_protos()
        self._emit_forward_decls()
        self._emit_enum_defs()
        self._emit_type_defs()
        self._emit_static_defs()
        self._emit_fn_defs()
        if self._is_root:
            self._emit_entry_point()
        return self._get_output()

    # ------------------------------------------------------------------
    # Buffer infrastructure (RT-8-1-1)
    # ------------------------------------------------------------------

    def _emit(self, s: str) -> None:
        """Append raw text to the output buffer."""
        self._out.append(s)

    def _emitln(self, s: str) -> None:
        """Append an indented line followed by a newline."""
        indent = "    " * self._indent_level
        self._out.append(f"{indent}{s}\n")

    def _blank(self) -> None:
        """Emit a blank line."""
        self._out.append("\n")

    def _indent(self) -> None:
        """Increase indentation by one level."""
        self._indent_level += 1

    def _dedent(self) -> None:
        """Decrease indentation by one level."""
        self._indent_level -= 1

    def _get_output(self) -> str:
        """Join the output buffer into a single string."""
        return "".join(self._out)

    def _fresh_temp(self) -> str:
        """Generate a fresh temp variable name, scoped to the current function.

        Uses _fl_e_ prefix to avoid collision with lowering's _fl_tmp_ temps.
        """
        self._tmp_counter += 1
        return f"_fl_e_{self._tmp_counter}"

    # ------------------------------------------------------------------
    # Header emission (RT-8-1-2)
    # ------------------------------------------------------------------

    def _emit_header(self) -> None:
        """Emit the file header comment and #include."""
        self._emitln("/* Generated by flowc - do not edit */")
        self._emitln(f"/* Source: {self._source_file} */")
        self._emitln('#include "flow_runtime.h"')

    # ------------------------------------------------------------------
    # Extern FFI declarations
    # ------------------------------------------------------------------

    def _emit_extern_protos(self) -> None:
        """Emit extern C function prototypes for FFI bindings."""
        if not self._module.extern_fn_protos:
            return
        self._blank()
        self._emitln("/* Extern FFI declarations */")
        for fn_name, param_ltypes, ret_ltype in self._module.extern_fn_protos:
            ret_str = self._emit_ltype(ret_ltype)
            if param_ltypes:
                params_str = ", ".join(
                    self._emit_ltype(pt) for pt in param_ltypes)
            else:
                params_str = "void"
            self._emitln(f"extern {ret_str} {fn_name}({params_str});")

    # ------------------------------------------------------------------
    # Forward declarations (RT-8-2-2, RT-8-3-2)
    # ------------------------------------------------------------------

    def _emit_forward_decls(self) -> None:
        """Emit forward declarations for struct types and function prototypes."""
        if not self._module.type_defs and not self._module.fn_defs:
            return

        # Forward-declare struct types (needed for mutually-referencing structs)
        for td in self._module.type_defs:
            self._blank()
            self._emitln(f"typedef struct {td.c_name} {td.c_name};")

        # Forward-declare function prototypes (needed for mutual recursion)
        # Only emit when there are type defs or multiple functions
        if self._module.type_defs or len(self._module.fn_defs) > 1:
            for fn in self._module.fn_defs:
                self._blank()
                proto = self._fn_prototype(fn)
                self._emitln(f"{proto};")

    # ------------------------------------------------------------------
    # Enum definition emission
    # ------------------------------------------------------------------

    def _emit_enum_defs(self) -> None:
        """Emit all enum type definitions."""
        for ed in self._module.enum_defs:
            self._blank()
            self._emitln(f"typedef enum {{")
            self._indent()
            for i, (name, val) in enumerate(ed.variants):
                comma = "," if i < len(ed.variants) - 1 else ""
                self._emitln(f"{name} = {val}{comma}")
            self._dedent()
            self._emitln(f"}} {ed.c_name};")

    # ------------------------------------------------------------------
    # Type definition emission (RT-8-2-1)
    # ------------------------------------------------------------------

    @staticmethod
    def _topo_sort_type_defs(type_defs: list[LTypeDef]) -> list[LTypeDef]:
        """Topologically sort type definitions so that by-value dependencies
        are emitted before the types that embed them.

        A struct A depends on struct B (by-value) when A has a field of type
        LStruct(c_name=B.c_name) — not behind a pointer.  Pointer references
        only need the forward declaration, which is already emitted earlier.
        """
        names = {td.c_name for td in type_defs}
        name_to_td = {td.c_name: td for td in type_defs}

        # Collect by-value struct dependencies for each type def.
        def _by_value_deps(td: LTypeDef) -> set[str]:
            deps: set[str] = set()
            for _, ft in td.fields:
                if isinstance(ft, LStruct) and ft.c_name in names:
                    deps.add(ft.c_name)
            return deps

        # Kahn's algorithm for topological sort.
        in_degree: dict[str, int] = {n: 0 for n in names}
        adj: dict[str, list[str]] = {n: [] for n in names}
        for td in type_defs:
            for dep in _by_value_deps(td):
                adj[dep].append(td.c_name)
                in_degree[td.c_name] += 1

        queue = [n for n in names if in_degree[n] == 0]
        # Maintain original relative order among zero-in-degree nodes.
        order_idx = {td.c_name: i for i, td in enumerate(type_defs)}
        queue.sort(key=lambda n: order_idx[n])

        result: list[LTypeDef] = []
        while queue:
            n = queue.pop(0)
            result.append(name_to_td[n])
            for m in adj[n]:
                in_degree[m] -= 1
                if in_degree[m] == 0:
                    queue.append(m)
                    queue.sort(key=lambda n: order_idx[n])

        # If there's a cycle (shouldn't happen with valid structs), append
        # remaining in original order.
        if len(result) < len(type_defs):
            seen = {td.c_name for td in result}
            for td in type_defs:
                if td.c_name not in seen:
                    result.append(td)

        return result

    def _emit_type_defs(self) -> None:
        """Emit all type definitions, topologically sorted so by-value
        struct dependencies come first."""
        sorted_defs = self._topo_sort_type_defs(self._module.type_defs)
        for td in sorted_defs:
            self._blank()
            self._emit_type_def(td)

    def _emit_type_def(self, td: LTypeDef) -> None:
        """Emit a single struct typedef."""
        self._emitln(f"struct {td.c_name} {{")
        self._indent()
        for field_name, field_type in td.fields:
            self._emitln(f"{self._format_decl(field_type, field_name)};")
        self._dedent()
        self._emitln("};")

    # ------------------------------------------------------------------
    # Static/global emission (RT-8-4-1)
    # ------------------------------------------------------------------

    def _emit_static_defs(self) -> None:
        """Emit all static/global definitions."""
        for sd in self._module.static_defs:
            self._blank()
            self._emit_static_def(sd)

    def _is_string_ptr(self, t: LType) -> bool:
        """Check if a type is FL_String* (not compile-time constant)."""
        return isinstance(t, LPtr) and isinstance(t.inner, LStruct) and t.inner.c_name == "FL_String"

    def _emit_static_def(self, sd: LStaticDef) -> None:
        """Emit a single static/global definition."""
        type_str = self._emit_ltype(sd.c_type)
        # String statics can't be initialized at compile time — defer to runtime
        if self._is_string_ptr(sd.c_type) and sd.init is not None:
            self._emitln(f"{type_str} {sd.c_name} = NULL;")
            self._deferred_static_inits.append(
                (sd.c_name, self._emit_expr(sd.init)))
            return
        if sd.is_mut:
            if sd.init is not None:
                self._emitln(f"{type_str} {sd.c_name} = {self._emit_expr(sd.init)};")
            else:
                self._emitln(f"{type_str} {sd.c_name};")
        else:
            if sd.init is not None:
                self._emitln(f"static const {type_str} {sd.c_name} = {self._emit_expr(sd.init)};")
            else:
                self._emitln(f"static const {type_str} {sd.c_name};")

    # ------------------------------------------------------------------
    # Function emission (RT-8-3-1)
    # ------------------------------------------------------------------

    def _emit_fn_defs(self) -> None:
        """Emit all function definitions."""
        for fn in self._module.fn_defs:
            self._blank()
            self._emit_fn_def(fn)

    def _emit_entry_point(self) -> None:
        """Emit a C main() wrapper if the module has an entry point."""
        ep = self._module.entry_point
        if ep is None:
            return
        # Merge extra static inits from dependency modules.
        all_static_inits = self._extra_static_inits + self._deferred_static_inits
        # Emit static string init function if there are deferred inits
        if all_static_inits:
            self._blank()
            self._emitln("static void _fl_init_statics(void) {")
            self._indent_level += 1
            for name, init_expr in all_static_inits:
                self._emitln(f"{name} = {init_expr};")
                # Pin interned strings so retain/release never frees them
                if name.startswith("_fl_str_"):
                    self._emitln(f"{name}->refcount = 2147483647;")
            self._indent_level -= 1
            self._emitln("}")
        self._blank()
        self._emitln("/* Entry point */")
        self._emitln("int main(int argc, char** argv) {")
        self._indent_level += 1
        self._emitln("_fl_runtime_init(argc, argv);")
        if all_static_inits:
            self._emitln("_fl_init_statics();")
        self._emitln(f"{ep}();")
        self._emitln("return 0;")
        self._indent_level -= 1
        self._emitln("}")

    def _emit_fn_def(self, fn: LFnDef) -> None:
        """Emit a single function definition."""
        self._emit_line_directive(fn.source_line)
        if fn.source_name:
            self._emitln(f"/* Flow: {fn.source_name} */")
        proto = self._fn_prototype(fn)
        self._emitln(proto + " {")
        self._indent()

        # Reset temp counter per function
        self._tmp_counter = 0

        for stmt in fn.body:
            self._emit_stmt(stmt)

        self._dedent()
        self._emitln("}")

    def _fn_prototype(self, fn: LFnDef) -> str:
        """Format a function prototype string (without trailing semicolon or brace)."""
        ret_str = self._emit_ltype(fn.ret)
        if fn.params:
            params_str = ", ".join(
                self._format_decl(ptype, pname)
                for pname, ptype in fn.params
            )
        else:
            params_str = "void"
        return f"{ret_str} {fn.c_name}({params_str})"

    # ------------------------------------------------------------------
    # Type formatting (RT-8-2-3)
    # ------------------------------------------------------------------

    def _emit_ltype(self, t: LType) -> str:
        """Return the C type string for an LType."""
        match t:
            case LInt(width=32, signed=True):
                return "fl_int"
            case LInt(width=32, signed=False):
                return "fl_uint"
            case LInt(width=16, signed=True):
                return "fl_int16"
            case LInt(width=16, signed=False):
                return "fl_uint16"
            case LInt(width=64, signed=True):
                return "fl_int64"
            case LInt(width=64, signed=False):
                return "fl_uint64"
            case LFloat(width=64):
                return "fl_float"
            case LFloat(width=32):
                return "fl_float32"
            case LBool():
                return "fl_bool"
            case LChar():
                return "fl_char"
            case LByte():
                return "fl_byte"
            case LPtr(inner=inner):
                return self._emit_ltype(inner) + "*"
            case LStruct(c_name=name):
                return name
            case LVoid():
                return "void"
            case LFnPtr(params=params, ret=ret):
                ret_str = self._emit_ltype(ret)
                params_str = ", ".join(self._emit_ltype(p) for p in params)
                if not params_str:
                    params_str = "void"
                return f"{ret_str} (*)({params_str})"
            case _:
                raise EmitError(
                    message=f"unknown LType: {t}",
                    file=self._source_file,
                    line=0,
                    col=0,
                )

    def _format_decl(self, t: LType, name: str) -> str:
        """Format a variable/parameter declaration: 'type name'.

        Handles function pointers specially since the name goes inside the type.
        """
        match t:
            case LFnPtr(params=params, ret=ret):
                ret_str = self._emit_ltype(ret)
                params_str = ", ".join(self._emit_ltype(p) for p in params)
                if not params_str:
                    params_str = "void"
                return f"{ret_str} (*{name})({params_str})"
            case _:
                return f"{self._emit_ltype(t)} {name}"

    # ------------------------------------------------------------------
    # Statement emission (RT-8-3-3, RT-8-3-6)
    # ------------------------------------------------------------------

    def _emit_stmt(self, stmt: LStmt) -> None:
        """Emit a single statement, dispatching by type."""
        self._emit_line_directive(getattr(stmt, 'source_line', None))
        match stmt:
            case LVarDecl(c_name=name, c_type=ctype, init=init):
                self._emit_var_decl(name, ctype, init)
            case LArrayDecl(c_name=name, elem_type=elt, count=n):
                self._emitln(f"{self._emit_ltype(elt)} {name}[{n}];")
            case LAssign(target=target, value=value):
                self._emit_assign(target, value)
            case LReturn(value=value):
                self._emit_return(value)
            case LExprStmt(expr=expr):
                self._emit_expr_stmt(expr)
            case LIf(cond=cond, then=then, else_=else_):
                self._emit_if(cond, then, else_)
            case LWhile(cond=cond, body=body):
                self._emit_while(cond, body)
            case LBlock(stmts=stmts):
                self._emit_block(stmts)
            case LSwitch(value=value, cases=cases, default=default):
                self._emit_switch(value, cases, default)
            case LGoto(label=label):
                self._emitln(f"goto {label};")
            case LLabel(name=name):
                # Labels are not indented — they go to column 0 within the function.
                # Use a statement after the label to avoid "label at end of compound statement".
                self._emit(f"{name}:;\n")
            case LBreak():
                self._emitln("break;")
            case LContinue():
                self._emitln("continue;")
            case _:
                raise EmitError(
                    message=f"unknown LStmt: {stmt}",
                    file=self._source_file,
                    line=0,
                    col=0,
                )

    def _flush_pre_stmts(self) -> None:
        """Emit any hoisted pre-statements (from LCheckedArith etc.) and clear the list."""
        for s in self._pre_stmts:
            self._emitln(s)
        self._pre_stmts = []

    def _emit_var_decl(self, name: str, ctype: LType, init: LExpr | None) -> None:
        """Emit a variable declaration."""
        if init is not None:
            saved = self._pre_stmts
            self._pre_stmts = []
            init_str = self._emit_expr(init)
            self._flush_pre_stmts()
            self._pre_stmts = saved
            self._emitln(f"{self._format_decl(ctype, name)} = {init_str};")
        else:
            self._emitln(f"{self._format_decl(ctype, name)};")

    def _emit_assign(self, target: LExpr, value: LExpr) -> None:
        """Emit an assignment statement."""
        saved = self._pre_stmts
        self._pre_stmts = []
        target_str = self._emit_expr(target)
        value_str = self._emit_expr(value)
        self._flush_pre_stmts()
        self._pre_stmts = saved
        self._emitln(f"{target_str} = {value_str};")

    def _emit_return(self, value: LExpr | None) -> None:
        """Emit a return statement."""
        if value is not None:
            saved = self._pre_stmts
            self._pre_stmts = []
            value_str = self._emit_expr(value)
            self._flush_pre_stmts()
            self._pre_stmts = saved
            self._emitln(f"return {value_str};")
        else:
            self._emitln("return;")

    def _emit_expr_stmt(self, expr: LExpr) -> None:
        """Emit an expression statement."""
        saved = self._pre_stmts
        self._pre_stmts = []
        expr_str = self._emit_expr(expr)
        self._flush_pre_stmts()
        self._pre_stmts = saved
        self._emitln(f"{expr_str};")

    def _strip_outer_parens(self, s: str) -> str:
        """Remove one layer of outer matching parens from a C expression string.

        BinOp expressions are emitted as '(left op right)'. When used as the
        condition in 'if (cond)' or 'while (cond)', the result is '((left op right))'
        with redundant double parens. This helper removes the outer pair when the
        parens span the entire string, producing 'if (left op right)' instead.
        """
        if len(s) < 2 or s[0] != '(' or s[-1] != ')':
            return s
        depth = 0
        for i, c in enumerate(s):
            if c == '(':
                depth += 1
            elif c == ')':
                depth -= 1
            if depth == 0:
                if i == len(s) - 1:
                    return s[1:-1]
                else:
                    return s  # outer paren closes before end — not a wrapping pair
        return s

    def _emit_if(self, cond: LExpr, then: list[LStmt],
                 else_: list[LStmt]) -> None:
        """Emit an if/else statement."""
        saved = self._pre_stmts
        self._pre_stmts = []
        cond_str = self._emit_expr(cond)
        self._flush_pre_stmts()
        self._pre_stmts = saved

        self._emitln(f"if ({self._strip_outer_parens(cond_str)}) {{")
        self._indent()
        for s in then:
            self._emit_stmt(s)
        self._dedent()
        if else_:
            self._emitln("} else {")
            self._indent()
            for s in else_:
                self._emit_stmt(s)
            self._dedent()
        self._emitln("}")

    def _emit_while(self, cond: LExpr, body: list[LStmt]) -> None:
        """Emit a while loop.

        When the condition produces pre-statements (e.g. FL_CHECKED_MUL for
        ``d * d <= n``), those pre-statements must be re-evaluated on every
        iteration, not just once before the loop.  We detect this case and
        emit a ``while (1) { <pre-stmts>; if (!cond) break; <body> }`` loop
        so the temporaries are recomputed each time.
        """
        saved = self._pre_stmts
        self._pre_stmts = []
        cond_str = self._emit_expr(cond)
        cond_pre = list(self._pre_stmts)
        self._pre_stmts = saved

        if cond_pre:
            # Condition has side-effecting pre-statements that must run
            # each iteration (e.g. checked-arithmetic temps).
            self._emitln("while (1) {")
            self._indent()
            for s in cond_pre:
                self._emitln(s)
            self._emitln(f"if (!({self._strip_outer_parens(cond_str)})) break;")
            for s in body:
                self._emit_stmt(s)
            self._dedent()
            self._emitln("}")
        else:
            self._emitln(f"while ({self._strip_outer_parens(cond_str)}) {{")
            self._indent()
            for s in body:
                self._emit_stmt(s)
            self._dedent()
            self._emitln("}")

    def _emit_block(self, stmts: list[LStmt]) -> None:
        """Emit a block statement."""
        self._emitln("{")
        self._indent()
        for s in stmts:
            self._emit_stmt(s)
        self._dedent()
        self._emitln("}")

    def _emit_switch(self, value: LExpr, cases: list[tuple[int, list[LStmt]]],
                     default: list[LStmt]) -> None:
        """Emit a switch statement."""
        saved = self._pre_stmts
        self._pre_stmts = []
        value_str = self._emit_expr(value)
        self._flush_pre_stmts()
        self._pre_stmts = saved

        self._emitln(f"switch ({value_str}) {{")
        self._indent()
        for case_val, case_stmts in cases:
            self._emitln(f"case {case_val}: {{")
            self._indent()
            for s in case_stmts:
                self._emit_stmt(s)
            self._emitln("break;")
            self._dedent()
            self._emitln("}")
        if default:
            self._emitln("default: {")
            self._indent()
            for s in default:
                self._emit_stmt(s)
            self._emitln("break;")
            self._dedent()
            self._emitln("}")
        self._dedent()
        self._emitln("}")

    # ------------------------------------------------------------------
    # Expression emission (RT-8-3-4, RT-8-3-5, RT-8-3-7)
    # ------------------------------------------------------------------

    def _emit_expr(self, expr: LExpr) -> str:
        """Emit a C expression string for an LExpr node."""
        match expr:
            case LLit(value=value):
                return value
            case LVar(c_name=name):
                return name
            case LCall(fn_name=fn, args=args):
                args_str = ", ".join(self._emit_expr(a) for a in args)
                return f"{fn}({args_str})"
            case LIndirectCall(fn_ptr=fn_ptr, args=args):
                fn_str = self._emit_expr(fn_ptr)
                args_str = ", ".join(self._emit_expr(a) for a in args)
                return f"{fn_str}({args_str})"
            case LBinOp(op=op, left=left, right=right):
                return f"({self._emit_expr(left)} {op} {self._emit_expr(right)})"
            case LUnary(op=op, operand=operand):
                return f"({op}{self._emit_expr(operand)})"
            case LFieldAccess(obj=obj, field=field):
                return f"{self._emit_expr(obj)}.{field}"
            case LArrow(ptr=ptr, field=field):
                return f"{self._emit_expr(ptr)}->{field}"
            case LIndex(arr=arr, idx=idx):
                return f"{self._emit_expr(arr)}[{self._emit_expr(idx)}]"
            case LCast(inner=inner, c_type=ctype):
                return f"(({self._emit_ltype(ctype)}){self._emit_expr(inner)})"
            case LAddrOf(inner=inner):
                return f"(&{self._emit_expr(inner)})"
            case LDeref(inner=inner):
                return f"(*{self._emit_expr(inner)})"
            case LBoxDeref(inner=inner, boxed_type=bt):
                return f"FL_BOX_DEREF({self._emit_expr(inner)}, {self._emit_ltype(bt)})"
            case LSizeOf(c_type=ctype):
                return f"sizeof({self._emit_ltype(ctype)})"
            case LTernary(cond=cond, then_expr=then_expr, else_expr=else_expr):
                return (f"({self._emit_expr(cond)} ? "
                        f"{self._emit_expr(then_expr)} : "
                        f"{self._emit_expr(else_expr)})")
            case LOptDerefAs(inner=inner, val_type=val_type, c_type=opt_type):
                return (f"FL_OPT_DEREF_AS({self._emit_expr(inner)}, "
                        f"{self._emit_ltype(val_type)}, "
                        f"{self._emit_ltype(opt_type)})")
            case LCompound(fields=fields, c_type=ctype):
                fields_str = ", ".join(
                    f".{name} = {self._emit_expr(val)}"
                    for name, val in fields
                )
                return f"({self._emit_ltype(ctype)}){{{fields_str}}}"
            case LArrayData(elements=elements, elem_type=etype):
                elems_str = ", ".join(self._emit_expr(e) for e in elements)
                return f"({self._emit_ltype(etype)}[]){{{elems_str}}}"
            case LCheckedArith(op=op, left=left, right=right, c_type=ctype):
                tmp = self._fresh_temp()
                type_str = self._emit_ltype(ctype)
                # Float modulo uses fmod via FL_CHECKED_FMOD
                if op == "%" and isinstance(ctype, LFloat):
                    macro = "FL_CHECKED_FMOD"
                else:
                    macro = _CHECKED_OP_MAP.get(op)
                if macro is None:
                    raise EmitError(
                        message=f"no checked arithmetic macro for operator '{op}'",
                        file=self._source_file,
                        line=0,
                        col=0,
                    )
                left_str = self._emit_expr(left)
                right_str = self._emit_expr(right)
                self._pre_stmts.append(f"{type_str} {tmp};")
                self._pre_stmts.append(f"{macro}({left_str}, {right_str}, &{tmp});")
                return tmp
            case _:
                raise EmitError(
                    message=f"unknown LExpr: {expr}",
                    file=self._source_file,
                    line=0,
                    col=0,
                )
